### ISSUE TITLE
ActionScript code formatting support

### ISSUE THREAD

**Issue by 22Round** [BowlerHatLLC/vscode-as3mxml#176]
> Sorry, but there is no formatter for 'nextgenas'-files installed.

@joshtynjala do you plan to support code formatting?

**Comment by joshtynjala** [comment]
Perhaps in a future update! I haven't looked into how to implement code formatting yet. I suspect that this is not a trivial task, and it will definitely take some research. I'll keep it in mind for after 1.0.

**Comment by 22Round** [comment]
I am slowly moving from FlashDevelop, FlashBuilder to VSCode+nextgenas and formatting feature would be grate addition, keep going!

**Comment by leitwolf** [comment]
A format tool here: [Actionscript Tools](https://marketplace.visualstudio.com/items?itemName=lonewolf.vscode-astools)

**Comment by varadig** [comment]
what about mxml formatting? I can format .as files, but not mxml.....

![Screenshot 2019-03-11 16 48 46](https://user-images.githubusercontent.com/6317148/54137262-9b320e00-441d-11e9-9eff-5046640bef28.png)
![Uploading Screenshot 2019-03-11 16.47.11.png…]()

**Comment by joshtynjala** [comment]
@varadig vscode-as3mxml does not support formatting .as files. I assume that you're using the extension that @leitwolf posted, and you meant to ask here instead: https://github.com/leitwolf/vscode-ASTools/issues

**Comment by varadig** [comment]
@joshtynjala you are right, I forgot to write, I use that tool.

**Comment by esidegallery** [comment]
I use Beautify to format MXML and it works pretty well. Just include mxml in the html list under beautify.language. I also set the preference `"html.format.wrapAttributes": "preserve-aligned"` to match how Flash Builder aligns attributes.

**Comment by esidegallery** [comment]
p.s. I haven't looked into it yet, but surely a JS formatter could do the job for .as formatting.

**Comment by MESepehr** [comment]
Unfortunately after upgrading Vscode  to version 1.35.1 ,actionScript code formatting tools [Actionscript Tools](https://marketplace.visualstudio.com/items?itemName=lonewolf.vscode-astools) does n't work

**Comment by leitwolf** [comment]
@MESepehr fixed.

**Comment by yooni126** [comment]
@leitwolf 

when I choose FormatDocument in rightClick menu nothing happened also when I run this command with a shortcut key (ALT+SHIFT+F) vscode prompt me that unable to access jar file!

**Comment by yooni126** [comment]
![image](https://user-images.githubusercontent.com/3766387/89117566-fdc4f780-d4b3-11ea-8556-cc1371f84755.png)

**Comment by yooni126** [comment]
![image](https://user-images.githubusercontent.com/3766387/89117647-bb4fea80-d4b4-11ea-91df-edae0ac56457.png)

**Comment by leitwolf** [comment]
@yooni126 invalid path? a blank in the path?

**Comment by yooni126** [comment]
yes, it's a ridiculous message! in fact, my windows account is "Mr.Tolid Moblie" but I don't know the rest of the message !

**Comment by yooni126** [comment]
also I set this command is setting.json 

```
    "as3mxml.sdk.framework": "f:\\Tools\\AirSDK\\Air32",
    "as3mxml.java.path": "c:\\Program Files\\Java\\jdk1.8.0_51\\bin\\java.exe",
    "editor.formatOnSave": true,
```

**Comment by esidegallery** [comment]
This issue can probably be closed thanks to the new asformat
