### ISSUE TITLE
Package release (captive runtime) task for Adobe AIR does not remove intermediate files

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-as3mxml#184]
When package release (captive runtime) task is run:
![image](https://user-images.githubusercontent.com/1468887/36875593-e0c90ce6-1db0-11e8-959e-049b072497c1.png)

it creates unnecessary files:
![image](https://user-images.githubusercontent.com/1468887/36875649-34df182a-1db1-11e8-9f4f-14beff3ff53d.png)

The `Main.air` directory has it all that app needs to run.

BTW: `Main.air` name is more like name of a file, maybe something like `Main-app` is more appropriate name for a directory. At least in Windows OS.

**Comment by joshtynjala** [comment]
Those are just intermediate files produced during the build process. They're what get packaged up into the AIR app. I guess I could probably safely delete them at the end of a release build.

The name should be exactly what you specified in *asconfig.json* in airOptions for the output value. Or did you not specify the AIR output path? In that case, I guess it might have tried to guess an appropriate name, and I could probably make that smarter.

Thanks for all the bug reports recently, by the way. Good to see someone really digging in and trying it all out!

**Comment by neminovno** [comment]
> I could probably safely delete them at the end of a release build.

That would be great. So release directory is "clean".

I just figured out that output value does not have to be .air always :) Look https://github.com/BowlerHatLLC/vscode-nextgenas/issues/164 
Probably because when using ADT manually, as I remember, one must always have .air somewhere within command options.

You are welcome. Thank you for your great work here that you do! :+1:
