### ISSUE TITLE
Problem within curly brackets in MXML tag's property underlines all lines from beginning down to the line with the problem

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-as3mxml#199]
For example this code:
```
<?xml version="1.0" encoding="utf-8"?>
<s:Group xmlns:fx="http://ns.adobe.com/mxml/2009"
    xmlns:s="library://ns.adobe.com/flex/spark">
    
    <s:ComboBox id="comboBox"
                dataProvider="{aaa}"/>

    <s:Button click="bbb"/>
</s:Group>
```

If there is no bbb, click is underlined - ok
If there is bbb, bbb is underlined - ok
If there is no aaa, it's null, nothing is underlined - ok
But if there is aaa, all lines are red underlined down to aaa - not ok. Only aaa should be underlined.

Preview:
![2018-04-16_02-52-27](https://user-images.githubusercontent.com/1468887/38785511-41ce3f64-4121-11e8-86f6-54e3da248df4.gif)

**Comment by joshtynjala** [comment]
Thanks! I'll take a look.

**Comment by joshtynjala** [comment]
I have determined that this is a bug in the Apache Royale compiler. It's returning correct values for the start line and column, but the end line and column are incorrect.

**Comment by joshtynjala** [comment]
I made changes to the Apache Royale compiler that fixes this issue:

apache/royale-compiler#41

Once these changes are released in an official build of Royale, I can close this issue.

**Comment by joshtynjala** [comment]
Confirmed to be fixed after updating Apache Royale dependency to 0.9.4.
