### ISSUE TITLE
Show Warning in Problems panel for untyped events (parameters)

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-as3mxml#210]
Example code:
```
<?xml version="1.0" encoding="utf-8"?>
<s:WindowedApplication xmlns:fx="http://ns.adobe.com/mxml/2009"
   xmlns:s="library://ns.adobe.com/flex/spark">
	<fx:Script>
		<![CDATA[

			private function onClick(event):void {}

		]]>
	</fx:Script>
</s:WindowedApplication>
```

This warning is only visible in Terminal when build is run:

> Warning: parameter 'event' has no type declaration.
> 
>                         private function onClick(event):void {}

**Comment by joshtynjala** [comment]
There's a good chance that this is a bug in the Royale compiler that powers the code intelligence. I'll take a look, though. Maybe I missed somewhere that errors are being reported.

Can you verify for me that you haven't set the warnings compiler option to false in asconfig.json?

**Comment by neminovno** [comment]
I haven't set the warnings compiler option in asconfig.json
It is 'default one':
```
{
	"config": "air",
	"compilerOptions": {
		"output": "bin/Main.swf"
	},
	"application": "src/Main-app.xml",
	"files": [
		"src/Main.mxml"
	]
}
```

**Comment by joshtynjala** [comment]
Okay, thanks!

**Comment by joshtynjala** [comment]
I added a new warning for untyped function parameters to the Apache Royale compiler.

apache/royale-compiler@e8557a39f6f4d7ca219b24c9f6552651382191d6

This change will be included in the VSCode extension after the next Royale release. In the meantime, the `as3mxml.sdk.editor` setting can be used with a nightly build of Royale to take advantage of this change early.
