### ISSUE TITLE
Show Error in Problems panel if MXML tag properties are not properly defined

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-as3mxml#211]
Example code:
```
<?xml version="1.0" encoding="utf-8"?>
<s:WindowedApplication xmlns:fx="http://ns.adobe.com/mxml/2009"
   xmlns:s="library://ns.adobe.com/flex/spark">

	<s:Rect width="20" height="10">
		<s:stroke>
			<s:SolidColorStroke color="0" weight=""/>
		</s:stroke>
	</s:Rect>

	<s:Rect width="20" height="10">
		<s:stroke>
			<s:SolidColorStroke color="#" weight="1"/>
		</s:stroke>
	</s:Rect>

	<s:Ellipse width="" height=""/>

</s:WindowedApplication>

```

These errors are visible only in Terminal when build is run:

> C:\dev\flex\qtp\src\Main.mxml(7): Error: Initializer for 'weight': cannot parse value of type Number from text ''.
> 
>                         <s:SolidColorStroke color="0" weight=""/>
> 
> C:\dev\flex\qtp\src\Main.mxml(13): Error: Initializer for 'color': cannot parse value of type uint from text '#'.
> 
>                         <s:SolidColorStroke color="#" weight="1"/>
> 
> C:\dev\flex\qtp\src\Main.mxml(17): Error: Initializer for 'width': cannot parse value of type Number from text ''.
> 
>         <s:Ellipse width="" height=""/>
> 
> C:\dev\flex\qtp\src\Main.mxml(17): Error: Initializer for 'height': cannot parse value of type Number from text ''.
> 
>         <s:Ellipse width="" height=""/>
> 
> The terminal process terminated with exit code: 4

**Comment by neminovno** [comment]
Also there should be Error in Problems panel if Image source is empty string:

`<s:Image source="@Embed(source='')"/>`

> Error: Unable to create source Main__embed_mxml__1466165722.: String index out of range: 0

**Comment by joshtynjala** [comment]
Commit apache/royale-compiler@52f24d44a2185b6553bfc26dd6067662925b70af will fix this issue.

**Comment by joshtynjala** [comment]
Confirmed to be fixed after updating Apache Royale dependency to 0.9.4.
