### ISSUE TITLE
Packaging failed, when using files option in asconfig.json

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-as3mxml#225]
When trying to package captive runtime with icons:
```
"files": [
		{
			"file": "icons/icon-48.png",
			"path": "."
		}
	]
```
this error appears:

> Packaging failed. Packager internal error
> The terminal process terminated with exit code: 12

and that exit code is:

> 12 | Invalid input | Verify file paths and other arguments passed to ADT on the command line.

Same for:
`"file": "icons\\icon-48.png",`

If package shared runtime is choosen, error is:

> Files 
> "C:\dev\project\icons\icon-48.png" and 
> "C:\dev\project\icons\icon-48.png" have conflicting package paths: 
> C:\dev\project\icons\icon-48.png

That error does not appear if directory name is used for destination:
`"path": "icons"`
or
`"path": "./icons"`

but then, in output, there is file named icons created but not directory:
![image](https://user-images.githubusercontent.com/1468887/41249287-fde3a8f6-6db3-11e8-8e4c-c7aafd428b74.png)

Os: Windows 7

Note: I have not used `<icon>` in _Main-app.xml_

**Comment by joshtynjala** [comment]
Try this instead:

```
"files": [
		{
			"file": "icons/icon-48.png",
			"path": "icon-48.png"
		}
	]
```

Adobe's documentation for the `-e` command line option says that the destination path is supposed to be a directory, but I think that it actually needs to be the file path.

**Comment by neminovno** [comment]
Thanks! It works.

**Comment by neminovno** [comment]
Just to confirm, so this:
```
	"files": [
		{
			"file": "icons",
			"path": "icons"
		}
	]
```
 should not work?
That setting outputs this error:

>Error: Failed to parse Adobe AIR options.
> java.lang.NullPointerException
>         at com.nextgenactionscript.asconfigc.air.AIROptionsParser.addFile(AIROptionsParser.java:325)
>         at com.nextgenactionscript.asconfigc.air.AIROptionsParser.parseFiles(AIROptionsParser.java:310)
>         at com.nextgenactionscript.asconfigc.air.AIROptionsParser.parse(AIROptionsParser.java:205)
>         at com.nextgenactionscript.asconfigc.ASConfigC.readAIROptions(ASConfigC.java:472)
>         at com.nextgenactionscript.asconfigc.ASConfigC.parseConfig(ASConfigC.java:367)
>         at com.nextgenactionscript.asconfigc.ASConfigC.<init>(ASConfigC.java:158)
>         at com.nextgenactionscript.asconfigc.ASConfigC.main(ASConfigC.java:133)
> 
> The terminal process terminated with exit code: 1

**Comment by joshtynjala** [comment]
That should work.

**Comment by neminovno** [comment]
Great. 
By the way, than maybe these names for properties are more appropriate:
```
"files": [
		{
			"source": "icons",
			"destination": "icons"
		}
	]
```

**Comment by neminovno** [comment]
If dot is used for path, like in examples from Wiki:
```
"files": [
		{
			"file": "icons/icon48.png",
			"path": "."
		}
```
it still doesn't work, now the error is:

> Invalid destination path for file in Adobe AIR application. Source: icons/icon48.png, Destination: .
> The terminal process terminated with exit code: 1

**Comment by neminovno** [comment]
So, as I just tested, only option to add files to sub-directory of the app is to add complete folder, this way:
```
"files": [
            {
                "file": "icons",
                "path": "icons"
            }
        ]
```

as this does not work:
```
"files": [
            {
                "file": "icons/icon-48.png",
                "path": "icons/icon-48.png"
            }
        ]
```
