### ISSUE TITLE
Adobe AIR packaging: add option to save storepass for the current session

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/vscode-as3mxml#240]
Similar to other IDEs, like Flash Builder and IntelliJ IDEA.

Show some kind of UI to collect it before **asconfigc** is executed, and pass it on as a command line option.

This is more secure than allowing users to specify the storepass in the plain text *asconfig.json*.

**Comment by neminovno** [comment]
Maybe solution would be to store it in [local storage or in workspace state](https://code.visualstudio.com/docs/extensionAPI/vscode-api#ExtensionContext) until it is closed.

**Comment by joshtynjala** [comment]
I should be able to simply store the password in a variable somewhere (to be sure that it is forgotten when exiting... Or even crashing, in the worst case). It's getting the UI right that I really need to look at. VSCode doesn't expose a lot of UI options, and it would be easy to make something more annoying than the current behavior of typing the password into the terminal.

**Comment by joshtynjala** [comment]
[asconfigc](https://www.npmjs.com/package/asconfigc) v0.10 will support a new `storepass` command line option.

This will make it possible to specify the password in *tasks.json*. Putting the plaintext password in *tasks.json* is **not recommended**, for the same reason why there is no `storepass` field included in *asconfig.json*: Storing a password in plaintext is **insecure**, and you risk exposing it by accidentally committing it to a repository.

However, *tasks.json* has some interesting macros that will allow us to specify the password in a better way. For instance, you can tell it to prompt for a password in the UI (which is better than in the terminal, as it currently does). See an example of this below:

``` json5
{
	// See https://go.microsoft.com/fwlink/?LinkId=733558
	// for the documentation about the tasks.json format
	"version": "2.0.0",
	"tasks": [
		{
			"label": "asconfigc AIR android",
			"type": "shell",
			"command": "asconfigc",
			"args": [
				"--sdk=${config:as3mxml.sdk.framework}",
				"--debug=false",
				"--air=android",
				"--storepass=${input:android_password}"
			],
			"problemMatcher": []
		}
	],
    "inputs": [
        {
            "id": "android_password",
            "description": "Enter your Adobe AIR certificate password for Android.",
            "type": "promptString"
        }
    ]
}
```

Notice that `--storepass` is set to `${input:android_password}`, which is the macro that will cause VSCode to prompt the user for the password.

You may have also noticed that the `--sdk` option is set to `${config:as3mxml.sdk.framework}`, which will make asconfigc compile using the SDK that is configured in the project settings.

It's now also possible to call a command from *tasks.json*, which should make it possible to prompt for the password, and also store it for the current session.

**Comment by joshtynjala** [comment]
Starting in v0.17 of the AS3 & MXML extension, it will be possible to save your certificate password for signing Adobe AIR apps. You can define a custom task that runs the command line version of [**asconfigc**](https://www.npmjs.com/package/asconfigc). The new `as3mxml.saveSessionPassword` command may be used to define the `storepass` command line option to pass to asconfigc.

``` json5
{
	"label": "package Adobe AIR app (Android)",
	"type": "shell",
	"command": "asconfigc",
	"args": [
		"--sdk=${config:as3mxml.sdk.framework}",
		"--debug=false",
		"--air=android",
		"--storepass=${command:as3mxml.saveSessionPassword}"
	],
	"problemMatcher": []
}
```
