### ISSUE TITLE
Remove unwanted framework classes/SWCs from completion

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-as3mxml#275]
Hi Josh,

one thing that will improve the user experience will be the capability to remove unwanted libraries in SDK. In Royale (and in Flex), we have various UI sets, and that means many classes that does the same 
In concrete in Royale we have Jewel, Basic, MDL, Express, CreateJS, Flat, and now MX, Spark... that means that writing "check" and hitting CTRL+SPACE outputs 9 possible "CheckBox" classes. Then the user has to start pressing up/down buttons and see the CheckBox he wants to import.

I think we should have some way to remove all extra libs. In Royale if I use Jewel as UI set (and taking into account that current state with Basic UI set as part of the linking), we should only see 2 options: Jewel CheckBox and Basic CheckBox. (If I get the team accept to separate Basic UI TLDs to other lib, we should only get one CheckBox over time).

So **my feature request should be to be able to configure AS3 & MXML extension to exclude SWCs of the SDK that we don't want enter in the code IntelliSense mechanism**. I think this could be not too hard to do it and will improve the experience a lot.

Thanks!

**Comment by carlosrovira** [comment]
Hi Josh, great to see you appreciate the value this feature could bring. Don't know how hard this would be to implement.

If you have some idea or plan on how to do this,  maybe, I could take a look and try to help to make this real. I think it could be fun. I'll never do anything for VSCode and maybe finally could not reach to something valid but I could try if you want.

Thanks! :)

**Comment by joshtynjala** [comment]
I don't have an exact plan for this one yet. I think I would either let you specify which MXML namespaces to include or exclude, or I would let you specify which SWCs from the SDK to include or exclude. At the moment, I'm leaning towards SWCs. However, that's also a little tricky because Royale has different SWCs for SWF and JS targets.

I need to think about this one a bit more.

**Comment by carlosrovira** [comment]
Hi Josh,
I think what we need is SWCs. For example, Basic is splitter in more than one SWC, so remove "basic" namespace, will remove all, and we don't want that. Instead, if we don't use, let's say, Network.swc (that is in basic namespace) in our app, we want to remove it from code intelligence, since will be useless bring things from that SWC. We'll want to remove mostly all UI sets not used. And One day I hope we can move TLDs from Basic UI set to other SWC so we can just have the UI set you use (and add as you want incorporate SWCs if needed).

Maybe one thing could be check SWCs listed in pom.xml or ant.xml, or add to ascconfig.json or add to settings.json...

Thanks
