### ISSUE TITLE
Code Action: Generate unimplemented methods (interface)

### ISSUE THREAD

**Issue by Adolio** [BowlerHatLLC/vscode-as3mxml#308]
Hello Josh,

It would be nice to have a code action to generate missing methods when implementing an interface.

Apparently the parser is already aware of the missing methods.

![screen shot 12-07-18 at 10 40 am](https://user-images.githubusercontent.com/1126990/49639974-9b7cd080-fa0c-11e8-817c-dbf216fc8ea8.PNG)

Best,
Aurélien

**Comment by joshtynjala** [comment]
Good suggestion!

**Comment by Adolio** [comment]
Thanks Josh!
