### ISSUE TITLE
Missing js-load-config

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/vscode-as3mxml#313]
There's a separate config option for SWF and JS. Currently the is only `load-config`. `js-load-config` is missing from the asconfig options.

**Comment by joshtynjala** [comment]
Thanks! I'll get it added soon. In the meantime, you can add it to the additionalOptions field.

**Comment by Harbs** [comment]
I tried `additionalOptions`, but I wasn't sure how to specify a relative path using that.

**Comment by joshtynjala** [comment]
This should work:

```
-js-load-config+=my/relative/path.xml
```

You should be able to add *./* at the beginning of the path, if you prefer.

Paths are relative to the folder that contains *asconfig.json*. That's the current working directory that gets set when VSCode executes the compiler.
