### ISSUE TITLE
clean build task not working

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/vscode-as3mxml#314]
When trying to run clean I get the following output:

Failed to clean project because the output path overlaps with the current working directory.
The terminal process terminated with exit code: 1

Below is my asconfig file:

````
{
  "config": "royale",
  "compilerOptions": {
      "debug": false,
      "targets": ["JSRoyale"],
      "source-map": false,
      "js-library-path": [
          "../Spectrum/target"
      ],
      "remove-circulars": true,
      "html-template": "index-template.html",
      "js-compiler-option": [
          "--skip_type_inference"
      ]
  },
  "copySourcePathAssets": true,
  "additionalOptions": "-js-output-optimization=skipAsCoercions  -warn-public-vars=false",
  "files":
  [
      "src/SpectrumBrowser.mxml"
  ]
}
````

**Comment by joshtynjala** [comment]
You know, I don't think I tested the clean task with Royale projects. Without looking at the code, I think I already know how to fix it, though.

Thanks!
