### ISSUE TITLE
Setting to disable real-time problem checking

### ISSUE THREAD

**Issue by matrix3d** [BowlerHatLLC/vscode-as3mxml#316]
How to turn off automatic output problems. Big project this function is too slow, every time you enter a word

![flashmixer](https://user-images.githubusercontent.com/4150631/50882370-876b2b00-141f-11e9-9de3-b19feacec7d3.gif)

**Comment by joshtynjala** [comment]
There is currently no way to turn it off, but I'll try to add a setting in the next update to make it check for errors only when you save a file.
