### ISSUE TITLE
Multiple SWF Compilation

### ISSUE THREAD

**Issue by jcrawford** [BowlerHatLLC/vscode-as3mxml#319]
I could have swore we covered this in the past but when I looked through the comments in my closed tickets I could not find it.  Now that I am able to build again we have several swf's that we need to have compiled. Is there a way to have multiple json files such as asconfig.json where I could specify every swf that we need to have compiled?

We currently have 5 that are compiled separately and I only have 1 setup in VSCode for compilation.

**Comment by joshtynjala** [comment]
I think you are looking for this comment:

https://github.com/BowlerHatLLC/vscode-as3mxml/issues/286#issuecomment-428229657

**Comment by jcrawford** [comment]
Perfect Thank you, not sure how I missed that one but thought we had discussed it in the past.
