### ISSUE TITLE
Error: only one source is allowed in the filespec

### ISSUE THREAD

**Issue by lonelyma1021** [BowlerHatLLC/vscode-as3mxml#323]
I am trying to import an existing FlashBuilder Project into  VS Code. I follow the Wiki generated asconfig.json file. It work fine and I can run my App. But when I add other modules to "files" element, I get "only one source is allowed in the file spec" error. Here is my config:

```
{
  "config":"air:,
  "compilerOptions":{
    "output":"bin/MyApp.swf",
    "library-path":[
      "libs"
    ]
  },
  "application":"src/MyApp-app.xml",
  "files":[
    "scr/com/toshiba/todolist/Todos.mxml",
    "src/MyApp.mxml"
  ],
  "copySourcePathAssets":true
}
```

Could you tell me how to config mutimodule project, please~

**Comment by joshtynjala** [comment]
Modules in Flex projects need to be complied separately. Each module will need its own asconfig file.

Your main app should use asconfig.json, but you might add asconfig.todos.json to configure your Todos module. VSCode will provide additional build tasks for each asconfig file that you create.

**Comment by joshtynjala** [comment]
By the way, you have a typo.

> scr/com/toshiba/todolist/Todos.mxml

That should be src, I think.
