### ISSUE TITLE
preLaunchTask must be renamed if simple project is opened within workspace, or if it already is but other root folders are removed from workspace

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-as3mxml#325]
For example, if simple project Project1 is used (one folder opened), this works ok:
`"preLaunchTask": "ActionScript: compile debug - asconfig.json"`

but if other folder Project2 is added in workspace,  `preLaunchTask` in _launch.json_ of the Project1 must be renamed to:
`"preLaunchTask": "ActionScript: compile debug - Project1/asconfig.json"`

Also, if all but one folder are removed from workspace and only Project1 is left, and it has:
`"preLaunchTask": "ActionScript: compile debug - Project1/asconfig.json"`

error will popup:
![image](https://user-images.githubusercontent.com/1468887/53058894-2e2df700-34b5-11e9-9b47-6c4fa3bba066.png)

and to run, it must be renamed to:
`"preLaunchTask": "ActionScript: compile debug - asconfig.json"`

So to prevent this need for renaming `preLaunchTask`, when one project's folder is opened alone or together with other projects folders in workspace, it would be great if the extension could always detect `preLaunchTask` with included name of the root folder before asconfig.json in the task name.

As I see it, the change would be just to allow simple projects (one folder opened) to have:
`"preLaunchTask": "ActionScript: compile debug - Project1/asconfig.json"`
as `preLaunchTask` task name.

**Comment by joshtynjala** [comment]
I thought that I had I copied how TypeScript handles the tasks in multi-root workspace, but it looks like TS gives all built-in tasks in a multi-root workspace the same name: *tsc: build - tsconfig.json*.

However, even with the difference, TypeScript has basically the same issue. The built-in task names from a single workspace can't be used with preLaunchTask after adding a second folder (or after removing all folders but one).

The correct solution is to give your task a `label`. You can reference a task's label in the `preLaunchTask` instead of its default name. As a bonus, the label can be anything that you'd like, so you can choose something shorter, if you prefer.

**Comment by neminovno** [comment]
Oh, there is `label` instead of deprecated `identifier` https://github.com/BowlerHatLLC/vscode-as3mxml/issues/303

So to have [ActionScript: compile debug - asconfig.json](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Tasks-for-ActionScript-and-MXML-in-Visual-Studio-Code#actionscript-compile-debug---asconfigjson) task as `preLaunchTask`, having this in _tasks.json_:
```
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "Compile debug",
            "type": "actionscript",
            "debug": true
        }
    ]
}
```

and this in _launch.json_:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "swf",
            "request": "launch",
            "name": "Launch SWF",
            "preLaunchTask": "Compile debug"
        },
        {
            "type": "swf",
            "request": "attach",
            "name": "Attach SWF",
        }
    ]
}
```

solves the issue. Thank you.

**Comment by joshtynjala** [comment]
Yeah, I'm not sure why they removed identifier and then immediately added label, since they seem to serve the same purpose. Perhaps I missed some subtle difference that makes the new way better.
