### ISSUE TITLE
Wiki: small issue

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-as3mxml#327]
In [Debug an Adobe AIR desktop application with Visual Studio Code](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Debug-an-Adobe-AIR-desktop-application-with-Visual-Studio-Code#native-extensions) it says:

> If your Adobe AIR mobile application

but should be:

> If your Adobe AIR desktop application

**Comment by joshtynjala** [comment]
Thanks!
