### ISSUE TITLE
Unexpected "test" appears in Terminal output while packaging mobile

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-as3mxml#328]
Example (before "NOTE"):
> Adobe AIR code signing password:
> testNOTE: The application has been packaged with a captive runtime.
> 
> Terminal will be reused by tasks, press any key to close it.

**Comment by joshtynjala** [comment]
I think this is fixed already because I don't see the string "test" anywhere in my code.

**Comment by neminovno** [comment]
Sorry, found it mentioned before, here https://github.com/BowlerHatLLC/vscode-as3mxml/issues/230
It is from AIR 19 adt:
![image](https://user-images.githubusercontent.com/1468887/53108660-b228c300-3537-11e9-8691-422bf4aae9be.png)
