### ISSUE TITLE
Quick Compile & Debug Files to Compile At First Run

### ISSUE THREAD

**Issue by angelhdz** [BowlerHatLLC/vscode-as3mxml#329]
### DEVELOPMENT ENVIRONMENT DETAILS
VSCode Version:  1.31.1 (User Setup)
Nextgenactionscript Version: 0.17.2
OS: Windows 10 PRO 64bit
Apache Royale Version: 0.9.4 (JS & SWF)

Hello again. I think this is a **bug**. As you (Josh) know I'm working with Apache Royale.

### ISSUE DESCRIPTION
I have to hit _CNTRL + ENTER_ or select  _Command Palette > Actionscript: Quick & Compile_ **TWICE** in order to get it to compile and reflect changes in code or in project files.

![2019-02-22_08-16-44](https://user-images.githubusercontent.com/10191085/53242279-b27da700-367a-11e9-8e3c-59c945e00061.gif)

### EXPECTED OUTCOME
Hitting _CNTRL + ENTER_ or selecting  _Command Palette > Actionscript: Quick & Compile_ **ONLY ONCE**, will compile the project and then debug it and reflect the changes in the project.

**Comment by joshtynjala** [comment]
I wonder if this is related to some caching that the Royale compiler started doing in 0.9.4. For performance reasons, it stores certains objects in a cache. That works fine when compiling from the command line, but if the compiler is reused beyond a single session, the cache can get stale. I found that this broke code intelligence in VSCode under some circumstances. When using Quick Compile & Debug, the compiler is reused if the configuration has not changed because it can improve subsequent compile times. Unfortunately, this may be another situation where the cache is causing old data to be used.

I don't think that I can fix Quick Compile & Debug until Royale 0.9.6 is released.

To get the equivalent behavior, you should define a preLaunchTask for your debug configuration. Then, just start the debugger normally instead of using Ctrl+Enter. I think the keyboard shortcut is F5, but I may be wrong.

**Comment by angelhdz** [comment]
Thank you. That makes sense.

### WORKAROUND

Setting **preLaunchTask** in asconfig.json to **"build"**, and in the **task.json** setting the label attribute to **"build"**, works as a workaround, so hitting **F5** will compile and debug. We can edit the keyboard shortcut of **F5** to point to **CTRL + ENTER** if we wish.

### FINAL WORDS

However, I'll wait for the next version of Royale to get this fixed, so I can debug with F5 (faster) and wen I make some changes, then i hit CTRL + ENTER to compile & debug (slower).

Thank you very much Josh! Blessings.  😄

**Comment by angelhdz** [comment]
### UPDATE

It's happening now on an AIR Workspace, with the **AIR 31.0.0.96 SDK**.

I hit **CTRL + ENTER**, don't see my recent changes in the code. Hit it again, then it compiles the changes.

**Comment by joshtynjala** [comment]
That's very strange! I've been using Quick Compile & Debug with all of my AIR projects since I first introduced this feature almost a year ago. I have never encountered this issue.

**Comment by angelhdz** [comment]
![2019-02-25_19-18-10](https://user-images.githubusercontent.com/10191085/53377438-65c6f400-3938-11e9-829e-08330923b710.gif)

**Comment by joshtynjala** [comment]
@angelhdz In the GIF, I notice that your *Main.as* file still displays the modified dot next to its name after the project starts compiling. You modified the text, but you seem to have forgotten to save the file.

**Comment by joshtynjala** [comment]
It looks like VSCode automatically saves all files before running any task, so I guess it would make sense to do the same for Quick Compile & Debug too.

**Comment by angelhdz** [comment]
I don't know if I'm just assuming that Quick Compile & Debug of your extension will save the files automatically the same way I'm a used to in Flash Develop and the same way the Pyton extensions I use save all the files before interpreting/debugging, but, I never save the files. 

First time I hit CTRL + ENTER, there's no update. Second time i hit CTRL + ENTER, then there is update. That means, the second time I call the command, it also saves the files.

Why not the first time as well?

I'm new to this extension so I'm just trying to understand how it works and it's limitations.

Thank you for having patience. 

Best regards!

**Comment by joshtynjala** [comment]
> First time I hit CTRL + ENTER, there's no update. Second time i hit CTRL + ENTER, then there is update. That means, the second time I call the command, it also saves the files.

Not exactly. When I was watching the GIF, it looked to me like VSCode also automatically saves all files when the debugger starts. So, your file doesn't get saved before the first compile, but then VSCode saves it when the debugger starts the first time. By the time you compile you ask it to compile a second time, the fact that it was saved earlier means that your changes are finally reflected.

**Comment by joshtynjala** [comment]
In the next update, Quick Compile & Debug will save all files automatically before running the compiler.

**Comment by angelhdz** [comment]
Now that makes sense. I am also new to VSCode so I'm slowly trying to understand how it works. It took me a while to understand the asconfig.json, tasks.json, launch.json, Run Build Task, etc.

So, the files don't get saved when compiling. They get saved when debugging (before or after).

So I wonder... is possible to modify the extension to make VSCode save the files when compiling so you can improve in a future release?

In the meantime, I will stick to the **preLaunchTask** workaround. It seems to do the job. I can do any modifications in any file, an when hitting _CTRL + ENTER_ it will save the files, then compile, then debug.

Note: Ha ha ha, while I was writing this response, I noticed your reply about  Quick Compile & Debug will save the files when compiling. Great!

I will donate again when I get paid in my landscaping job. Also will donate to Carlos from Royale.

Thank you for everything!

**Comment by joshtynjala** [comment]
> I will donate again

Thank you, @angelhdz!
