### ISSUE TITLE
Completion should add () after method and put cursor in between parentheses

### ISSUE THREAD

**Issue by GotJimmy** [BowlerHatLLC/vscode-as3mxml#33]
Would be nice to get   ()   after auto-completing a function call and put the cursor within  ()  if the function has parameters, or after  ()  if no params.

**Comment by joshtynjala** [comment]
I recently discovered that I could use snippets to add parentheses and place the cursor between them. Unfortunately, when I do this, signature help doesn't automatically open to show the list of function parameters. Signature help only opens if you type `(` manually.

With that in mind, until VSCode provides a good way to add parentheses, move the cursor, and open signature help (all at the same time), it's better to leave this behavior as-is.
