### ISSUE TITLE
Building Without Launching Browser

### ISSUE THREAD

**Issue by jcrawford** [BowlerHatLLC/vscode-as3mxml#333]
Is there a way to build a release build without actually launching it in the browser?

**Comment by joshtynjala** [comment]
Run the "ActionScript: compile release" task.

**Comment by jcrawford** [comment]
I do not have that option...
<img width="623" alt="screen shot 2019-02-28 at 11 50 06 am" src="https://user-images.githubusercontent.com/875341/53583177-0858c000-3b4f-11e9-85de-74bacf297902.png">

**Comment by joshtynjala** [comment]
Go to the **Terminal** menu and choose **Run Task...**

Or, if you prefer to use the command palette, run the **Tasks: Run Task...** command.

**Comment by jcrawford** [comment]
It is not listed there either, do I need to do something special to configure this?

<img width="609" alt="screen shot 2019-02-28 at 12 24 48 pm" src="https://user-images.githubusercontent.com/875341/53585439-ef9ed900-3b53-11e9-8f7d-e4442181444f.png">

**Comment by joshtynjala** [comment]
No... The "compile debug", "compile release", and "clean" tasks are always available. Only the Adobe AIR tasks require special configuration.

I can reproduce the issue where some are missing if I omit the : character. Add that in there, and you should see all of the tasks. I guess VSCode has a bug with the filtering.

**Comment by jcrawford** [comment]
nothing there on my side which is odd.

<img width="608" alt="screen shot 2019-02-28 at 12 47 56 pm" src="https://user-images.githubusercontent.com/875341/53586885-1f9bab80-3b57-11e9-8f87-7035af825c3d.png">

**Comment by jcrawford** [comment]
I have tried uninstalling and re-installing the plugin as well.  I am currently using the latest version of VSCode (not insiders)

**Comment by joshtynjala** [comment]
Try just scrolling through the list instead of searching.

**Comment by jcrawford** [comment]
This is all that is shown when I click Terminal > Run Task

<img width="615" alt="screen shot 2019-02-28 at 12 51 57 pm" src="https://user-images.githubusercontent.com/875341/53587167-ac466980-3b57-11e9-9dda-ab9cf128a852.png">

**Comment by joshtynjala** [comment]
"Build Manufacturer", "Build Distributor", etc. tasks are your compile release tasks. The label that you gave them in tasks.json is displayed instead of the original name.

**Comment by jcrawford** [comment]
Ahh ok thank you I will try those.
