### ISSUE TITLE
[Question] Multi-root Workspace

### ISSUE THREAD

**Issue by angelhdz** [BowlerHatLLC/vscode-as3mxml#335]
Having to add each new project manually to the workspace is not practical, so I put all my projects inside a root folder and added that folder instead, so every time I add a new folder inside the root folder it will appear in the workspace automatically (or by refreshing it).

How to configure the workspace so it asks me what folder to debug?
I can **Run Build Task** and it asks me what folder to build and it builds successfully, but not with debugging.

**Start Debugging** will complain the folder doesn't have a _asconfig.json_. 

Thank you.

**Comment by joshtynjala** [comment]
> Having to add each new project manually to the workspace is not practical

Why not? You add it once, save the workspace, and it will be restored every time you reopen the same workspace.

**Comment by neminovno** [comment]
@joshtynjala what would be answer here:

> 
> How to configure the workspace so it asks me what folder to debug?
> I can Run Build Task and it asks me what folder to build and it builds successfully, but not with debugging.
> 
> Start Debugging will complain the folder doesn't have a asconfig.json.

**Comment by joshtynjala** [comment]
> Each root folder in workspace must have launch.json configured?

It can start debugging without launch.json, but it's possible that only works when there's only one workspace root. When you have multiple roots, it's best to set up launch configurations for each one.

**Comment by wmfelipe** [comment]
> It can start debugging without launch.json, but it's possible that only works when there's only one workspace root. When you have multiple roots, it's best to set up launch configurations for each one.

Hi @joshtynjala , does you mean I should have a launch.json file even for my SWC component folder in workspace?
Thanks.

**Comment by joshtynjala** [comment]
@wmfelipe You can't launch _.swc_ library files, so no, you don't need _launch.json_ files for those. It's only for application projects that you want to run/debug.
