### ISSUE TITLE
Unable to load a certificate

### ISSUE THREAD

**Issue by noenoe** [BowlerHatLLC/vscode-as3mxml#337]
I set the signing options and build a mobile project.
but I can't build the project because of the error below.

> unable to load a certificate in this file

Maybe, this certificate made by 1024 bit. (the project is too old!)
So I created a 2048 bit certificate and tried it, It can build.

Is there a way to use the 1024 bit certificate as it is?

**Comment by neminovno** [comment]
As I recall, it depends on Java version. If you can use older Java version, you could use 1024 bit cert.

**Comment by noenoe** [comment]
Thanks your advice. I already tryed to use lower version of java, but it’s same result. (I use 1.6 for mac os and 1.8 for this extention of vs code)

need more older version?

**Comment by neminovno** [comment]
Check [Why am I getting a “unable to load a certificate in this file” error? Adobe Air captive runtime bundle](https://stackoverflow.com/questions/48450439/why-am-i-getting-a-unable-to-load-a-certificate-in-this-file-error-adobe-air/49060170#49060170)
Older than 1.8.0_121, like 8u112, should handle 1024 bit signed certs.

**Comment by joshtynjala** [comment]
You are welcome to continue the discussion, but I am closing this issue since it's unrelated to VSCode.
