### ISSUE TITLE
v18.0 branch not working in Tour De Jewel project

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-as3mxml#338]
Hi Josh,

I just compiled locally v0.18 to try it and while in my real Apache Royale project it works ok, in Tour de Jewel is not working. Maybe some update to "asconfig.json" is needed, but I'm trying to figure what could be without luck. Hope you could give me some hint to try

Thanks in advance

**Comment by joshtynjala** [comment]
Please ensure that you have my latest commit from about an hour ago. It fixes a serious freeze/hang bug.

For reference, I am able to open TourDeJewel on my machine, and code intelligence is working correctly. No configuration changes required.

**Comment by carlosrovira** [comment]
Hi Josh,

today I check that I had the latest code (I was up to date yesterday). I rebuild again and updated VSCode. Reinitialize and the problem persist. Can you try again TDJ with latest updates?
For now I switched back to 17.2 until we see what could be the problem.
If there's something I can do to find the problem let me know
Thanks

**Comment by joshtynjala** [comment]
I tested the TourDeJewel project on both Windows and macOS with the latest versions of everything in Royale. Code intelligence is working correctly for me on both computers.

Is there any kind of error message that you can share? "Not working" is very vague and could mean anything. An error message from VSCode or any kind of compiler error/warning would probably provide some clues.

**Comment by carlosrovira** [comment]
Hi Josh,
the problem is that in status bar appears a message "Iniitalizaing Actionscript & MXML..." and a moving icon of two circular arrows moving, and while in my real project this happens few seconds and then all works, in TDJ this message remains and never disappear, and extension seems blocked.
Hope this helps to reach to the problem
thanks!

**Comment by joshtynjala** [comment]
If you open up the **Output** view and select **ActionScript & MXML Language Server**, do you see any output there?

If you open the **Command Palette** and run the **Developer: Toggle Developer Tools** command, do you see any output there?

**Comment by carlosrovira** [comment]
HI Josh, 
I think I got it: The problem is that I'm using a workspace not just TDJ alone. If I open just TDJ it works, but open a workspace with:
-Jewel
-JewelTheme
-TourDeJewel
-Core
-Basic
-BE0004_Adding_an_item_to_a_Jewel_List

Is where I have the problem. Removing this 3 solves the problem:

-Core
-Basic
-BE0004_Adding_an_item_to_a_Jewel_List

**Comment by joshtynjala** [comment]
Thanks for the info! I can now reproduce this issue.

**Comment by joshtynjala** [comment]
Hey Carlos, this issue should now be resolved. I've been working on fixing some multi-threading issues recently, and I ended up introducing a new one!

Sorry for the trouble!

**Comment by carlosrovira** [comment]
Many thanks Josh for the quick fix! :)
