### ISSUE TITLE
Flash Builder workspace linked resources is not imported

### ISSUE THREAD

**Issue by gdeverlant** [BowlerHatLLC/vscode-as3mxml#339]
```
"compilerOptions": {
		"output": "bin-debug/Program1.swf",
		"source-path": [
			"src"
		],
		"external-library-path": [
			"${AS3}/ane/com.juice.Termo/ext/ane/com.juice.Termo-x86-debug.ane",
			"${AS3}/ane/com.juice.rtmfp/ext/com.juice.rtmfp-x86-debug.ane"
		]
	}
```

![image](https://user-images.githubusercontent.com/26530975/54471018-3f1b1100-47b2-11e9-8684-a4432e067efd.png)

![image](https://user-images.githubusercontent.com/26530975/54471025-738ecd00-47b2-11e9-914a-7fb69c23b8ee.png)

**Comment by joshtynjala** [comment]
Thanks! That's not a feature I've ever used. I'll need to look into what it takes to read those values from the Eclipse workspace.

**Comment by gdeverlant** [comment]
For the time being is there a way to declare the ${AS3} statically inside of the asconfig.json file ?

**Comment by gdeverlant** [comment]
There is another bug I found out which is on this screenshot:

![image](https://user-images.githubusercontent.com/26530975/54637235-732f5400-4a88-11e9-9569-f02dcebd7867.png)

It seems that the editor doesn't like **;** in my source code.

**Comment by gdeverlant** [comment]
> Thanks! That's not a feature I've ever used. I'll need to look into what it takes to read those values from the Eclipse workspace.

Do you think that we could have a global variable place in VS Code to set those path variables once like in FlashBuilder and reuse them as placeholder variables?

**Comment by joshtynjala** [comment]
As I understand it, on the command line, the compiler allows you to specify tokens like `${AS3}` using this format:

```
+AS3=path/to/folder
```

You can use the `additionalOptions` field in *asconfig.json* to specify options that aren't defined in the `compilerOptions` field.

With that in mind, I think that this will work for you:

```
{
	"compilerOptions: {
		"external-library-path": [
			"${AS3}/ane/com.juice.Termo/ext/ane/com.juice.Termo-x86-debug.ane",
			"${AS3}/ane/com.juice.rtmfp/ext/com.juice.rtmfp-x86-debug.ane"
		]
	},
	"additionalOptions": "+AS3=G:/programming/AS3"
}
```

**Comment by joshtynjala** [comment]
> It seems that the editor doesn't like ; in my source code.

Until your *asconfig.json* file isn't valid yet, this error isn't really relevant. You may get more detailed errors once you fix your project configuration.

**Comment by gdeverlant** [comment]
> As I understand it, on the command line, the compiler allows you to specify tokens like `${AS3}` using this format:
> 
> ```
> +AS3=path/to/folder
> ```
> You can use the `additionalOptions` field in _asconfig.json_ to specify options that aren't defined in the `compilerOptions` field.
> 
> With that in mind, I think that this will work for you:
> 
> ```
> {
> 	"compilerOptions: {
> 		"external-library-path": [
> 			"${AS3}/ane/com.juice.Termo/ext/ane/com.juice.Termo-x86-debug.ane",
> 			"${AS3}/ane/com.juice.rtmfp/ext/com.juice.rtmfp-x86-debug.ane"
> 		]
> 	},
> 	"additionalOptions": "+AS3=G:/programming/AS3"
> }
> ```

You mean something like : 

````
{
	"compilerOptions": {
		"output": "bin-debug/Multiverses.swf",
		"source-path": [
			"src"
		],
		"external-library-path": [
			"${AS3}/ane/de.gaia.Fractal/ext/de.gaia.Fractal-x86-debug.ane",
			"${AS3}/ane/de.gaia.rtmfp/ext/de.gaia.rtmfp-x86-debug.ane"
		]
	},
	"files": [
		"src/Multiverses.as"
	],
	"application": "src/Multiverses-app.xml",
	"copySourcePathAssets": true,
	"additionalOptions": "-keep-as3-metadata+=Metadatas :+AS3=G/programming/as3",
	"airOptions": {
		"output": "Multiverses.air",
		"signingOptions": {
			"keystore": "G:/programming/releases/test.p12",
			"storetype": "pkcs12"
		},
		"extdir": [
			"${AS3}/ane/de.gaia.Fractal/ext/de.gaia.Fractal-x86-debug.ane",
			"${AS3}/ane/de.gaia.rtmfp/ext/de.gaia.rtmfp-x86-debug.ane"
		]
	},
	"config": "air"
}
````

**Comment by joshtynjala** [comment]
Unfortunately, compiler tokens will only work when you reference them inside `compilerOptions` or `additionalOptions`. Compiler tokens won't work in the `airOptions` section because AIR apps are packaged with a different tool.

**Comment by gdeverlant** [comment]
Tried again with : 
```
{
	"compilerOptions": {
		"output": "bin-debug/Multiverses.swf",
		"source-path": [
			"src"
		],
		"external-library-path": [
			"G:/programming/as3/ane/de.gaia.Fractal/ext/de.gaia.Fractal-x86-debug.ane",
			"G:/programming/as3/ane/de.gaia.rtmfp/ext/de.gaia.rtmfp-x86-debug.ane"
		]
	},
	"files": [
		"src/Multiverses.as"
	],
	"application": "src/Multiverses-app.xml",
	"copySourcePathAssets": true,
	"additionalOptions": "-keep-as3-metadata+=Metadatas",
	"airOptions": {
		"output": "Multiverses.air",
		"signingOptions": {
			"keystore": "G:/programming/releases/test.p12",
			"storetype": "pkcs12"
		},
		"extdir": [
			"G:/programming/as3/ane/de.gaia.Fractal/ext/de.gaia.Fractal-x86-debug.ane",
			"G:/programming/as3/ane/de.gaia.rtmfp/ext/de.gaia.rtmfp-x86-debug.ane"
		]
	},
	"config": "air"
}
```

![image](https://user-images.githubusercontent.com/26530975/54641897-8e539100-4a93-11e9-8cff-c6f7ba94f3a0.png)

**Comment by joshtynjala** [comment]
Does *bin-debug* contain a folder named *.as3mxml-unpackaged-anes*, and have your extensions been copied into it?

**Comment by gdeverlant** [comment]
> Does _bin-debug_ contain a folder named _.as3mxml-unpackaged-anes_, and have your extensions been copied into it?

The answer is : 

![image](https://user-images.githubusercontent.com/26530975/54642325-95c76a00-4a94-11e9-9a57-9067271b92d2.png)

**Comment by joshtynjala** [comment]
Are you building your project with the built-in **ActionScript: compile debug - asconfig.json** task?

**Comment by gdeverlant** [comment]
I have two files and when I do **Ctrl+Shift+B** : 

```
> Executing task: C:\Program Files\ojdkbuild\java-1.8.0-openjdk-1.8.0.181-1\bin\java.exe -jar c:\Users\ar.rahman\.vscode\extensions\bowlerhatllc.vscode-nextgenas-0.18.0\bin\asconfigc.jar --sdk c:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK --debug=true --project g:\programming\as3\multiverses\Multiverses\asconfig.json --unpackage-anes=true <

Loading configuration: c:\Program Files\Adobe\Adobe Flash Builder 4.7 (64 Bit)\eclipse\plugins\com.adobe.flash.compiler_4.7.0.349722\AIRSDK\frameworks\air-config.xml

1460 bytes written to G:\programming\as3\multiverses\Multiverses\bin-debug\Multiverses.swf in 1.059 seconds

Terminal will be reused by tasks, press any key to close it.
```

**Comment by joshtynjala** [comment]
Great news!

**Comment by gdeverlant** [comment]
Thank you a lot for your support. What do you think about the FlashBuilder Linked Resource paths and VS Code? Is it worth it?

**Comment by joshtynjala** [comment]
I'll definitely look into improving the Flash Builder project import so that no linked resources are unresolved in *asconfig.json*. This will probably involve replacing the token with the full path before writing to *asconfig.json*. I don't want to support a full implementation of linked resources, unless VSCode builds it in natively.

**Comment by gdeverlant** [comment]
> I'll definitely look into improving the Flash Builder project import so that no linked resources are unresolved in _asconfig.json_. This will probably involve replacing the token with the full path before writing to _asconfig.json_. I don't want to support a full implementation of linked resources, unless VSCode builds it in natively.

I get it, it makes sense. I was wondering if in the future the Project Explorer/Outliner/Breakpoints/Expressions will be added in the UI? I'm talking about this screenshot 👍 
![image](https://user-images.githubusercontent.com/26530975/54643618-a7f6d780-4a97-11e9-961a-e6f741a75222.png)

**Comment by joshtynjala** [comment]
Switch to the VSCode's "Debug" section for variables, watch expresssions, and breakpoints.

VSCode has an "Outline" view too. It might not be open by default, but you can find it in the "View" menu.

**Comment by gdeverlant** [comment]
I see it is pretty condensed is there a way to make these sections into Tabs like in FB because it is not practical to have them stacked on top of each other.

![image](https://user-images.githubusercontent.com/26530975/54709883-b3550c00-4b46-11e9-8562-0d246609e4a3.png)

**Comment by joshtynjala** [comment]
No, I'm not aware of a way to make them into tabs in VSCode.

**Comment by gdeverlant** [comment]
How about wait and see for an answer?
