### ISSUE TITLE
[Bug Or Unknown Config] NativeWindow Size Wrong

### ISSUE THREAD

**Issue by angelhdz** [BowlerHatLLC/vscode-as3mxml#340]
Hello!

### Issue Description
Wrong native window size with **ActionScript & MXML** extension in VSCode.

Tested in **FlashDevelop** (right AIR window in the image below) and everything works fine there.

### Development Environment

1. Same descriptor file
2. Same *.as files
3. Same SDK (Feathers 4.0)
4. AIR Mobile Project
5. `<supportedProfiles>mobileDevice</supportedProfiles> (application.xml)`
6. `"profile": "mobileDevice" (launch.json)`

### Config Files

launch.json
```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "swf",
      "request": "launch",
      "name": "Launch AIR mobileDevice",
      "profile": "mobileDevice",
      "internalConsoleOptions": "openOnSessionStart",
      "preLaunchTask": "build"
    }
  ]
}
```
tasks.json

```
  {
    // See https://go.microsoft.com/fwlink/?LinkId=733558
    // for the documentation about the tasks.json format
    "version": "2.0.0",
    "tasks": [
      {
        "label": "build",
        "type": "actionscript",
        "debug": true,
        "problemMatcher": [
          "$nextgenas_nomatch"
        ],
        "group": {
          "kind": "build",
          "isDefault": true
        }
      }
    ]
  }
  
```
asconfig.json
```
{
    "config": "airmobile",
    "compilerOptions": {
        "output": "bin/Mensajero.swf",
        "library-path":  [
            "src",
            "C:\\Users\\Repair\\Documents\\Programming\\AS3\\packages\\fl",
            "C:\\Users\\Repair\\Documents\\Programming\\AS3\\packages\\Feathers",
            "C:\\Users\\Repair\\Documents\\Programming\\AS3\\themes\\Feathers\\MaterialCyanLimeMobileTheme"

        ],
        "source-path": [
            "src"
        ]
    },
    "application": "application.xml",
    "files":
    [
        "src/Main.as",        
    ]  
}
```

     
  

### Attempts to Solve the Issue

Tried setting the **width** and **height** manually in the descriptor file. No success.
Tried setting **stage.stageWidth** and **stage.stageHeight** manually. No success.

### Screen Capture
![asd](https://user-images.githubusercontent.com/10191085/54574891-719e5700-49c8-11e9-9838-97facb4c7b18.jpg)

**Comment by joshtynjala** [comment]
You are using the AIR mobile simulator. With the simulator, you cannot control window size from the app descriptor file or from AS3 code. Consider that you wouldn't be able to do that in a real device either. Instead, you tell the simulator which type of device to simulate when you launch it.

Check out the available options in launch.json:

https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/launch.json-fields-for-SWF-debugging

In particular, screensize and screenDPI.

Also, check out this page, which shows the launch.json settings for simulating several common mobile devices:

https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/launch.json-configuration-settings-for-simulating-common-mobile-devices-in-Adobe-AIR

**Comment by angelhdz** [comment]
Solved### 

Yup. I knew it was some configuration missing. In FlashDevelop everything is already set up when making a new project. And if I wanted extra configuration, I would edit the *.bat files.

Thank you!

![image](https://user-images.githubusercontent.com/10191085/54578187-263e7580-49d5-11e9-9eb0-613357c65578.png)
