### ISSUE TITLE
Screencast of Josh when he is porting/coding features from FlashBuilder to VSCode

### ISSUE THREAD

**Issue by gdeverlant** [BowlerHatLLC/vscode-as3mxml#342]
Hi again Josh I would like to help somehow with some features like the properties panel for projects in FB but I have no idea what is your workflow and how you are working.

Maybe if you could just record your screen while you work on the Actionscript & MXML extension for VSCode. I would like to see how you do from the old Java environment in code towards VSCode to learn myself and maybe contribute.

No need to make voice over or any professional montage just record each feature you do so that we can follow and learn the flow.

This would be a huge boost for other people who want to help.

Best regards

**Comment by joshtynjala** [comment]
I'm afraid that this is unlikely to happen.
