### ISSUE TITLE
Support dollar signs in file/class names

### ISSUE THREAD

**Issue by volfpeter** [BowlerHatLLC/vscode-as3mxml#345]
First of all, thanks for the effort you've put into this VSCode extension! We would like to give it a try at our company, but unfortunately we ran into some issues. This is one of them.

Typical use-case: ActionScript-style resource bundle names like `RB$locale_code$ResourceBundleName`.

Such files currently produce these kinds of errors:
`No externally-visible definition with the name 'locale_code.RB$locale_code$BundleName' was found.`
`An externally-visible definition with the name 'RB$locale_code$BundleName' was unexpectedly found.`

**Comment by joshtynjala** [comment]
Did you add the correct folder for your locale to the `source-path`?

**Comment by volfpeter** [comment]
Yes. The file in question is in a separate AS3 library whose code i'm trying to include in the application using the `source-path` and `include-sources` lists to make features like Goto definition work in VSCode.
I've just tried compiling the library in itself and i got no errors... I guess with this config i'm trying to make the extension do something that it is not supposed to do.

**Comment by joshtynjala** [comment]
Can you share with me a stripped down version of the code that VSCode doesn't like? Basically, just the package and class declaration without any member variables or methods should be enough.

**Comment by volfpeter** [comment]
This is one of the files i had a problem with.
```
package {
import core.resources.ResourceBundle;
[ExcludeClass]
public class RB$en_US$CoreActions extends ResourceBundle {
    public function RB$en_US$CoreActions() {super("en_US", "CoreActions");}
    override protected function getContent():Object {
        return {
            "action.label.activateApplication": "Show {0}",
            ...
        };
    }   
}}```

**Comment by joshtynjala** [comment]
Thanks! I'll take a look and see what I can do.

**Comment by volfpeter** [comment]
Thanks a lot! Don't go too deep into debugging this issue just: this is the first time we try to get the extension working with our codebase (more than 20 libraries with various dependencies between them), and as this discussion goes on i feel more and more that we have a config problem.
Could you maybe give me a tip on how to get for example the Goto definition feature working between libraries that are all added to the workspace?

**Comment by joshtynjala** [comment]
If something is on the `source-path`, `library-path`, or `external-library-path` (specified in `compilerOptions`) for your project, go to definition should be able to find it.

In the case of `library-path` or `external-library-path`, it will use the original source file, if the path exists on your system. Otherwise, it will generate some read-only code from the compiler's internal representation of the file.

**Comment by volfpeter** [comment]
I always get the generated code, i guess because the source code of dependencies is not referenced in asconfig.json, only the .swc files (my base config files were generated using the Flash Builder project import feature). I tried changing `include-sources` and `external-library-path` to fix this, but i must have messed it up somehow and that's how i ended up with the error i opened the issue for.
I'll try to redo the whole next week. Thanks for the great help!

**Comment by volfpeter** [comment]
I've tried to fix my configuration but i still get some compilation errors. I'm pretty sure it's not the extension's fault though, so i think the issue can be closed.
