### ISSUE TITLE
ActionScript source path view: should be visible always (or only if asconfig has source-path has more than "src" listed)

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-as3mxml#351]
If a file from src dir is opened, panel is not visible. If a file from other source-path dir is opened, panel becomes visible:
![image](https://user-images.githubusercontent.com/1468887/56515774-ff75e080-6538-11e9-9442-46459b1fe21d.png)

Why is "ACTIONSCRIPT SOURCE PATH" panel visible only if active file in editor is from included source path? Should it not be always visible, at least to indicate user that the opened project has extra source-path included?

**Comment by joshtynjala** [comment]
It is visible when any *.as* or *.mxml* file is open. It is hidden when other file formats are open. The value of the `source-path` compiler option does not affect the behavior.

**Comment by joshtynjala** [comment]
It used to be open at all times, but then it would activate the extension in all workspaces. Even workspaces for other languages.

I noticed that TypeScript hides some UI when other types of files are open, so I decided that it would make sense to do the same for this.
