### ISSUE TITLE
Warning in Problems view points to directory, can't find source of warning.

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-as3mxml#354]
Got 4 warnings in Problems view, grouped under root dir name:

> project-root-dir C:\dev\project-root-dir
>> Duplicate declaration of SkinState 'normal' [1,1]
>> Duplicate declaration of SkinState 'disabled' [1,1]
>> Duplicate declaration of SkinState 'normal' [1,1]
>> Duplicate declaration of SkinState 'disabled' [1,1]

If clicked on, error shows "Unable to open 'project-root-dir': File is a directory."
How to find source of the warnings?
Project is using other source paths than "src". Could the source of warnings be in one of included source path?

**Comment by joshtynjala** [comment]
That happens when the compiler doesn't provide me with a file path. It needs to be fixed in the compiler.

**Comment by joshtynjala** [comment]
This issue will be fixed when a release of Apache Royale contains commit apache/royale-compiler@a47853b5b51c83bbcd0e57860896017bd6e1e503.

It will probably be the release *after* Royale 0.9.6, unless the upcoming 0.9.6 release candidate has issues.
