### ISSUE TITLE
Could not locate valid Java executable. 

### ISSUE THREAD

**Issue by velara3** [BowlerHatLLC/vscode-as3mxml#355]
Working on getting started and I received a message from VSC that I needed Java. 

So I installed it from here first and restarted
https://www.java.com/en/download/mac_download.jsp

and I received another message that it was still not installed so I installed a previous version from here
https://support.apple.com/kb/DL1572?locale=en_US

I'm still getting this message when I start VSC:

>Could not locate valid Java executable. To configure Java manually, use the as3mxml.java.path setting.

**Comment by joshtynjala** [comment]
Java 8 is the minimum version required. With that in mind, your second Apple link that installs Java 6 definitely will not work.

Open up Terminal and try running this command:

```sh
java -version
```

What happens?

**Comment by velara3** [comment]
It returns:
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-468)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-468, mixed mode)

So should I go to the first link (version 8) and reinstall?

**Comment by joshtynjala** [comment]
It should be possible for multiple versions of Java to be installed side by side. I'm not on Mac these days, but I seem to recall that there's a way to tell your system to use 1.8 or newer by default, even if an older version is also installed.

If you can't figure that out, then there are a couple of different ways to tell VSCode which version of Java to use.

1) VSCode checks the PATH and `JAVA_HOME` environment variables. You don't need to modify both, but one or the other should do the trick:
    * Update your `PATH` environment variable to Java's `bin` folder.
    * Set the `JAVA_HOME` environment variable to the root folder of your Java installation.
1) In VSCode's settings, set `as3mxml.java.path` to the absolute path of the `java` executable.

The versions of Java should be installed here, by the way: */Library/Java/JavaVirtualMachines/*

**Comment by velara3** [comment]
In that directory I only see 1.6.0.jdk. Does it have to be the JDK or will JRE work? 

When I run `/usr/libexec/java_home -V` I get this: 

> Matching Java Virtual Machines (2):
    1.6.0_65-b14-468, x86_64:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home
    1.6.0_65-b14-468, i386:	"Java SE 6"	/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home

**Comment by velara3** [comment]
The error has gone away since installing the JDK from [here](https://www.oracle.com/technetwork/java/javase/downloads/jdk12-downloads-5295953.html) Thanks

**Comment by joshtynjala** [comment]
> Does it have to be the JDK or will JRE work?

JRE is fine.

> The error has gone away since installing the JDK from here Thanks

Great!

**Comment by joshtynjala** [comment]
By the way, you may want to switch to OpenJDK, considering Oracle's recent license changes to their commercial version.

https://openjdk.java.net/install/
