### ISSUE TITLE
Possible to have more than one application per workspace

### ISSUE THREAD

**Issue by velara3** [BowlerHatLLC/vscode-as3mxml#357]
Is it possible to have two or more applications per project? 

I have two mxml applications in the src directory that I'm switching between. Should I have two asconfigs and rename them when switching?

**Comment by joshtynjala** [comment]
Yes, you can have more than one *asconfig.json* file in your workspace. You must always have one named *asconfig.json*, but you can define additional files using the naming format: *asconfig.myapp.json* (replace *myapp* with anything you'd like). These additional files don't affect the code intelligence in the editor, but each one will get its own set of build tasks.

**Comment by velara3** [comment]
The code intelligence is working but I'm not able to get the second application to debug. I created two launch configurations but they both launch the application in asconfig.json

   "version": "0.2.0",
   "configurations": [
      {
         "type": "swf",
         "request": "launch",
         "name": "Launch My App",
         "preLaunchTask": "ActionScript: compile debug - asconfig.my-app.json"
      },
      {
         "type": "swf",
         "request": "launch",
         "name": "Launch SWF",
         "preLaunchTask": "ActionScript: compile debug - asconfig.json"
      }
   ]
}

**Comment by velara3** [comment]
The code intelligence is working but I'm not able to get the second application to debug. I created two launch configurations but they both launch the application in asconfig.json:

      {
         "version": "0.2.0",
         "configurations": [
            {
               "type": "swf",
               "request": "launch",
               "name": "Launch My App",
               "preLaunchTask": "ActionScript: compile debug - asconfig.my-app.json"
            },
            {
               "type": "swf",
               "request": "launch",
               "name": "Launch SWF",
               "preLaunchTask": "ActionScript: compile debug - asconfig.json"
            }
         ]
      }

**Comment by joshtynjala** [comment]
For *asconfig.my-app.json*, you'll need to use the [`program`](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/launch.json-fields-for-SWF-debugging#program) field in *launch.json*. Set it to the path to a *.swf* file, to an Adobe AIR application descriptor *.xml* file, or to an *.html* file to launch in a browser.

**Comment by velara3** [comment]
When I set this value I get an error, `initial content not found`.

      {
         "type": "swf",
         "request": "launch",
         "name": "Launch My App",
         "program": "src/MyApp-app.xml"
      }

>Error launching SWF debug session. Process exited with code: 8
>Process terminated without establishing connection to debugger.
>initial content not found

**Comment by joshtynjala** [comment]
> "program": "src/MyApp-app.xml"

You should instead set it to the file that gets copied to the output folder as part of the build process. You want to be sure that the initial content is correctly populated and that any relative paths get resolved from the output folder and not from somewhere else where they won't work.

**Comment by velara3** [comment]
When I set the program to a SWF like this:

      {
         "type": "swf",
         "request": "launch",
         "name": "Launch My App",
         "program": "bin-debug/MyApp.swf"
      },

It looks like it's waiting to attach to the swf, the progress bar moves, but the adl app never opens. 

When I remove the program name value pair the default application in asconfig opens.

**Comment by joshtynjala** [comment]
Is will only launch ADL if you set `program` to the AIR XML file. That's what I was referring to when I mentioned the file copied to your output folder. So, like this:

```
"program": "bin-debug/MyApp-app.xml"

```

When you tell it to launch a SWF, it should launch standalone Flash Player, if you have it associated with SWF files. However, for an AIR app, you don't want that.

**Comment by velara3** [comment]
It is working great. Thanks for clarifying that.

**Comment by cgascons** [comment]
Hi! Sorry to re-open an already closed issue, I have a question regarding what you mentioned @joshtynjala:

> You must always have one named asconfig.json

and I thought it'd be better to ask it here rather than creating a new issue.

Does this asconfig.json needs to be valid (not blank)? i.e., in my case we have 5 games running on 5 different platforms. 

My intention would be to have 1 folder for each project, containing 5 subfolders, 1 for each platform. I'd like to have an asconfig.json for each platform something like: asconfig-ios.json, asconfig-android.json, asconfig-facebook.json, etc... for the sake of clarity, can the default asconfig.json be completely blank? Or should it be valid for some reason? It's not returning any errors when left blank, but I'd like if there's any surprise coming if I decide to leave the setup as is.

**Comment by joshtynjala** [comment]
It should not be blank. This is the file that configures the code intelligence in VSCode, so it's important to set the correct compiler options for your project.

**Comment by cgascons** [comment]
Thanks for the info josh, I was surprised that it actually worked with an empty (`{}`) asconfig.json though. I was only considering leaving blank the default one, all the other asconfig.json files had their compiler options properly set.

**Comment by joshtynjala** [comment]
I'm also surprised that `{}` worked. You should get some kind of error that certain fields are required.

**Comment by cgascons** [comment]
I'm actually having some trouble, I'm writing a new issue in order to give you more details, I do believe I'm close to make it work
