### ISSUE TITLE
unverified breakpoints for non-as3 source files (e.g. Haxe)

### ISSUE THREAD

**Issue by nadako** [BowlerHatLLC/vscode-as3mxml#359]
I'm trying to use the debugger from this extension with an SWF generated from Haxe and it can't set breakpoints, I guess due to [this check](https://github.com/BowlerHatLLC/vscode-as3mxml/blob/aeb85d4023d3756a41d63216ccb35b7bcb576f40/swf-debugger/src/main/java/com/as3mxml/vscode/SWFDebugSession.java#L892). Could you do something about this please? :-)

**Comment by nadako** [comment]
Thank you very much! Release anytime soon? :)

**Comment by joshtynjala** [comment]
I'm a couple of weeks, maybe.

**Comment by nadako** [comment]
Alright, I'm gonna try building the dev version then!
