### ISSUE TITLE
FlashDevelop project import

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/vscode-as3mxml#361]
Similar to #322, but for FlashDevelop projects.

Here's the code for importing Flash Builder projects:

https://github.com/BowlerHatLLC/vscode-as3mxml/blob/master/vscode-extension/src/main/ts/commands/importFlashBuilderProject.ts

FlashDevelop project files are also an XML based format, so the code should end up being very, very similar.

**Comment by alanlanglois** [comment]
I'm giving a look at it, I'm not very familiar with FlashBuilder and VSCode, and I'm not sure there is something similar to workspace in Flashdevelop.
I would guess, we "_just_" have to import the FD project file, read it and convert it to a `asconfig.json`.
Here is an example from one of my projects: 
```<?xml version="1.0" encoding="utf-8"?>
<project version="2">
  <!-- Output SWF options -->
  <output>
    <movie outputType="Application" />
    <movie input="" />
    <movie path="bin\cachecacheville.swf" />
    <movie fps="50" />
    <movie width="320" />
    <movie height="640" />
    <movie version="28" />
    <movie minorVersion="0" />
    <movie platform="AIR Mobile" />
    <movie background="#FFFFFF" />
    <movie preferredSDK="AIR 29.0.0;29.0.0;" />
  </output>
  <!-- Other classes to be compiled into your SWF -->
  <classpaths>
    <class path="src" />
  </classpaths>
  <!-- Build options -->
  <build>
    <option accessible="False" />
    <option advancedTelemetry="True" />
    <option allowSourcePathOverlap="False" />
    <option benchmark="False" />
    <option es="False" />
    <option inline="False" />
    <option locale="" />
    <option loadConfig="" />
    <option optimize="True" />
    <option omitTraces="True" />
    <option showActionScriptWarnings="True" />
    <option showBindingWarnings="True" />
    <option showInvalidCSS="True" />
    <option showDeprecationWarnings="True" />
    <option showUnusedTypeSelectorWarnings="True" />
    <option strict="True" />
    <option useNetwork="True" />
    <option useResourceBundleMetadata="True" />
    <option warnings="False" />
    <option verboseStackTraces="False" />
    <option linkReport="" />
    <option loadExterns="" />
    <option staticLinkRSL="True" />
    <option additional="-swf-version=35" />
    <option compilerConstants="" />
    <option minorVersion="" />
  </build>
  <!-- SWC Include Libraries -->
  <includeLibraries>
    <!-- example: <element path="..." /> -->
  </includeLibraries>
  <!-- SWC Libraries -->
  <libraryPaths>
    <element path="lib\as3-signals-v0.9-BETA.swc" />
    <element path="lib\AS3YAML_041.swc" />
    <element path="lib\EazeTween-rc2.swc" />
    <element path="lib\global.swc" />
    <element path="lib\NetworkInfoActionScriptLibrary.swc" />
    <element path="lib\robotlegs-starling-plugin-v0.2.swc" />
    <element path="lib\starling.swc" />
    <element path="lib\gestouch-0.4.1.swc" />
    <element path="lib\Swiftsuspenders-v2.0.0rc3.swc" />
    <element path="lib\robotlegs-framework-v2.1.0.swc" />
    <element path="lib\PNGEncoder2_fast.swc" />
  </libraryPaths>
  <!-- External Libraries -->
  <externalLibraryPaths>
    <!-- example: <element path="..." /> -->
  </externalLibraryPaths>
  <!-- Runtime Shared Libraries -->
  <rslPaths>
    <!-- example: <element path="..." /> -->
  </rslPaths>
  <!-- Intrinsic Libraries -->
  <intrinsics>
    <!-- example: <element path="..." /> -->
  </intrinsics>
  <!-- Assets to embed into the output SWF -->
  <library>
    <!-- example: <asset path="..." id="..." update="..." glyphs="..." mode="..." place="..." sharepoint="..." /> -->
  </library>
  <!-- Class files to compile (other referenced classes will automatically be included) -->
  <compileTargets>
    <compile path="src\com\lekiosque\ccv\Main.as" />
  </compileTargets>
  <!-- Paths to exclude from the Project Explorer tree -->
  <hiddenPaths>
    <hidden path="obj" />
  </hiddenPaths>
  <!-- Executed before build -->
  <preBuildCommand />
  <!-- Executed after build -->
  <postBuildCommand alwaysRun="False" />
  <!-- Other project options -->
  <options>
    <option showHiddenPaths="True" />
    <option testMovie="Custom" />
    <option testMovieCommand="Run.bat" />
  </options>
  <!-- Plugin storage -->
  <storage>
    <entry key="at_enabled"><![CDATA[1]]></entry>
    <entry key="at_password"><![CDATA[azerty]]></entry>
  </storage>
</project>```

**Comment by joshtynjala** [comment]
Yes, exactly. That file should have pretty much everything that's needed.

**Comment by alanlanglois** [comment]
Yep, investigating a little more into it (that's a pretty long file to parse haha). 
Some other data defined in Bat files (SetupApplication.bat/SetupSDK.bat) might also be parsed/added such as: 
 - certificats paths for ios/android
 - icons path for ios/android
 - sdk path? (probably not necessary as it's manage by the vscode workspace if I get it right)
 - signing options

I'm currently trying to work on this fork: https://github.com/alanlanglois/vscode-as3mxml/blob/FD-import/vscode-extension/src/main/ts/commands/importFlashdevelopProject.ts

Here is the main template used to develop as3 AIR Mobile Project using FD, including the as3proj and bat files: https://github.com/fdorg/flashdevelop/tree/development/External/Extensions/AS3Templates/%24(BaseDir)/Projects/190%20ActionScript%203%20-%20AIR%20Mobile%20AS3%20App

**Comment by joshtynjala** [comment]
Don't try to parse anything in the *.bat* files. Even if they usually follow a standard format, that's still a scripting language, and there are a lot of edge cases that we don't want to try to cover.

It might make sense to add the *.bat* files to the workspace's *tasks.json*. I'm not sure if there's an API for that in VSCode, though. If not, it might just make sense for me to include how to do that in the documentation.

**Comment by alanlanglois** [comment]
I agree, on most of my projects I customized those files which make it difficult to interpret from one project to the other. 
I think having a prompt with the missing info contained in the bat files would make the trick, it's mainly paths references anyway.

**Comment by joshtynjala** [comment]
I think that those paths should simply be skipped, at least for a first iteration. Assuming that you can figure out that it's an AIR project from the *.as3proj* file, we can display a warning in the output console that those fields need to be set manually in *asconfig.json*.
