### ISSUE TITLE
Make properties generation public default

### ISSUE THREAD

**Issue by piotrzarzycki21** [BowlerHatLLC/vscode-as3mxml#364]
Option for generating get/set property from some class field make them private default. I catch myself many times that I have generated such properties and discovered that hey are private when I'm compiling app instead earlier. It would be super convenient if generated property would be public default.

![properties](https://user-images.githubusercontent.com/24554795/57539252-66bdce00-734a-11e9-9295-516d7d8c7086.gif)

**Comment by joshtynjala** [comment]
If the variable is public, the getter and setter will be public. It's choosing private because your variable is private.

**Comment by piotrzarzycki21** [comment]
Ahh! Ok now I understand :) I always create private field. Never starts from public. That make sense. Thanks and sorry for the noise!

**Comment by Adolio** [comment]
Thanks @joshtynjala for the new options 🙂

This is maybe my concern in #450. I will double check when the release is there and update the task.
