### ISSUE TITLE
No trace output in Debug Console, no breakpoints either

### ISSUE THREAD

**Issue by ddorris** [BowlerHatLLC/vscode-as3mxml#365]
Recently I can't seem to do a basic
trace("hello world");
and the debugger is ignoring any breakpoints I set.

I don't think anything changed in my configuration.

I am using Adobe AIR 30 and have the latest Node, VS Code, and the latest as3mxml extension.

Has anything changed?

Is there a minimal AIR example project that I could test with?

**Comment by joshtynjala** [comment]
Have you been using Ctrl+Enter to compile and debug in one step? If so, you need to use Crtl+Shift+Enter now. I needed to change it make things more consistent with Adobe Animate, where those keyboard shortcuts come from.

**Comment by ddorris** [comment]
Yes! Thank you!
I love it when the answer is easy!

**Comment by zhaiduo** [comment]
> Crtl+Shift+Ente

I try it on MacOS, seems not work. Would you please tell me how to trace the output in Mac ENV?

**Comment by joshtynjala** [comment]
@zhaiduo On macOS, you use **Command** instead of Ctrl.

**Comment by zhaiduo** [comment]
Thanks! @joshtynjala can you share your launch.json? My config seems not work:

> {
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "type": "swf",
      "request": "launch",
      "name": "Launch SWF",
      "internalConsoleOptions": "openOnSessionStart"
    }
  ]
}

**Comment by zhaiduo** [comment]
> {
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "type": "actionscript",
      "debug": true,
      "problemMatcher": [],
      "presentation": {
        "reveal": "always",
        "focus": true,
        "panel": "new"
      }
    }
  ]
}

I changed task.json, still can see the trace output.

**Comment by joshtynjala** [comment]
@zhaiduo That's all you need in launch.json. When using Cmd+Shift+Enter, tasks.json is ignored.

Which program is launching? Is it the AIR Debug Launcher? Standalone Flash Player?

**Comment by zhaiduo** [comment]
@joshtynjala just compile ActionScript3 in debug mode, use Flex4.6 SDK. No debug launcher, use Flash player in Chrome. But still no trace output.

> /Users/***/.vscode/extensions/bowlerhatllc.vscode-nextgenas-0.21.0/bin/asconfigc.jar --sdk 
 /Users/***/Downloads/flex_sdk_4.6 --debug=true --project /Users/***/work/BAK/flash9/asconfig.json 
/Users/***/work/1/bin/particles.swf
Press any key to close the terminal.

**Comment by joshtynjala** [comment]
@zhaiduo The default version of Flash Player included with Chrome does not support debugging. Did

**Comment by zhaiduo** [comment]
> @zhaiduo The default version of Flash Player included with Chrome does not support debugging or trace output. Did you install the debug version of Flash Player for Chrome?

Ok, I will install one debug version. Thanks very much! @joshtynjala
