### ISSUE TITLE
Exception has occurred. Error: (new Main(...)).start is not a function

### ISSUE THREAD

**Issue by velara3** [BowlerHatLLC/vscode-as3mxml#366]
I'm not sure what changed but I tried to setup a new AS3 project and I started to get a new error message: 

>Exception has occurred.  
>Error: (new Main(...)).start is not a function

I opened a previous project that was working and I'm getting the same error on that project. 

I'm able to run an Royale MXML document but not an AS. 

The HTML page template throws an error on the first line: 

```
<body>
	<script type="text/javascript">
		new Main().start();
	</script>
</body>
```
IIRC I thought it was `new Main();` but clearly it shows calling a start() method. 

The class is: 

```
package
{
	public class Main
	{
		public function Main()
		{
			var element:HTMLDivElement = document.getElementById("header") as HTMLDivElement;
			element.innerText = "Hello World!";
		}
	}
}
```

**Comment by velara3** [comment]
The original project is working fine. It looks like VSC can only have one project open at a time? It looks like it's closing the first project when I open the second project.

**Comment by joshtynjala** [comment]
Yeah, Royale framework apps must have a public `start()` method. With pure AS3 apps, the details template just calls the constructor.

`"config": "js"` should use the "JS" target instead of "JSRoyale". This is the default, if you omit it.
