### ISSUE TITLE
Suggestion: Add guide for Installation of Apache Royale SDK

### ISSUE THREAD

**Issue by velara3** [BowlerHatLLC/vscode-as3mxml#372]
I found this tip from your post about how to install Apache Royale SDK: 

>...you will need Apache Royale 0.9.4 or newer. Use the downloads page, or download it from Node Package Manager with

npm install @apache-royale/royale-js -g

This is much simpler install instruction than other methods I've seen. 

https://royale.codeoscopic.com/hello-node-how-to-transpile-actionscript-for-node-js/

**Comment by joshtynjala** [comment]
I'm not sure that's within the scope of the documentation for the VSCode extension. The [Apache Royale download page](https://royale.apache.org/download/) already mentions that you can use npm to install it. Even without npm, it's not like Flex, where you had to run an install script to get some final dependencies. With Royale, you can just unzip and your SDK is good to go!

**Comment by velara3** [comment]
Before discovering npm I had installed it the classic way. npm install was much quicker. With npm where does it install it to?

**Comment by joshtynjala** [comment]
Off the top of my head, I don't remember where exactly npm installs things globally. Somewhere in your user directory. On Windows, that's probably somewhere in *c:\Users\username\AppData\*. On macOS, that would be somewhere in */Users/username/Library/*.

One thing worth noting, also, is that not everyone will have Node.js installed already, so it might end up being more complicated for those people to use npm.
