### ISSUE TITLE
AutoComplete for Vector.<*>

### ISSUE THREAD

**Issue by MTeamapps** [BowlerHatLLC/vscode-as3mxml#373]
Dear Josh, thanks for your amazing ActionScript support for VS code.
I found out that you didn't support autocomplete for Vectors.
The IDE doesn't understand values and classes of a vector like this sample:

```
var a:Vector.<B> = new Vector.<B>();

class B{
 var c;
 var d;
}

//////////////////////

a[0].?
```

**Comment by joshtynjala** [comment]
I have confirmed that this is not working correctly. Thank you for reporting the bug!
