### ISSUE TITLE
Auto open parentheses for functions on auto complete

### ISSUE THREAD

**Issue by MTeamapps** [BowlerHatLLC/vscode-as3mxml#374]
On autocompletes, there is no difference between values and methods. because not parentheses opens for methods after ctrl+space. this is how IntelliJ and Eclipse show methods after ctrl+space.

**Comment by joshtynjala** [comment]
I recently implemented this in commit aeb85d4023d3756a41d63216ccb35b7bcb576f40. It will be available in the next update!
