### ISSUE TITLE
Specifying files under ios/android in airOptions ignores files directly under airOptions 

### ISSUE THREAD

**Issue by mrfrasier** [BowlerHatLLC/vscode-as3mxml#375]
So it seems that if you specify an asconfig similar to the following:

```
"airOptions": {
        "files": [
            // base spritesheet
            { "file":"assets/sprites/mysprite.atf", "path":"assets/mysprite.atf"},
            { "file":"assets/sprites/mysprite.xml", "path":"assets/mysprite.xml"},
        ],
		"android": {
			"files": [
            // android spritesheet
            { "file":"assets/sprites/android .atf", "path":"assets/android .atf"},
            { "file":"assets/sprites/android .xml", "path":"assets/android .xml"},
            ]
		}
}
```

Then the files specified under airOptions directly are ignored and only the files specified under android (or iOS) are added. That is to say, android.atf is added, but mysprite.atf is ignored.

Is this intentional?

**Comment by joshtynjala** [comment]
Yes, it's intentional. When you specify a platform section, like `ios` or `android`, each option completely replaces the one specified in `airOptions`. They are not merged.

**Comment by mrfrasier** [comment]
OK gotcha. Would it not make sense to allow both though? Or maybe I'm just using it wrong.

I like to keep the splash screen and iOS-specific icons under the ios section and the generic stuff like spritesheets (which apply to both Android and iOS) in the main section. Is there another way I should be doing that?

**Comment by joshtynjala** [comment]
There is not a way to avoid duplicates when you have multiple platforms. However, it does support specifying entire folders, so you could limit the number of duplicates that are required by putting all of your shared assets in a single same folder.

**Comment by mrfrasier** [comment]
I didn't create an issue for that, but I had no success including whole folders. It just didn't see the files on compilation, so I resorted to individually naming every file

```
// Fonts
            { "file":"assets/fonts/Proxima.png", "path":"assets/fonts/Proxima.png"},
            { "file":"assets/fonts/Proxima.fnt", "path":"assets/fonts/Proxima.fnt"},
            { "file":"assets/fonts/novecentowidebold.png", "path":"assets/fonts/novecentowidebold.png"},
            { "file":"assets/fonts/novecentowidebold.fnt", "path":"assets/fonts/novecentowidebold.fnt"},
            { "file":"assets/fonts/arial.png", "path":"assets/fonts/arial.png"},
            { "file":"assets/fonts/arial.fnt", "path":"assets/fonts/arial.fnt"},
            { "file":"assets/fonts/Oswald2.png", "path":"assets/fonts/Oswald2.png"},
            { "file":"assets/fonts/Oswald2.fnt", "path":"assets/fonts/Oswald2.fnt"},
            { "file":"assets/fonts/OswaldLight.png", "path":"assets/fonts/OswaldLight.png"},
            { "file":"assets/fonts/OswaldLight.fnt", "path":"assets/fonts/OswaldLight.fnt"},
```

With the above I originally just had the fonts folder included, but it wouldn't read them.

**Comment by joshtynjala** [comment]
I distinctly remember that including folders was broken in the past, but then I fixed it, so it should be possible.

However, I've always found that it can be tricky getting the paths correct when including any extra files in an AIR app. They don't always end up where I expect in the apk/ipa file, so I try a few random paths resolved from File.applicationDirectory and nothing seems to work. I find that I always end up unzipping the apk/ipa to double-check where things have actually ended up, and then it's easier.

**Comment by mrfrasier** [comment]
All good, I'll stick to files for now. Thank you
