### ISSUE TITLE
Unknown attribute: unicodeRange with embedded font

### ISSUE THREAD

**Issue by gibbz-one** [BowlerHatLLC/vscode-as3mxml#378]
Hi! I'm trying to embed a TTF font in a new VSCode AIR Desktop simple project, using the code:

`[Embed(source="fonts/DroidSans.ttf",
	    fontName = "DroidSans",
	    mimeType = "application/x-font",
	    fontWeight="normal",
	    fontStyle="regular",
		unicodeRange = "U+0020-007E,U+00A1-00FF,U+2000-206F,U+20A0-20CF,U+2100-2183",
	    advancedAntiAliasing="true",
	    embedAsCFF="false")]
		private var fontDroidSans:Class;`

The compiler shows me this error:

> Unknown attribute: unicodeRange

This code was running fine in another Flash Builder project. 
Thanks in advance!

**Comment by joshtynjala** [comment]
This is likely a limitation of the Apache Royale compiler, which is used for AS3/MXML code intelligence only. It has some limitations related to embedding, especially fonts. However, that's only for code intelligence in the editor. If you run the compile task, it should be able to build successfully.

**Comment by gibbz-one** [comment]
I confirm that the compile task run successfully.
Thank You, Josh!

**Comment by joshtynjala** [comment]
I updated the Apache Royale compiler to support the `unicodeRange` attribute in `[Embed]` metadata. The VSCode extension will be updated with the new compiler when the next version of Royale is released.

apache/royale-compiler@13a701bd22ccf2df2e52bb671c53624d505cc75f

**Comment by gibbz-one** [comment]
Great! Thank You!
