### ISSUE TITLE
v 0.20 download

### ISSUE THREAD

**Issue by yooni126** [BowlerHatLLC/vscode-as3mxml#382]
hi josh
how can I download version 0,20 of your vscode-1s3mxml?

**Comment by joshtynjala** [comment]
It should update automatically, if you have an older version of the extension already. However, it might not let you update, if you're on a version of VSCode older than 1.34. That's the new minimum supported version of VSCode, so make sure that you're up to date.

**Comment by joshtynjala** [comment]
Additionally, I always post a *.vsix* file when I release a new version of the extension. This can be used to install it manually. However, I recommend always getting the extension from the marketplace.

https://github.com/BowlerHatLLC/vscode-as3mxml/releases
