### ISSUE TITLE
Problems debugging SWF embedded in HTML from a remote URL.

### ISSUE THREAD

**Issue by cgascons** [BowlerHatLLC/vscode-as3mxml#383]
I am attempting to debug a SWF embedded in an html file directly from a remote URL. I have achieved debugging the file in local but I'm having a hard time debugging the same file after uploading it into the server.

This is a chunk from the launch.json file I'm using to launch both configs:

```
{
            "type": "swf",
            "request": "launch",
            "name": "Debug Browser (LOCAL)",
            "program": "_browser/bin/FSPreloader.html",
            "runtimeExecutable": "/Applications/Safari.app",
            "preLaunchTask": "ActionScript: compile debug - asconfig-browser.json"
        },
        {
            "type": "swf",
            "request": "launch",
            "name": "Debug Browser (dev)",
            "program": "https://apps.facebook.com/appame-dev",
            "runtimeExecutable": "/Applications/Safari.app"
        }
```
The first one is working just fine, but when attempting to load the '_Debug Browser (dev)_' one Safari is launched with this in its url field:

`file:///Users/cgascons/Library/Containers/com.apple.Safari/Data/https:/apps.facebook.com/appname-dev%3Fdebug=true
`
Of course nothing happens after that, if I change the url for the right one, it loads properly and starts debugging. Could you point me in the right direction here? I must be missing something.

Thanks

**Comment by joshtynjala** [comment]
That seems like a bug in the extension. I'll investigate!

**Comment by cgascons** [comment]
Also, not sure if related (probably), but the very first time I try to debug via Safari there's a prompt shown before running the html file that says "Please confirm the file to load", and I have to manually select the .html file, then it starts debugging. 

Image attached:
![confirmation](https://user-images.githubusercontent.com/2189330/60077486-514e0900-972a-11e9-82ad-24bab6bb5210.png)

**Comment by joshtynjala** [comment]
> the very first time I try to debug via Safari there's a prompt

I think that this is a security feature of Safari to avoid random apps running arbitrary local scripts. I worked on a project recently where I had to force local files to run in Chrome because this confirmation in Safari made for a terrible user experience.

**Comment by cgascons** [comment]
I see, it is indeed terrible, thanks for the info though, I thought I was doing something wrong here.

**Comment by joshtynjala** [comment]
Does the same thing happen if you try a different browser, like Firefox or Chrome?

**Comment by joshtynjala** [comment]
C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

**Comment by joshtynjala** [comment]
I confirmed myself that the correct URL is opened in Firefox and Chrome. It's either a Safari issue or an issue with the debugger included in the SDK. It's actually the debugger that handles launching the app, rather than the VSCode extension.
