### ISSUE TITLE
Code intelligence doesn't work for included and referenced files

### ISSUE THREAD

**Issue by jnpatrick99** [BowlerHatLLC/vscode-as3mxml#385]
It seems the code intelligence doesn't work for files using ```include 'file.as'``` and also for ```<mx:Script source="file.as"/>```. Some of our projects are using Flex 3 so it's ```mx:Script```. 

Is this a known issue? I noticed there was a similar case https://github.com/BowlerHatLLC/vscode-as3mxml/issues/331.

**Comment by joshtynjala** [comment]
It's a known issue. See #324.

It's better than it used to be, but as you've discovered, it's not perfect. There are probably sections of your included files where code intelligence actually works. It may depend on the size of the file, though. I had some trouble figuring out how certain offsets were supposed to work, so I gave up for now. I may revisit it in the future.

**Comment by jnpatrick99** [comment]
I see, thank you for the explanation! Looking forward to the future!
