### ISSUE TITLE
Compiling/launching within multi root workspace

### ISSUE THREAD

**Issue by cgascons** [BowlerHatLLC/vscode-as3mxml#387]
When having a multi-root workspace, if one of the workspaces in it has a specific SDK assigned, the compile or debug tasks will always use the "parent" workspace's SDK, is this intended?

**Comment by joshtynjala** [comment]
That's just how settings in VSCode work when you have a multi-root workspace. Settings in individual workspace folders are ignored. As you discovered, this means that a multi-root workspace can't use different SDKs for each folder.

**Comment by cgascons** [comment]
I see josh, didn't know that. I guess I will have to think some other way of debugging with a specific sdk then, thanks
