### ISSUE TITLE
Linux Flex/AIR Desktop

### ISSUE THREAD

**Issue by screenpunch** [BowlerHatLLC/vscode-as3mxml#391]
Perhaps the wrong place to ask this, but is it possible to debug an Apache Flex AIR project in Linux with this plugin?

**Comment by joshtynjala** [comment]
I was able to successfully connect the debugger to Flash Player on Linux. I've never tried debugging AIR on Linux, though, but I don't see why it couldn't work too. You'll just be stuck on the old AIR 2.6, since that was the last release of AIR for Linux.
