### ISSUE TITLE
 What is the component that replaces  <mx: RemoteObject in Apache Royale Jewel <j: RemoteObject ?

### ISSUE THREAD

**Issue by lmarevaloa** [BowlerHatLLC/vscode-as3mxml#392]

**Comment by lmarevaloa** [comment]
I want to call and send data to a function from Apache royale Jewel to PHP, but I do not know how I can do it since there is no information or any method that is identical to the one that was handled in flex.:(

**Comment by piotrzarzycki21** [comment]
Did you review examples available in Royale?

**Comment by joshtynjala** [comment]
The Apache Royale users mailing list is a more appropriate place to ask this question:

https://royale.apache.org/mailing-lists/
