### ISSUE TITLE
Packaging directory instead of file does not work if asconfig.json is not in the root of workspace

### ISSUE THREAD

**Issue by varadig** [BowlerHatLLC/vscode-as3mxml#396]
What about this issue?
https://github.com/BowlerHatLLC/vscode-as3mxml/issues/225

I really need to package a lot of file inside my captive runtime application, so this is not an option to write file-path object in files array for every single file.

If I point the file to a directory:

```
{
        "file": "resources/defaults",
        "path": "defaults"
      }
```

can't package the app:

`File does not exist: resources/defaults `

**Comment by joshtynjala** [comment]
Packaging folders is supported. Double check that you haven't accidentally mixed up the "file" and "path" fields. The "file" field refers to the location on your development computer, relative to your project's root folder. The "path" field refers to the location in the packaged app (inside the APK file on Android or the IPA file on iOS, similar on Windows or macOS)

**Comment by varadig** [comment]
Thanks @joshtynjala , but I did not mixed the two value, there is something other.
![Screenshot 2019-08-07 09 41 36](https://user-images.githubusercontent.com/6317148/62604132-a9feed00-b8f7-11e9-8abb-85491ed249c5.png)

**Comment by joshtynjala** [comment]
I have figured out how to reproduce the issue, and I'll get it fixed! I think it may be generating the relative path by using *DynamicDungeonsVS* as the root instead of *editor*.

In the meantime, as a temporary workaround, you can open the *editor* folder as your workspace root. That will make it calculate the relative path correctly.

**Comment by varadig** [comment]
Thanks Josh!!!
