### ISSUE TITLE
Flex project fail to build since version 0.18.0 (Error: Java heap space)

### ISSUE THREAD

**Issue by valterrgodoy** [BowlerHatLLC/vscode-as3mxml#397]
Hi, my flex project build succesfully on version 0.18.0, but fail to build on newer versions. After 10 min, I receive a java heap space.
Visual Studio Code 1.36.1
Apache Flex 4.16.1

**Comment by joshtynjala** [comment]
Can you share the exact error message that you see?

**Comment by joshtynjala** [comment]
And are you on Windows or macOS?

**Comment by valterrgodoy** [comment]
Hi, i'm on Windows 7.
I receive the message:
> Executing task in folder Flex: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe -jar c:\Users\Valter\.vscode\extensions\bowlerhatllc.vscode-nextgenas-0.21.0\bin\asconfigc.jar --sdk c:\Dev\Flex\4.16.1 --debug=true --project c:\Dev\SVN\MKSaude\Flex\asconfig.json <

Loading configuration file C:\Dev\Flex\4.16.1\frameworks\flex-config.xml
Error: Java heap space

The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.
[Flex.zip](https://github.com/BowlerHatLLC/vscode-as3mxml/files/3482448/Flex.zip)

Configuration files atacched.
Thanks.

**Comment by joshtynjala** [comment]
In your previous IDE, do you remember if you ever had to specify some kind of option to increase the Java heap space, like `-Xmx1024M` or something like that?

**Comment by valterrgodoy** [comment]
Yes, in the Flash Builder, I changed the FlashBuilder.ini with this:
-Xms512m
-Xmx1024m
-XX:+UseParallelGC
-XX:MaxPermSize=256m
-XX:PermSize=64m

Em qui, 8 de ago de 2019 às 12:35, Josh Tynjala <notifications@github.com>
escreveu:

**Comment by joshtynjala** [comment]
Thank you. It seems like I need to add a setting to the VSCode extension to allow you to customize it there too.

**Comment by valterrgodoy** [comment]
Any time. In version 0.18 build without errors and very fast.

Em qui, 8 de ago de 2019 14:45, Josh Tynjala <notifications@github.com>
escreveu:

**Comment by joshtynjala** [comment]
In the next update, a new `as3mxml.asconfigc.jvmargs` setting will be available. You'll be able to specify extra arguments for the JVM, like the ones you used in FlashBuilder.ini. In particular, -Xmx1024m will increase the max heap size, which should fix your build.

**Comment by joshtynjala** [comment]
I just published v0.22.0, which restores the old memory behavior. As mentioned in my previous comment, you can now also pass in custom values, if the JVM's defaults don't work either.
