### ISSUE TITLE
Templates / Starter Projects

### ISSUE THREAD

**Issue by cat7gods** [BowlerHatLLC/vscode-as3mxml#405]
Hi Josh, are there any project templates for mobile and desktop apps (asconfigs, settings, task, ANEs and SWCs import,....) available out there. I intend to move all my projects from FD to VS Code. I'm quite difficult to get start with your extension. THanks!

**Comment by joshtynjala** [comment]
There are no example projects or templates at this time. Just Only instructions on the wiki for setting up each project type. Here are the AIR mobile and desktop instructions:

* [AIR mobile](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Create-a-new-ActionScript-project-in-Visual-Studio-Code-that-targets-Adobe-AIR-for-mobile-platforms)
* [AIR desktop](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Create-a-new-ActionScript-project-in-Visual-Studio-Code-that-targets-Adobe-AIR-for-desktop-platforms)

And of course, there's also the reference of all of the available fields in *asconfig.json* files:

* [asconfig.json reference](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/asconfig.json)

I'd like to get a FlashDevelop project importer working, similar to the one that I created for Flash Builder, but other things have taken priority recently. One tip that might make this easier for you: You should be able to keep using the same *.bat* files that FlashDevelop created when you migrate to VSCode. Check out the [custom tasks](https://code.visualstudio.com/docs/editor/tasks#_custom-tasks) documentation on the VSCode website for how to set up your *tasks.json* file to run them. If you use the same *.bat* files, you can probably have a much simpler *asconfig.json* where you configure only what is needed for code intelligence.

**Comment by cat7gods** [comment]
Thanks for your reply. I still did not why. After re-installing VS Code and your extension. everything works well. I have this suggestion because vshaxe extension has some templates, so devs can save time for setting up projects. Hopefully your info can help someone. Cheers!
