### ISSUE TITLE
AIR 33 (Harman) - Armv8 Support

### ISSUE THREAD

**Issue by amjadhashim** [BowlerHatLLC/vscode-as3mxml#406]
hi guys, do we have any update on compatibility with air 33 - harman's version?

tried to set this to my asconfig but it failed to recognize "armv8" as a value for "arch"

```
"airOptions": {
 "android": {
 "arch": "armv8"
 }
}
```

**Comment by joshtynjala** [comment]
I'll make sure that it is properly supported in the next update.
