### ISSUE TITLE
Enable autocompletion for asconfig.*.json files

### ISSUE THREAD

**Issue by Adolio** [BowlerHatLLC/vscode-as3mxml#407]
Hi Josh,

Auto-completion for `asconfig.json` file is a great feature especially for newcomers 🙂

Could you do something to enable it for platform specific asconfig.json (asconfig.*.json) as well?

Best,
Aurélien

**Comment by joshtynjala** [comment]
I didn't realize that I hadn't enabled that! I'll make sure to add it soon.
