### ISSUE TITLE
Jewel Missing builtin type Object

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-as3mxml#408]
Hi,

I'm facing a weird issue. Don't since this is happening, since I was not opening Jewel and TourDeJewel to work over it since many days.

I'm using 0.22 version. When open VSCode for Jewel Library I get :

```
{
	"resource": "/Users/carlosrovira/Dev/Royale/Source/royale-asjs/frameworks/projects/Jewel/",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": "1475",
	"severity": 8,
	"message": "Missing builtin type Object",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}
```

My settings.xml is:
```
{
    "as3mxml.sdk.framework": "/Users/carlosrovira/Dev/Royale/Source/royale-asjs",
    "as3mxml.sdk.editor": "/Users/carlosrovira/Dev/Royale/Source/royale-asjs"
}
```

(pointing to where I build the SDK daily as always)

This causes VSCode gives me lots of errors when I try to modify a file

Hope you can get me some clue about what's could be happening

thanks!

**Comment by joshtynjala** [comment]
This error usually means that playerglobal.swc or js.swc is not being loaded. Which one that VSCode is looking for depends on whether SWF or JSRoyale appears first in the targets compiler option.

For instance, if SWF is first, but your SDK is missing playerglobal.swc, that's probably why you see the error.

**Comment by carlosrovira** [comment]
Thanks Josh,
in my case I can see in 'royale-asjs/frameworks/` folder subfolders for 11.1, 20.0 and 30.0 with corresponding `playerglobal.swc`. Maybe that's not the right folder, or subfolder structure. 
What means maybe something has changed in the ANT build that creates the daily SDK

**Comment by carlosrovira** [comment]
Hi Josh,

I just fix the issue moving the before mentioned playerblobal folders to `frameworks/libs/player`.
This means something has changed, or maybe can be some side effect of my testings with RC2.
