### ISSUE TITLE
asconfig output path prompt on release

### ISSUE THREAD

**Issue by devlfm** [BowlerHatLLC/vscode-as3mxml#409]
Hi @joshtynjala 

I was exporting a release, and on Flashbuilder when I'm releasing, I can choose where to export the release (e.g /releases/8.6.4), to do this on vscode, I have to change the output path before start the release and then undo the change for debugging. Is there a way to prompt for the output when we run the task for release?

Thank you

**Comment by joshtynjala** [comment]
Currently, the only way to do that is to create a separate asconfig file, named something like *asconfig.release.json*. In that file, you would set a different value for output. VSCode will provide separate tasks for both files.

If you do this, you'll need to duplicate all of the fields from your other asconfig file, and then you need to be careful to keep them both in sync. Eventually, I hope to add an `extends` field that allows you to reference a different asconfig file and only change what is needed. However, that's not possible yet.

**Comment by devlfm** [comment]
Ok, that was what I did.. I'll wait for extends field.
Thank you
