### ISSUE TITLE
Mark deprecated members (& move them to the bottom) in auto-completion dropdown

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/vscode-as3mxml#410]
When displaying a list of members in auto-completion dropdown, those that have been deprecated should be marked as such and possibly be moved to the bottom of the list.

**Comment by joshtynjala** [comment]
This will need to wait until the proposed API for deprecated completion items is finalized:

https://code.visualstudio.com/updates/v1_38#_deprecation-tags-for-symbols-and-completions
