### ISSUE TITLE
signing password

### ISSUE THREAD

**Issue by getfile** [BowlerHatLLC/vscode-as3mxml#411]
can i save keypass or storepass in asconfig.json?
when build air app,  i must input password everytime,  is bother.

**Comment by joshtynjala** [comment]
VSCode does not provide a good way to do something like that, but I was able to come up with this workaround:

https://github.com/BowlerHatLLC/vscode-as3mxml/blob/v0.22.0/distribution/src/assembly/CHANGELOG.md#tips--tricks-1

**Comment by getfile** [comment]
thanks for your reply
