### ISSUE TITLE
How to add -compiler.exclude-defaults-css-files ?

### ISSUE THREAD

**Issue by cristallium** [BowlerHatLLC/vscode-as3mxml#415]
Hi,
I have an issue to find how to use the 
-compiler.exclude-defaults-css-files=MXRoyale-${royale.framework.version}-js.swc:defaults.css

(check https://github.com/apache/royale-asjs/issues/495#issuecomment-539906300)
I there a specific syntax in as3config.json ?

Regards

**Comment by joshtynjala** [comment]
There's a field named `additionalOptions` where you can specify anything that isn't supported in the `compilerOptions` section.

**Comment by cristallium** [comment]
Many thanks for your quick reply. I missed it reading https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/asconfig.json
Tested and approuved
Regards
