### ISSUE TITLE
Wiki: Need to specify "target": "bundle" for captive runtime builds

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/vscode-as3mxml#416]
(The GitHub Wiki doesn't appear to have a way to suggest changes)

[This page](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Create-a-new-ActionScript-project-in-Visual-Studio-Code-that-targets-Adobe-AIR-for-desktop-platforms#captive-runtime) should say that `"target": "bundle"` is required for building captive runtimes (took me a while to figure out!)

**Comment by joshtynjala** [comment]
I can see that VSCode will provide me with a task to create a captive runtime build, even if I don't specify the "bundle" target. I gave it a try on the Feathers SDK Manager, and it is still working as expected. I believe that is why I omitted it from the wiki.

**Comment by joshtynjala** [comment]
Regardless, I still added it, just to have that information available.

**Comment by esidegallery** [comment]
Thanks Josh. Oddly it wasn't offering me that option.

**Comment by joshtynjala** [comment]
Did you set a different value for target instead? That could explain why you didn't see it.

**Comment by esidegallery** [comment]
It was an imported Flex project, which I believe set a target of "air", but I removed it. Some residual cached data under the bonnet perhaps?

**Comment by joshtynjala** [comment]
It reads asconfig.json every time the list of tasks is loaded, so nothing should be cached.

That being said, I actually saw this happen on a project last week. I wasn't sure why, exactly, and I didn't have a chance to dig into the source code to figure it out. My best guess was that my previous tests of the Feathers SDK Manager included `windows` and `mac` sections in the `airOptions`, and I might be checking for that too.

I'll try to revisit this when I get a chance. I think it makes sense to show captive runtime as an option, even if "bundle", "windows", and "mac" are undefined.

**Comment by joshtynjala** [comment]
I figured out that there was a technical reason for requiring target to be explicitly set to bundle, so I won't be making any changes to the behavior of the tasks because I simply cannot. However, it's now properly documented, so hopefully, this won't give anyone trouble anymore.
