### ISSUE TITLE
[QUESTION] Create SWC

### ISSUE THREAD

**Issue by angelhdz** [BowlerHatLLC/vscode-as3mxml#417]
Been searching a lot and I don't find anything. I need to create SWC library with all the AS files on a folder. Tried creating some commands in the tasks.json to call compc but it doesn't work. 
Is there specific settings in the launch.json to allow this? 

Also, when I execute compc directly in terminal, I get a lot of errors like this one:

```
Error: Definition flash.filesystem:File could not be found.

  import flash.filesystem.File;
```

The command I'm using is:

`compc -source-path+=src -include-sources+=src -target-player=31.0 -output=loaderapi.swc`

Thanks

**Comment by angelhdz** [comment]
### Found it

https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Create-a-new-ActionScript-library-project-in-Visual-Studio-Code

**Comment by dreammonkey** [comment]
The link seems to be broken, did the wiki move?
