### ISSUE TITLE
I'm desperate to set up the environment!

### ISSUE THREAD

**Issue by anderson-duarte-effetive-bib** [BowlerHatLLC/vscode-as3mxml#418]
Hi! I really need your help! I have a project in AsctionScript 3 and Mxml and I need to configure the project in vscode because I can no longer open FlashBuilder IDE.

I spoke to you on instagram, twitter and tried to get in touch with other social networks, can we talk about the development environment in VsCode? kkkkkkkkkkk

Plss Help me.

**Comment by joshtynjala** [comment]
The AS3 & MXML extension can import Flash Builder projects. Have you tried that?

**Comment by anderson-duarte-effetive-bib** [comment]
Sim, tendei, consegui buildar o projeto agora, mas ainda tenho alguns problemas com meus arquivos de AS3 que estão separados dos arquivos de MXML, tenho algumas variaveis Bindable que fica indicando erro.

Print:
<img width="527" alt="Screen Shot 2019-10-22 at 09 15 58" src="https://user-images.githubusercontent.com/56613909/67284840-c1885380-f4ac-11e9-822b-dde318fe65b5.png">

**Comment by joshtynjala** [comment]
Are you including the *.as* files inside the *.mxml* files like this?

```
<fx:Script source="file.as"/>
```

**Comment by anderson-duarte-effetive-bib** [comment]
Sorry, I wrote my last answer in Portuguese.

But yes, I'm including in the MXML file yes, like this:

`<mx:Script source="../business/iAnalysisSoSiPaStoBallena.as"/>`

And by the way, I can debug the application inside an HTML, the work you have been doing is amazing! Thanks a lot for the help!

**Comment by joshtynjala** [comment]
Unfortunately, including source files in MXML like this is not fully supported in VSCode at this time. I recommend using Script tags like this instead:

```mxml
<mx:Script>
    <![CDATA[
        //copy the contents of the .as file here
    ]]>
</mx:Script>
```

**Comment by anderson-duarte-effetive-bib** [comment]
Do you have any supported examples that I can use to try to do in separate files?

**Comment by joshtynjala** [comment]
I'm not sure that I understand what you mean.
