### ISSUE TITLE
Smart building of swcs

### ISSUE THREAD

**Issue by KidCoconuts** [BowlerHatLLC/vscode-as3mxml#419]
Hi,

I have a flex project that has about 10 libraries associated with it. I've got it building but it does take some time to compile so I was wondering if there is any feature that can determine if the swc needs to be created (and if not, use the one from the last build).

Is this possible?

Thanks

**Comment by joshtynjala** [comment]
Unfortunately, no. VSCode's tasks system doesn't keep track of modifications or anything like that, so it can only do a full build every time.

**Comment by KidCoconuts** [comment]
Ah ok, thanks
