### ISSUE TITLE
Spaces break links in Exception Peek UI

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/vscode-as3mxml#421]
Not sure if this is a VS Code specific bug, but I can't find any mention of it. See image below:

![Broken link](https://i.postimg.cc/fyzm5QVR/broken-link.png)

P.S. I am using VS Code for Windows

**Comment by joshtynjala** [comment]
Unfortunately, I don't have any control over how links are detected in the exception popup, so this is definitely a VSCode issue.
