### ISSUE TITLE
armv7 in iOS

### ISSUE THREAD

**Issue by pbranco-magikbee** [BowlerHatLLC/vscode-as3mxml#424]
Hi,

I'm using AIR SDK 33.0, compiling for iOS as debug and packaging the ipa file.
Checking the architectures inside, there's only arm64, and no armv7, so does not run on older devices.

I used before FB and AIR 32, which included both architectures in iOS, so I'm wondering if there's an issue with AIR 33, or I'm missing some setting...

Thanks !

**Comment by joshtynjala** [comment]
vscode-as3mxml does not have any special behavior for AIR 33 and iOS. It sends the same command to all SDKs when packaging an AIR app for iOS.

You'll need to ask Harman for help.

https://airsdk.harman.com/support
