### ISSUE TITLE
Class not found on project with ANE

### ISSUE THREAD

**Issue by alanlanglois** [BowlerHatLLC/vscode-as3mxml#425]
Hi there, 
I have a problem on an old FD project I'm trying to compile on VSCode.

I successfully run an other project without any ANE, but I'm struggeling with this one using 3 different ANE from distriqt. 

I got it running but when it start I got this error:

`VerifyError: Error #1014: Class com.distriqt.extension.compass.events::CompassEvent could not be found.`

![image](https://user-images.githubusercontent.com/712986/68409868-266bcb00-0188-11ea-84ab-06d491591078.png)

Here is some extract from my asconfig.json: 
 ```
{
	"config": "airmobile",
	"compilerOptions": {
		"output": "bin/Main.swf",
		"library-path": [
			"libs"
		],
		"source-path": [
			"src"
		],
		"external-library-path": [
			"ext/com.distriqt.androidsupport.V4.ane",
			"ext/com.distriqt.Compass.ane",
			"ext/com.distriqt.Core.ane",
			"ext/com.distriqt.Dialog.ane"
		],
		"swf-version": 43,
        "target-player": "32.0"
	},
	
	"application": "descriptor.xml",
	"files":
	[
		"src/com/etaminstudio/volcans/Main.as"
	],
	"airOptions": {
		"extdir": [
			"ext/com.distriqt.androidsupport.V4.ane",
			"ext/com.distriqt.Compass.ane",
			"ext/com.distriqt.Core.ane",
			"ext/com.distriqt.Dialog.ane"
		]
 ```

And the launch.json

 ```
"version": "0.2.0",
    "configurations": [
        {
            "type": "swf",
            "request": "launch",
            "name": "Launch SWF",
            "profile": "mobileDevice",
			"screensize": "iPhoneRetina",
			"screenDPI": 326,
            "versionPlatform": "IOS",
            "preLaunchTask": "${defaultBuildTask}",
            "extdir": "ext-debug"
        },
		{
			"type": "swf",
			"request": "attach",
			"name": "Attach SWF"
		}
    ]
 ```

Note the extdir contains unziped anes, 
and ext .ane files. 

It's probably something stupid, but I haven't found the cause yet...

**Comment by joshtynjala** [comment]
It's possible that some of your *.ane* files need to be added to the `library-path` instead of the `external-library-path`. I assume that distriqt's documentation will explain which one to use.

**Comment by joshtynjala** [comment]
Also, you should not need to specify `extdir` in *launch.json*. It was required in the past, but not any more. It will be populated automatically as part of the build process.

`extdir` in asconfig.json is required, though. So don't remove both of them.

**Comment by alanlanglois** [comment]
On FD I add this "Add to library" optin, how do I do the same on VSCode? 

![image](https://user-images.githubusercontent.com/712986/68415017-acd8da80-0191-11ea-9298-0b406c73c551.png)

**Comment by joshtynjala** [comment]
I am not experienced with FlashDevelop. I assume that it's equivalent to using the `library-path` compiler option. This is what I suggested in my first response.

**Comment by joshtynjala** [comment]
In other words, give this a try:

```
"library-path": [
	"ext/com.distriqt.androidsupport.V4.ane",
	"ext/com.distriqt.Compass.ane",
   	"ext/com.distriqt.Core.ane",
   	"ext/com.distriqt.Dialog.ane"
]
```

**Comment by alanlanglois** [comment]
It's getting better. 
At first I added the paths to the library-path and let them to the external-library-path with no luck. 
Having them only in the library-path node is better, don't have the last error but the extensions don't seem to be able to se their context : 
![image](https://user-images.githubusercontent.com/712986/68512367-7c1fa080-0278-11ea-8b74-a1647078541c.png)
Based on this error I found this faq answer: https://airnativeextensions.com/knowledgebase/faq/5
But don't really see how to apply this to vsCode :/

**Comment by alanlanglois** [comment]
Ok got it working :)
I added the full paths in AIR `airOptions` and removed the `extdir` in `launch.json`
```
"config": "airmobile",
	"compilerOptions": {
		"output": "bin/Main.swf",
		"library-path": [
			"libs",
			"ext/com.distriqt.androidsupport.V4.ane",
			"ext/com.distriqt.Compass.ane",
			"ext/com.distriqt.Core.ane",
			"ext/com.distriqt.Dialog.ane"
		],
		"source-path": [
			"src"
		],
		"external-library-path": [
		]
	},
	
	"application": "descriptor.xml",
	"files":
	[
		"src/com//Main.as"
	],
	"airOptions": {
		"extdir": [
			"ext/com.distriqt.androidsupport.V4.ane",
			"ext/com.distriqt.Compass.ane",
			"ext/com.distriqt.Core.ane",
			"ext/com.distriqt.Dialog.ane"
		],
```

Thanks a lot for your help and reactivity @joshtynjala !
