### ISSUE TITLE
Compilation error   

### ISSUE THREAD

**Issue by dileepnaduvinamani** [BowlerHatLLC/vscode-as3mxml#426]
Hi Team,
I am new to Apache-Royale, I am trying to build a simple HelloWorld application, I have followed the steps as shown in Git. I am getting an error like  Unable to open royale-config.xml, Please find the below screenshot.

![Capture](https://user-images.githubusercontent.com/23553653/68680077-091f6e00-0587-11ea-8921-b54ccc6a0ac1.PNG)

**Comment by piotrzarzycki21** [comment]
Hi @dileepnaduvinamani ,
I believe you may experiencing known issue if you are using 0.9.6 version. Try [my workaround](http://apache-royale-development.20373.n8.nabble.com/Broken-royale-config-in-JS-only-build-of-released-Apache-Royale-SDK-0-9-6-td12515.html#a12543). This patch fix will be also available as part of upcoming [Moonshine IDE](https://moonshine-ide.com/) release.

**Comment by dileepnaduvinamani** [comment]
Hi @piotrzarzycki21 
Thank You :) It's working fine with Hello World.
