### ISSUE TITLE
Image folder not copied into bin\js-debug folder.

### ISSUE THREAD

**Issue by T-San001** [BowlerHatLLC/vscode-as3mxml#427]
Hi,

There is a  problem.  The image folder (resource\assets) is not copied into bin\js-debug folder.

The application structure and the used asconfig.json follow.
This example is taken from \apache-royale-0.9.7-bin-js\royale-asjs\examples\royale\DataGridExample.

Did I miss something to set in asconfig.json?

== Application Structure == 

```
DataGridExample
    |-src
    |  |-main
    |     |-resources
    |     |  |-assets
    |     |     |-smallbulerect.jpg
    |     |     |-smallgreenrect.jpg 
    |     |
    |     |-royale
    |        |-models
    |        |  |-ProductsModel.as
    |        |-poducts   
    |        |  |-Products.as
    |        |  |-ProductItemRender.as
    |        |-DataGridExample.mxml
    |        |-MyInitialView.mxml
    |-asconfig.json
```

== asconfig.json ==

```json5
{
    "config": "royale",
    "compilerOptions": {
        "debug": false,
        "targets": ["JSRoyale"],
        "source-map": true
    },
    "additionalOptions": "-remove-circulars -js-output-optimization=skipAsCoercions",
    "files":
    [
        "src/main/royale/DataGridExample.mxml"
    ]
}
```

For your info.  Maven and moonshine both have the special settings to copy image folder into the output.

----------------------------------------------------------------------------------------------------
mvn:
\apache-royale-0.9.7-bin-js\royale-asjs\examples\pom.xml

        
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.1.0</version>
          <executions>
            <execution>
              <id>copy-resources-debug</id>
              <phase>validate</phase>
              <goals>
                <goal>copy-resources</goal>
              </goals>
              <configuration>
                <outputDirectory>${compiler.output-dir-debug}</outputDirectory>
                <resources>
                  <resource>
                    <directory>src/main/resources</directory>
                    <filtering>true</filtering>
                  </resource>
                </resources>
              </configuration>
            </execution>
           </executions>
        </plugin>

moonshine:
  C:\apache-royale-0.9.7-bin-js\royale-asjs\examples\royale\DataGridExample\DataGridExample.as3proj

  <moonshineResourcePaths>
    <class path="src/main/resources/assets"/>
  </moonshineResourcePaths>

Appreciate your help.
S. Takeshita

**Comment by joshtynjala** [comment]
There is an *asconfig.json* field named [`copySourcePathAssets`](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/asconfig.json#copysourcepathassets) that you can use in VSCode. If you set it to true, anything in your project's source path that isn't an *.as* or *.mxml* file will be copied to the output folder.

You will need to add *src/main/resources* to the `source-path` compiler option.

**Comment by T-San001** [comment]
Josh, for me, this option does not work.  resources/assets/*.jpg are not coped. The following is my asconfig.json.  What's wrong?  Appreciate your advice.

{
    "config": "royale",
    "compilerOptions": {
        "debug": true,
        "targets": ["JSRoyale"],
        "source-map": true
    }, 
    "additionalOptions": "-remove-circulars -js-output-optimization=skipAsCoercions",
    "copySourcePathAssets": true,
    "files":
    [
        "src/main/royale/DataGridExample.mxml"
    ]
}

**Comment by joshtynjala** [comment]
You seem to have missed an important detail:

> You will need to add *src/main/resources* to the `source-path` compiler option.

**Comment by T-San001** [comment]
Josh, thanks.  It worked.

The following is the updated asconfig.json.

{
    "config": "royale",
    "compilerOptions": {
        "debug": true,
        "targets": ["JSRoyale"],
        "source-map": true,
        "source-path": [
            "src/main/royale",
            "src/main/resources"
		]
    }, 
    "additionalOptions": "-remove-circulars -js-output-optimization=skipAsCoercions",
    "copySourcePathAssets": true,
    "files":
    [
        "src/main/royale/DataGridExample.mxml"
    ]
}
