### ISSUE TITLE
Debugging is broken in 0.24.* for windows/bundle. Downgrading to 0.23 corrected issues.

### ISSUE THREAD

**Issue by Zageron** [BowlerHatLLC/vscode-as3mxml#430]
I am not sure about the other modes, but if I try to debug this happens;
1) Breakpoint is hit.
2) this: loops infinitely trying to resolve.
3) All watch values are void.
4) No debug commands work. (Continue, step, etc...)

**Comment by joshtynjala** [comment]
Hmmm... it seems that adding a watch values causes some kind of freeze. I can reproduce this issue, but only when I have a watch value defined. Otherwise, it seems to be working correctly.

**Comment by joshtynjala** [comment]
I just released Debugger for SWF v1.0.1, which resolves this issue. You should update ActionScript & MXML to v0.24.0 again too.

**Comment by Zageron** [comment]
Awesome! Can confirm that after updating everything works for me again.
Thanks for the fast response.
