### ISSUE TITLE
Debug / Release Toggle

### ISSUE THREAD

**Issue by HeyDonny** [BowlerHatLLC/vscode-as3mxml#432]
I'm looking at moving from FlashDevelop with just one remaining issue. In FlashDevelop it's possible to use CONFIG::debug as a conditional for Debug / Release. Is there something similar in AS3MXML to be implemented? I have both debug and release options in the launch.json file, so would ideally like to determine which is set on build and respond accordingly.

**Comment by joshtynjala** [comment]
You can use the `define` field in the `compilerOptions` section of _asconfig.json_ for conditional compilation. As of right now,  you'll need to manually change the value of `CONFIG::debug` when you switch between debug and release build tasks. There's no way to do it automatically yet.

I'm working on a new field in _asconfig.json_, named `extends`, that will allow you to reference another _asconfig_ file to use as a base and then tweak some of its values. So, you'll be able to have _asconfig.json_ for debug builds that sets `CONFIG::debug` to `true` and all of your main stuff, but then you can also create _asconfig.release.json_ for release builds that extends _asconfig.json_ and sets `CONFIG::debug` to `false`.

**Comment by HeyDonny** [comment]
Thanks Josh, yes I had looked into the define field. The changes to asconfig sound great. Thanks for all your work.
