### ISSUE TITLE
Use more than one theme in asconfig.json

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-as3mxml#433]
Hi Josh,

in Royale, Jewel themes (far beyond JewelTheme), are composed by three CSS files. 
In maven I provide the three artifacts. Now I'm trying to fix the examples and found that "theme" option inside "compilerOptions" seems is limited to just one only member, while that should be a list.

Maybe I'm missing something and is possible to assign more than one in some way. If not is possible I think that's a bug.

Thanks!

**Comment by joshtynjala** [comment]
Okay, I'll take a look.

**Comment by carlosrovira** [comment]
Many thanks Josh! :)
