### ISSUE TITLE
Add code assist for ignore and emit

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/vscode-as3mxml#436]
I find myself writing `@royaleignorecoercion` and `@royaleemitcoercion` quite a lot.

I would love to be able to right-click on an "as" expression and have VSCode insert `@royaleignorecoercion` or `@royaleemitcoercion` as necessary.

**Comment by joshtynjala** [comment]
Good idea!

**Comment by Harbs** [comment]
🎉
