### ISSUE TITLE
Trying to change SDKs not working properly

### ISSUE THREAD

**Issue by carlosrovira** [BowlerHatLLC/vscode-as3mxml#441]
Hi Josh,

I have current v0.25.0, on Mac.
If I click on the bottom-right sdk zone and try to change the SDK to other folder, VSCode seems to not do anything.
To get the SDK change I need to go to `.vscode` folder and open `settings.json` then modify the code there:

```
{
    "as3mxml.sdk.framework": "/Users/carlosrovira/Dev/Royale/Sdks/apache-royale-maven",
    "as3mxml.sdk.editor": "/Users/carlosrovira/Dev/Royale/Sdks/apache-royale-maven"
}
```

In this way I get proper changes.

Maybe I'm doing something wrong? or something broke lately?

Thanks

**Comment by joshtynjala** [comment]
Unfortunately, I am not able to reproduce this issue.

In the Royale dev list, I suggested that a _.code-workspace_ file takes precedence over _.vscode/settings.json_. Perhaps that's where the settings are being modified instead.

**Comment by carlosrovira** [comment]
Hi Josh, I'm trying now changing from one SDK to another and surprisingly is working. Sorry for the confusion, don't know why yesterday was no way to do this. Thanks!
