### ISSUE TITLE
air-config.xml cannot be opened

### ISSUE THREAD

**Issue by T-San001** [BowlerHatLLC/vscode-as3mxml#443]
When using AIRSDK_Flex_Windows SDK from Harman, MXML and ActionScript extension issues this error against asconfig.json. Actually, this file does not exist in framework folder.  The same error is also issued with Adobe AIR SDK. 

How can I remove this error message?

**Comment by joshtynjala** [comment]
@T-San001 Did you merge AIRSDK_Flex_Windows with a Flex SDK?

**Comment by T-San001** [comment]
Josh, thanks. It seems the merge is required.
