### ISSUE TITLE
Code Snippet: Missing semicolon in 'for' code snippet

### ISSUE THREAD

**Issue by Adolio** [BowlerHatLLC/vscode-as3mxml#445]
Hi Josh,

Just a tiny thing about the `for` code snippet:

![Screen Shot 01-26-20 at 08 59 PM](https://user-images.githubusercontent.com/1126990/73140974-14ab0d00-407f-11ea-8591-7f463c654514.PNG)

Best,
Aurélien

**Comment by joshtynjala** [comment]
Thanks!

**Comment by Adolio** [comment]
Thanks to you!
