### ISSUE TITLE
Completion: MXML components with same namespace as root component should be ordered first in results

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/vscode-as3mxml#449]
If root is `<s:Application>` and both `<mx:Button>` and `<s:Button>` are available, then `<s:Button>` should appear before `<mx:Button>` in the completion list. Normally, it would be in alphabetical order and `mx` would appear before `s`.

This should be especially useful in Royale where there are many component sets.

However, maybe this behavior should have a setting that may be optionally disabled.

**Comment by Harbs** [comment]
👍 This would be very nice.
