### ISSUE TITLE
Code Action: Improve get / set accessors generation based on field visibility & existing prefix

### ISSUE THREAD

**Issue by Adolio** [BowlerHatLLC/vscode-as3mxml#450]
Hi Josh,

I would like to propose a small improvement for the generation of `get` / `set` accessors. 

When I generate them for:
```as3
private var _myNumber:Number = 0;
```

I end up with an extra `_` and the generated methods have a `private` scope:
```as3
private var __myNumber:Number = 0;

private function get _myNumber():Number
{
	return __myNumber;
}

private function set _myNumber(value:Number):void
{
	__myNumber = value;
}
```

But I'm actually expecting this result (as `FlashDevelop` does):
```as3
private var _myNumber:Number = 0;

public function get myNumber():Number
{
	return _myNumber;
}

public function set myNumber(value:Number):void
{
	_myNumber = value;
}
```

---

1) Could you detect if an `_` is already present and don't add an extra one if then? Or add one only if the field is `public`.
2) Could you make the accessors `public` by default or add another action like: `Generate public 'get' and 'set' accessors`?

Thanks in advance,
Aurélien

**Comment by joshtynjala** [comment]
You need to make the variable public. It keeps the same visibility as the original variable.

```
public var myNumber:Number = 0;
```

**Comment by Adolio** [comment]
Thanks @joshtynjala! I'm looking forward to try & use it :)

**Comment by Adolio** [comment]
Well done 👌 Thanks!
