### ISSUE TITLE
Package with gson.ane get Error. Using default implementation...

### ISSUE THREAD

**Issue by tidus2020** [BowlerHatLLC/vscode-as3mxml#455]
> Warning: Using default implementation for native extension 'com.google.code.gson.gson'

Maybe there is no reference of it , but when I use the webviewAne whitch depends on gson, I will get error.

**Comment by joshtynjala** [comment]
Did it work in a different IDE?

**Comment by tidus2020** [comment]
> Did it work in a different IDE?

yes,it worked on flashbuilder

**Comment by joshtynjala** [comment]
Is that the full message that you receive? There are no other details? I'm already inexperienced with ANEs, so it may be difficult for me to improve this situation.

Can you share your asconfig.json file?

**Comment by tidus2020** [comment]
> Is that the full message that you receive? There are no other details? I'm already inexperienced with ANEs, so it may be difficult for me to improve this situation.
> 
> Can you share your asconfig.json file?

Of course.
[tuarua's WebViewANE](https://github.com/tuarua/WebViewANE)

my asconfig.json
`{
    "config": "airmobile",
	"compilerOptions": {
		"source-path": [
			"src"
		],
		"output": "bin/Main.swf"
		,"strict": true
		,"warnings": false
		,"keep-all-type-selectors": true
		,"library-path": [
			"libs"
			,"libs/MyANE.ane"
			,"libs/com.tuarua.frekotlin-1.9.5.ane"
			,"libs/WebViewANE.ane"
		]
	},
	"mainClass": "Main",
    "application": {
		"ios": "src/Main-app.xml",
		"android": "src/Main-app.xml",
		"windows": "src/Main-app.xml",
		"mac": "src/Main-app.xml"
    },
	"airOptions": {
		"android": {
			"output": "bin/Main.apk",
			"signingOptions": {
				"storetype": "pkcs12",
				"keystore": "E:\\Works\\Tidus1.p12"
            }
            ,"arch": "armv8"
		}

        ,"files": [
            {
                "file": "E:\\Test\\AppIconsForPublish/128.png",
                "path": "AppIconsForPublish/128.png"
            }
            ,{
                "file": "src/assets/",
                "path": "assets/"
			}
        ]

        ,"extdir": [
			"libs"
		]
    }
}
`

**Comment by joshtynjala** [comment]
I am unable to reproduce this issue. When I run the "Adobe AIR: package Android release - asconfig.json" task, the app packages successfully with no error messages.

One difference that I noticed is that I have com.google.code.gson.gson version 2.8.6, and you have version 2.8.4. It might be worth trying to update your dependencies.

Here is how I specified the extensions in my AIR application descriptor, as described by the WebViewANE documentation.

```xml
<extensions>
    <extensionID>com.tuarua.WebViewANE</extensionID>
    <extensionID>com.tuarua.frekotlin</extensionID>
    <extensionID>com.google.code.gson.gson</extensionID>
</extensions>
```

Which version of the AIR SDK are you using? I happened to test with AIR 33.0.2.246. There could be an issue if you are trying to use AIR 32 or 33.1, I guess.

**Comment by tidus2020** [comment]
> I am unable to reproduce this issue. When I run the "Adobe AIR: package Android release - asconfig.json" task, the app packages successfully with no error messages.
> 
> One difference that I noticed is that I have com.google.code.gson.gson version 2.8.6, and you have version 2.8.4. It might be worth trying to update your dependencies.
> 
> Here is how I specified the extensions in my AIR application descriptor, as described by the WebViewANE documentation.
> 
> ```
> <extensions>
>     <extensionID>com.tuarua.WebViewANE</extensionID>
>     <extensionID>com.tuarua.frekotlin</extensionID>
>     <extensionID>com.google.code.gson.gson</extensionID>
> </extensions>
> ```
> 
> Which version of the AIR SDK are you using? I happened to test with AIR 33.0.2.246. There could be an issue if you are trying to use AIR 32 or 33.1, I guess.

Yes ! I update everyThing to the lastest version and it workd fine ! 
Thanks ! (*^__^*)
