### ISSUE TITLE
Support for relative SDK path.

### ISSUE THREAD

**Issue by Zageron** [BowlerHatLLC/vscode-as3mxml#463]
Could you please add support for relative SDK pathing?
There's a huge thread about it on vscode.
https://github.com/microsoft/vscode/issues/2809

But it looks like it is up to each developer to implement.

**Comment by joshtynjala** [comment]
Relative to what exactly? The workspace? Something else?

**Comment by Zageron** [comment]
Workspace, user folder, home, and appdata, would be nice for a start.

And additionally, if not already, accepting Unix paths and converting to windows if necessary within the extension.

**Comment by Zageron** [comment]
Just interpreting an environment variable for the relative path would be very appreciated.

**Comment by joshtynjala** [comment]
Interpreting environment variables sounds like something that VSCode should be doing, and not each extension coming up with its own separate (probably somewhat buggy) implementation. I'll leave this for Microsoft to handle. microsoft/vscode#2809 is still open, so I assume that it's under consideration and they have not rejected this as a possible future feature.
