### ISSUE TITLE
"error 301: Application descriptor missing/cannot be opened" when packaging desktop release (shared runtime)

### ISSUE THREAD

**Issue by tidus2020** [BowlerHatLLC/vscode-as3mxml#464]
> error 301: Application descriptor missing/cannot be opened

asconfig.json

```json
{
	"compilerOptions": {
		"output": "bin-debug/ExcelReadtoJson.swf",
		"source-path": [
			"src"
		],
		"warnings": false
	},
	"mainClass": "ExcelReadtoJson",
	"application": "src/ExcelReadtoJson-app.xml",
	"copySourcePathAssets": true,
	"additionalOptions": "-locale en_US",
	"airOptions": {
		"output": "bin-debug/Main.air",
		"signingOptions": {
			"storetype": "pkcs12",
			"keystore": "Tidus1.p12"
		}
	},
	"config": "air"
}
```

when package to desktop released(shared runtime) will got this error. Of course the ExcelReadtoJson-app.xml is there.

**Comment by joshtynjala** [comment]
Does ExcelReadtoJson-app.xml exist in both src and bin-debug?

**Comment by tidus2020** [comment]
> Does ExcelReadtoJson-app.xml exist in both src and bin-debug? I'm just checking that it was properly copied to the output folder during compilation.

Yes,both there . I try to change the 'filename' and 'name' in the xml to pure English words, because I found some chinese word in it will get this error too, but dosen't work..

**Comment by joshtynjala** [comment]
Can you create and a simple project that reproduces this issue and attach it here?

**Comment by tidus2020** [comment]
Σ(⊙▽⊙"ha....I found it . I have a chinese word in the xml's annotation...delete it and every thing is ok.

> <android>
        <manifestAdditions><![CDATA[
        <manifest android:installLocation="auto">
                
                <uses-permission android:name="android.permission.INTERNET"/>

**Comment by danielkotzer** [comment]
I have the same problem, but can't find any Chinese word.

**Comment by joshtynjala** [comment]
> error 301: Application descriptor missing/cannot be opened

@danielkotzer This is an error from Adobe AIR's adt command. I doubt it's a vscode-as3mxml issue.

You either have a wrong path somewhere, or maybe you have a different invalid Unicode character in the AIR descriptor file. It doesn't necessarily need to be a Chinese character specifically. Maybe emoji or other languages cause the same issue.

To help with debugging, you might want to set `as3mxml.asconfigc.verboseOutput` to `true` in settings. If you run the build after that, you'll see the full adt command, which might give you a clue if any paths are wrong.
