### ISSUE TITLE
I get "unable to open" errors intermitantly.

### ISSUE THREAD

**Issue by Zageron** [BowlerHatLLC/vscode-as3mxml#466]
``` bash
d:\a\ffrGameMigration\ffrGameMigration\airsdk\frameworks\flex-config.xml:47
Error: unable to open 'd:\a\ffrGameMigration\ffrGameMigration\airsdk\frameworks\libs\player\11.1\playerglobal.swc'.
d:\a\ffrGameMigration\ffrGameMigration\airsdk\frameworks\flex-config.xml (line: 47)
        </external-library-path>
```

This is okay locally, I can just run the build again which takes at worst 10 seconds.
But in automation this is very frustrating as I have to run the entire pipeline again.

To be clear, the error is not consistent.

**Comment by joshtynjala** [comment]
This is a bug in the AIR SDK's comiler. Open _frameworks/flex-config.xml_ from your SDK in a text editor, and look for this line:

```xml
<path-element>libs/player/{targetPlayerMajorVersion}.{targetPlayerMinorVersion}/playerglobal.swc</path-element>
```

Change `{targetPlayerMajorVersion}.{targetPlayerMinorVersion}` to the version of your SDK. For example, if you are using AIR SDK 32, you would change it to `32.0`.

```xml
<path-element>libs/player/32.0/playerglobal.swc</path-element>
```
