### ISSUE TITLE
please help!! The editor code cannot be highlighted. and no writing prompt(tips)

### ISSUE THREAD

**Issue by tooun** [BowlerHatLLC/vscode-as3mxml#468]
![Untitled-CSADSA1](https://user-images.githubusercontent.com/63945825/79681455-f5221b80-824c-11ea-9127-12bf714a7467.jpg)

**I'm sorry to bother you!!!,**
I have installed ActionScript & MXML, and I have installed Adobe AN 2019,,
when I Create an AS3 file,,why there is no code prompt?
I tried to follow [getting started] in Wiki step by step, but there was no code prompt or highlight.. Can you tell me what's wrong

my setting::
![QQ截图20200419145213](https://user-images.githubusercontent.com/63945825/79681797-901bf500-824f-11ea-8153-40b90f93527f.jpg)

**Comment by joshtynjala** [comment]
@tooun Does your workspace folder contain an _asconfig.json_ file at the root?

**Comment by tooun** [comment]
@joshtynjala     this my asconfig.json
![QQ截图20200421104536](https://user-images.githubusercontent.com/63945825/79819853-7993ac00-83bd-11ea-92a9-adb771a8e75c.jpg)

and When I start vs code, it will prompt the following information
![QQ截图20200421104449](https://user-images.githubusercontent.com/63945825/79819919-9f20b580-83bd-11ea-844b-178e4871389f.jpg)

**Comment by joshtynjala** [comment]
Most developers don't need to use the `as3mxml.sdk.editor` setting. It is an advanced setting that is generally only needed when using nightly builds Apache Royale. Because you are not using Apache Royale, you should clear this setting.

**Comment by tooun** [comment]
very thank you ,I delete the [as3mxml.sdk.editor]  ,it 's work
writing prompt(tips) has work,
but code no color,.It doesn't matter

**Comment by joshtynjala** [comment]
I think that you can change to a different color theme. Some themes have more colors than others.
