### ISSUE TITLE
New line indents / formatting

### ISSUE THREAD

**Issue by mawyju** [BowlerHatLLC/vscode-as3mxml#473]
Hi there.

First of all, thanks for the amazing extension, which we really love as an alternative for the ever-buggy FlashDevelop for our as3 projects.

We do suffer from a big bug, for which I'm unsure whether is fixable through your extension, or is VS Code related altogether.

The indents for new lines are not respected to be in class-level indentaton. That is, new line after a method or field/variable will always be positioned on location 0, instead of 2 tab indents in, on the level where all fields and methods live.

This causes many false-positive conflicts and file-changes when file is formatted in Vs Code versus FlashDevelop or Notepad++ for that matter.

It would be extremely helpful to have this fixed. Looking forward to at least a feedback, if this cannot be solved on extension level.

Thanks, Marko

**Comment by joshtynjala** [comment]
Adding indentation when inserting new lines is definitely a behavior that is controlled by VSCode, and not by the extension.

However, what's strange is that I cannot reproduce the issue that you describe.

To test, I loaded the following ActionScript class in VSCode:

```as3
package
{
	import flash.display.Sprite;

	public class HelloWorld extends Sprite
	{
		public function HelloWorld()
		{
		}
	}
}
```

If I place the cursor after the constructor's `}` character, and I press the enter key to insert a new line, the new line is intended by two tabs. If I convert the file to spaces instead of tabs, it inserts the appropriate number of spaces instead.

**Comment by mawyju** [comment]
Hi, Josh. Thanks for looking into this and replying so rapidly!

I see now that I completely forgot to mention and add the core - important part of the issue! I apologize for that!

The indent issue appears when doing "Refactor" command, causing all lines (even empty lines in between the empty method, if you'd add an empty line inside your "HelloWorld()" method).

Also, what's working even strangely and sporadicaly is, pressing Ctrl+S / Saving the document, seems to remove indents on empty lines above the current cursor. That is, making 3 new lines after a method, all keep indents. Saving the file causes the first two lines to lose indent.

I hope this is easier to understand and reproduce now. Once again, apologizes for missing the important bit in the original post!

Best regards, Marko

**Comment by mawyju** [comment]
Edit: (edit button doesnt work for some reason on Edge browser...)

The latest seems to not be affected by save, but new lines in general. After every newline added it seems that previous ones lose indents...

**Comment by joshtynjala** [comment]
> After every newline added it seems that previous ones lose indents...

Yes, I see this behavior too. That's definitely controlled by VSCode. You should check to see if there is a setting that tells VSCode to preserve indentation on empty lines. Microsoft is pretty good about making little things like that configurable.
