### ISSUE TITLE
Adobe Animate project no build task because Animate not found

### ISSUE THREAD

**Issue by varadig** [BowlerHatLLC/vscode-as3mxml#474]
I follow [this](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Create-a-new-Adobe-Animate-project-in-Visual-Studio-Code) instruction, but I can't see any of build task.

I use Adobe Animate 2020.

[VIDEO](https://youtu.be/qkjb-AcG-Jo)

**Comment by joshtynjala** [comment]
@varadig What is the absolute file path of Adobe Animate's executable on your computer? It's possible that vscode-as3mxml is not finding the executable, for some reason.

**Comment by varadig** [comment]
/Volumes/Data/Applications/Adobe\ Animate\ 2020/Adobe\ Animate\ 2020.app

I installed another volume (not the system) because of low disk space

**Comment by varadig** [comment]
Where can I setup the path of the executable?

**Comment by joshtynjala** [comment]
Okay, thanks. I was right that it is unable to find Animate. Currently, there is no way to override the path to Animate. I'll try to fit that into a future update.

**Comment by varadig** [comment]
Thanks @joshtynjala ! 
Right now, I reinstall the Animate to the /Volumes/System/Application folder
