### ISSUE TITLE
Code Action: Import not placed at the "right" (organized) position

### ISSUE THREAD

**Issue by Adolio** [BowlerHatLLC/vscode-as3mxml#483]
Hi Josh,

That's just a minor usability thing... It would be nice if the add import through code action add the new import at the proper (ordered) position (same as the `Organize imports` command).

Or maybe it could automatically trigger `Organize imports` - this might not be adequate for all users.

Best,
Aurélien

**Comment by Adolio** [comment]
Hi back Josh,

Any plan to implement this usability improvement?

It would really be appreciated on my side. Thanks

**Comment by joshtynjala** [comment]
If you add the following to your workspace settings, it will automatically organize imports when you save a file. Works for any language, not just AS3/MXML.

```json
"editor.codeActionsOnSave": {
  "source.organizeImports": true
}
```

**Comment by Adolio** [comment]
Your proposition looks fine for me 😀

Unfortunately I need #485 before doing that. 😕

**Comment by Adolio** [comment]
This is now making my coding life much easier.. 🥲 (that's a tear of joy)

Again, thanks a lot Josh!
