### ISSUE TITLE
Adobe AIR code signing

### ISSUE THREAD

**Issue by zabdoul60460** [BowlerHatLLC/vscode-as3mxml#486]
Hi,
When I try to create an Adobe air package windows release this error appear 'unable to load a certificate in this file' after typing my password.
Please could you help to solve that ?
Best regards.

**Comment by joshtynjala** [comment]
See the official [Adobe AIR: ADT Signing Options documentation](https://help.adobe.com/en_US/air/build/WS5b3ccc516d4fbf351e63e3d118666ade46-7f72.html) for details.

In most cases, your asconfig.json file should look very similar to this, except that the path to the certificate file will be different:

```
"signingOptions": {
	"keystore": "path/to/certificate.p12",
	"storetype": "pkcs12"
}
```

**Comment by zabdoul60460** [comment]
My certificate was created with Flashbuilder.
My asconfig.json file is like that for airOptions 
`"airOptions": {
		"windows": {
			"target": "native",
			"output": "bin/MainOE.exe",
			"signingOptions": {
				"storetype": "pkcs12",
				"keystore": "src/VSCertificat.p12"
			}
		},
		"mac": {
			"target": "native",
			"output": "bin/MainOE.dmg",
			"signingOptions": {
				"storetype": "pkcs12",
				"keystore": "src/VSCertificat.p12"
			}
		}
	}`
My certificat is on src folder.
So I don't understand why it doesn't works.
Best regards.

**Comment by joshtynjala** [comment]
Apparently, one of the reasons this error message can be displayed is if you have a certificate that is 1024-bit RSA instead of 2048-bit RSA. Newer versions of Java will not accept the 1024-bit RSA certificates anymore. Perhaps you chose 1024 when you created the certificate in Flash Builder.

**Comment by zabdoul60460** [comment]
Thanks for your help.
Indeed if the certificate is 2048-bit RSA it works (for password).
But a new error appear : 'The terminal process terminated with exit code: 5'.
Do you know why ?
Many thanks in advance.

**Comment by zabdoul60460** [comment]
See below all errors messages :
`
unexpected failure: null
java.lang.NullPointerException
        at com.adobe.ucf.Packager.addFileOrDir(Packager.java:295)
        at com.adobe.ucf.Packager.addSourceFileOrDir(Packager.java:246)
        at com.adobe.air.nai.NativePackager.addSourceFileOrDir(NativePackager.java:311)
        at com.adobe.air.ADT.parseFileAndPathArguments(ADT.java:1871)
        at com.adobe.air.ADT.parseDescriptorAndFileset(ADT.java:1906)
        at com.adobe.air.ADT.parseInput(ADT.java:1173)
        at com.adobe.air.ADT.parsePackage(ADT.java:819)
        at com.adobe.air.ADT.parseArgsAndGo(ADT.java:695)
        at com.adobe.air.ADT.run(ADT.java:485)
        at com.adobe.air.ADT.main(ADT.java:535)
`

**Comment by joshtynjala** [comment]
[This document](https://helpx.adobe.com/air/kb/air-developer-tool-adt-error.html#main__Exit_Codes_) says "Unknown error". That makes sense for a null pointer exception like that. It's a bug in the ADT packaging tool.

Based on the stack trace, it seems like something is wrong with one of the files that you are including in the packaged app. Maybe the path is wrong or something. Hard to say without seeing your asconfig.json file.

**Comment by zabdoul60460** [comment]
Thanks for your reply.
Find below my asconfig.json file

`
{
	"config": "air",
	"compilerOptions": {
		"source-path": [
			"src"
		],
		"output": "bin/Main.swf"
	},
	"mainClass": "Main",
	"application": "src/Main-app.xml",
	"airOptions": {
		"windows": {
			"target": "native",
			"output": "bin/MainOE.exe",
			"signingOptions": {
				"storetype": "pkcs12",
				"keystore": "src/VSCertificat2048.p12"
			}
		},
		"mac": {
			"target": "native",
			"output": "bin/MainOE.dmg",
			"signingOptions": {
				"storetype": "pkcs12",
				"keystore": "src/VSCertificat2048.p12"
			}
		}
	}
}
`

**Comment by joshtynjala** [comment]
Hmm... so no files should be included except for your SWF and XML application descriptor. Do both Main-app.xml and Main.swf exist in your bin folder?

Which version of the AIR SDK are you using?

**Comment by zabdoul60460** [comment]
Yes both exist in my bin folder.
I use AIR Sdk 32.0.0.116.
Best regards

**Comment by zabdoul60460** [comment]
Before I work with Flash Buider 4.6.
Today my goal is to try to import my Flash Builder projet using your extension.
To begin, I test it with a very basic project, your sample !
Best regards

**Comment by joshtynjala** [comment]
In your VSCode settings, please set `as3mxml.asconfigc.verboseOutput` to `true. Then, try to build your project again and copy the full output here. Thanks!

**Comment by joshtynjala** [comment]
The full output may contain your certificate password, so please make sure to replace that with *** or something before you submit your comment.

**Comment by zabdoul60460** [comment]
Find below output log.

`
> Executing task: C:\Program Files\Java\jre1.8.0_251\bin\java.exe -jar c:\Users\clinicbz\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.2.1\bin\asconfigc.jar --sdk \\Mac\Home\Documents\VisualStudio\SDK_Air --debug=true --project \\Mac\Home\Documents\VisualStudio\DemoAir\asconfig.json --air windows --verbose=true <

Configuration file: \\Mac\Home\Documents\VisualStudio\DemoAir\asconfig.json
Reading configuration file...
Validating configuration file...
Parsing configuration file...
SDK: \\Mac\Home\Documents\VisualStudio\SDK_Air
Compiling application...
C:\Program Files\Java\jre1.8.0_251\bin\java -Dflexcompiler=\\Mac\Home\Documents\VisualStudio\SDK_Air -Dflexlib=\\Mac\Home\Documents\VisualStudio\SDK_Air\frameworks -jar \\Mac\Home\Documents\VisualStudio\SDK_Air\lib\mxmlc-cli.jar +flexlib=\\Mac\Home\Documents\VisualStudio\SDK_Air\frameworks
--debug=true +configname=air --source-path+=src --output=bin/Main.swf -- src\Main.as
Chargement de la configuration : \\Mac\Home\Documents\VisualStudio\SDK_Air\frameworks\air-config.xml

689 octets écrits dans \\Mac\Home\Documents\VisualStudio\DemoAir\bin\Main.swf en 2,380 secondes
Processing Adobe AIR application descriptor(s)...
Initial window content: Main.swf
Descriptor: \\Mac\Home\Documents\VisualStudio\DemoAir\src\Main-app.xml
Packaging Adobe AIR application...
Adobe AIR code signing password:
C:\Program Files\Java\jre1.8.0_251\bin\java -jar \\Mac\Home\Documents\VisualStudio\SDK_Air\lib\adt.jar -package -storetype pkcs12 -keystore src/VSCertificat2048.p12 -storepass xxxxxx -target native bin/MainOE.exe \\Mac\Home\Documents\VisualStudio\DemoAir\bin\Main-app.xml -C \\Mac\Home\Documents\VisualStudio\DemoAir\bin Main.swf
unexpected failure: null
java.lang.NullPointerException
        at com.adobe.ucf.Packager.addFileOrDir(Packager.java:295)
        at com.adobe.ucf.Packager.addSourceFileOrDir(Packager.java:246)
        at com.adobe.air.nai.NativePackager.addSourceFileOrDir(NativePackager.java:311)
        at com.adobe.air.ADT.parseFileAndPathArguments(ADT.java:1871)
        at com.adobe.air.ADT.parseDescriptorAndFileset(ADT.java:1906)
        at com.adobe.air.ADT.parseInput(ADT.java:1173)
        at com.adobe.air.ADT.parsePackage(ADT.java:819)
        at com.adobe.air.ADT.parseArgsAndGo(ADT.java:695)
        at com.adobe.air.ADT.run(ADT.java:485)
        at com.adobe.air.ADT.main(ADT.java:535)
The terminal process terminated with exit code: 5

Terminal will be reused by tasks, press any key to close it.

`

**Comment by joshtynjala** [comment]
Why does it seem to be mixing paths for different types of operating systems?

This seems like a Windows path:

> C:\Program Files\Java\jre1.8.0_251\bin\java

And this seems like a macOS or Linux path:

> \Mac\Home\Documents\VisualStudio\SDK_Air\lib\adt.jar

**Comment by zabdoul60460** [comment]
I work with a Windows 7 VM. It's explain windows path for java.
My root is on 'Document Folder' but in Parallels, this is sharing with Mac OS.
I try to move my project on c:/ but I have the same error !

**Comment by joshtynjala** [comment]
>  I try to move my project on c:/ but I have the same error !

I'll need to see the full build output again.

**Comment by zabdoul60460** [comment]
Now the project is on C:/ root.

`
> Executing task: C:\Program Files\Java\jre1.8.0_251\bin\java.exe -jar c:\Users\clinicbz\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.2.1\bin\asconfigc.jar --sdk \\Mac\Home\Documents\VisualStudio\SDK_Air --debug=false --project c:\VisualStudioRoot\DemoAir\asconfig.json --air windows --verbose=true <

Configuration file: c:\VisualStudioRoot\DemoAir\asconfig.json
Reading configuration file...
Validating configuration file...
Parsing configuration file...
SDK: \\Mac\Home\Documents\VisualStudio\SDK_Air
Compiling application...
C:\Program Files\Java\jre1.8.0_251\bin\java -Dflexcompiler=\\Mac\Home\Documents\VisualStudio\SDK_Air -Dflexlib=\\Mac\Home\Documents\VisualStudio\SDK_Air\frameworks -jar \\Mac\Home\Documents\VisualStudio\SDK_Air\lib\mxmlc-cli.jar +flexlib=\\Mac\Home\Documents\VisualStudio\SDK_Air\frameworks
--debug=false +configname=air --source-path+=src --output=bin/Main.swf -- src\Main.as
Chargement de la configuration : \\Mac\Home\Documents\VisualStudio\SDK_Air\frameworks\air-config.xml

559 octets écrits dans C:\VisualStudioRoot\DemoAir\bin\Main.swf en 1,822 secondes
Processing Adobe AIR application descriptor(s)...
Initial window content: Main.swf
Descriptor: c:\VisualStudioRoot\DemoAir\src\Main-app.xml
Packaging Adobe AIR application...
Adobe AIR code signing password:
C:\Program Files\Java\jre1.8.0_251\bin\java -jar \\Mac\Home\Documents\VisualStudio\SDK_Air\lib\adt.jar -package -storetype pkcs12 -keystore src/VSCertificat2048.p12 -storepass xxxxx -target native bin/MainOE.exe c:\VisualStudioRoot\DemoAir\bin\Main-app.xml -C c:\VisualStudioRoot\DemoAir\bin Main.swf
unexpected failure: failed to get jar directory
java.io.IOException: failed to get jar directory
        at com.adobe.air.Utils.getSDKLibDir(Utils.java:60)
        at com.adobe.air.nai.NativePackager.getNAISDKBinDir(NativePackager.java:271)
        at com.adobe.air.nai.NativePackager.invokePlatformConversion(NativePackager.java:208)
        at com.adobe.air.nai.NativePackager.createPackage(NativePackager.java:133)
        at com.adobe.air.ADT.parseArgsAndGo(ADT.java:696)
        at com.adobe.air.ADT.run(ADT.java:485)
        at com.adobe.air.ADT.main(ADT.java:535)
The terminal process terminated with exit code: 5

Terminal will be reused by tasks, press any key to close it.

`

**Comment by joshtynjala** [comment]
I can see from your output that `\Mac\Home\` paths are still being used. This is why it is failing. It should not contain any macOS paths.

You need to update your `as3mxml.sdk.framework` setting to point to a path on the Windows c:\ drive too.

**Comment by zabdoul60460** [comment]
I found the solution.
I move air SDK on c:/ too and now it work well.
Many thanks for your help

**Comment by joshtynjala** [comment]
You're welcome!
