### ISSUE TITLE
Compile failed: unknown DCD_LIB_LOCATION token

### ISSUE THREAD

**Issue by zabdoul60460** [BowlerHatLLC/vscode-as3mxml#489]
Hi,
I imported a new flash builder projet (air project) inside visual studio code.
I try to buis this project (Terminal/run build task / Actionscript compile debug).
But this error appear
```
command line
Erreur : la valeur de la variable de configuration compiler.library-path contient le jeton inconnu DCD_LIB_LOCATION.
The terminal process terminated with exit code: 4

```

Could you help me to solve that.

Best regards

**Comment by joshtynjala** [comment]
Just putting the translation to English here:

> Error: The value of the configuration variable compiler.library-path contains the unknown DCD_LIB_LOCATION token.

**Comment by joshtynjala** [comment]
In your project's _asconfig.json_ file, there is an invalid value in the library-path compiler option. It seems that you defined some kind of special DCD_LIB_LOCATION variable/token in your Flash Builder workspace settings. However, these special tokens are not translated into VSCode projects. You'll need to replace DCD_LIB_LOCATION with the real path.

**Comment by zabdoul60460** [comment]
thanks for your help it works.
