### ISSUE TITLE
Option to disable asconfig auto-creation for multiple folders

### ISSUE THREAD

**Issue by jnpatrick99** [BowlerHatLLC/vscode-as3mxml#492]
We have a huge project with multiple folders in VS Code. as3mxml requires every folder to have an `asconfig.json` file, but we don't need that (the biggest problem is that we have around 100 compiler definitions that change all the time, and it's hard to keep track of those around all folders). 

Is there a way to disable "Import Existing ActionScript & MXML projects..." dialog that pops up every time the workspace is open? If I click "Import" then multiple `asconfig.json` are being created. And also if I click close on that dialog, then it's created too. But disabling this dialog altogether would be really nice, thank you!

**Comment by joshtynjala** [comment]
Set the `as3mxml.projectImport.prompt` setting to `false`.

I see that this was undocumented, so I just added it to the documentation now.
