### ISSUE TITLE
MXML: CTRL+Space Import in <fx:Script> block sometimes places import on very top of file

### ISSUE THREAD

**Issue by brianraymes** [BowlerHatLLC/vscode-as3mxml#499]
When working within a Script block within an mxml file, CTRL+Space for completion/import sometimes places the import outside of the script block as the very first line of the file.

**Steps to reproduce**

1. _Create an mxml file with a Script block:_

```
<?xml version="1.0" encoding="utf-8"?>
<j:VGroup xmlns:fx="http://ns.adobe.com/mxml/2009"
    xmlns:j="library://ns.apache.org/royale/jewel"
    xmlns:js="library://ns.apache.org/royale/basic"
    xmlns:html="library://ns.apache.org/royale/html">

    <fx:Script>
        <![CDATA[
            
        ]]>
    </fx:Script>

</j:VGroup>
```

2. _Add some code that will allow auto complete_

```
<?xml version="1.0" encoding="utf-8"?>
<j:VGroup xmlns:fx="http://ns.adobe.com/mxml/2009"
    xmlns:j="library://ns.apache.org/royale/jewel"
    xmlns:js="library://ns.apache.org/royale/basic"
    xmlns:html="library://ns.apache.org/royale/html">

    <fx:Script>
        <![CDATA[
             private var test:RemoteOb
        ]]>
    </fx:Script>

</j:VGroup>
```

3. _Use CTRL+Space to auto complete_

4. _Sometimes, the import will appear at the very top of the file_

**Expected Results**

The import appears at the top of the Script block:

```
<?xml version="1.0" encoding="utf-8"?>
<j:VGroup xmlns:fx="http://ns.adobe.com/mxml/2009"
    xmlns:j="library://ns.apache.org/royale/jewel"
    xmlns:js="library://ns.apache.org/royale/basic"
    xmlns:html="library://ns.apache.org/royale/html">

    <fx:Script>
        <![CDATA[
             import org.apache.royale.net.RemoteObject;

             private var test:RemoteObject;
        ]]>
    </fx:Script>

</j:VGroup>
```

**Actual Results**

```
import org.apache.royale.net.RemoteObject;

<?xml version="1.0" encoding="utf-8"?>
<j:VGroup xmlns:fx="http://ns.adobe.com/mxml/2009"
    xmlns:j="library://ns.apache.org/royale/jewel"
    xmlns:js="library://ns.apache.org/royale/basic"
    xmlns:html="library://ns.apache.org/royale/html">

    <fx:Script>
        <![CDATA[
             private var test:RemoteObject;
        ]]>
    </fx:Script>

</j:VGroup>
```

**Observations**

I wish I had concrete steps on how to reproduce this issue; it is quite random/sporadic. I will add notes as I learn more.

It is possible that it may be tied to other features within VSCode like auto organize imports, or auto source formatting. I use Beautify for mxml, and ActionScript Tools for AS3. I have sometimes seen worse corruption after saving once this occurs as the imports are usually considerably off the viewable screen.

**Comment by brianraymes** [comment]
Update: I've just noticed that it happens quite often when pasting in code from another file. Possibly more so than from auto-completion.

**Comment by joshtynjala** [comment]
Do you have something enabled in VSCode where it organizes imports on paste? There is no reason why it would add an import during paste, unless maybe something like that were enabled.

**Comment by brianraymes** [comment]
I currently do not have any auto formatting turned on for pasting. Only saving. I will keep monitoring to attempt to track down a reproducible steps.

**Comment by joshtynjala** [comment]
Thanks! Hoping that you can find a way to reproduce consistently.

**Comment by joshtynjala** [comment]
Do you ever try to use `<fx:Script>` elements without `<![CDATA[`, like this?

```
<fx:Script>
 private var test:RemoteOb
</fx:Script>
```

While trying to reproduce, I saw that this is one case where imports are incorrectly added to the beginning of the file.

**Comment by brianraymes** [comment]
Sorry for the late reply. I do not believe I was doing that. I think I noticed it mostly after pasting and/or importing unknowns post paste, but, it is definitely possible what you reproduced is related.

I was able to verify that the case you found does exactly what I was describing.

I've been pulled into many projects lately and haven't had the time to reproduce. Feel free to do what you need with this task as far as using what you found, or closing it until I can find better steps.

**Comment by brianraymes** [comment]
Noticed this happening again today. Here was the scenario:

My mxml file contained the following:

```
    <fx:Script>
        <![CDATA[

        ]]>
    </fx:Script>
```

I pasted the following inside the CDATA block, which did not auto-import.

```
    [Bindable]
    public var menu:IVRMenu;
```

Which resulted in this:

```
    <fx:Script>
        <![CDATA[
            [Bindable]
            public var menu:IVRMenu;
        ]]>
    </fx:Script>
```

I went to the end of `IVRMenu` and hit ctrl+space, and the import appeared at the top of the file, not within the Script's CDATA block.

Hope this helps. I've seen this a few times lately, but usually notice it later as I'm further down within a file.

**Comment by brianraymes** [comment]
Hi Josh, I finally have one variant of this bug caught on video. In this case, It is happening due to "Organizing Imports" when saving. If I disable that flag in my workspace, it stops doing it.

https://user-images.githubusercontent.com/453805/123493313-e6fa2880-d5d0-11eb-9569-896769da3412.mp4

Ctrl+Space is putting it in the correct location. If I didn't catch the first issue, then pressing Ctrl+Space to add it, saving is what casues the worst of the issue, wiping everything between the two:

https://user-images.githubusercontent.com/453805/123493550-9d5e0d80-d5d1-11eb-95b1-0a450177a0bb.mp4

These settings in my workspace are likely relevant:

```
"editor.formatOnSave": true,
"editor.codeActionsOnSave": {
    "source.organizeImports": true,
    "source.fixAll": true
}
```

The combination of these two issues may be why I was confused as to what and or how it was happening.

Hope this helps!

**Comment by joshtynjala** [comment]
Thanks! I'll take a look soon.

**Comment by joshtynjala** [comment]
@brianraymes Thank you again! I can finally reproduce. It seems to happen when a missing import gets added automatically, but there were no existing imports in the `<fx:Script>` block beforehand.

**Comment by brianraymes** [comment]
Awesome!!

Potentially related or unrelated, I've been seeing issues where if I cut/copy/move code, not entirely certain what order of operations, but all imports used within MXML controls (not used within a script block) are deleted and I have to reimport them.

**Comment by joshtynjala** [comment]
If you're interested in trying it out before I do the next release, feel free to try a nightly build.

https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Nightly-builds
