### ISSUE TITLE
Specifying different config constants from different tasks

### ISSUE THREAD

**Issue by atmofunk** [BowlerHatLLC/vscode-as3mxml#500]
I'd like to set two dif tasks such that triggering each one compiles my project with its own config constants.  For example, two dif builds -- one with logging, the other without.   Right now it only looks like i can go in to asconfig.json and change them manually before running each task.    Is there a way to do this "automatically" ?

My apologies if this is documented somewhere!

**Comment by joshtynjala** [comment]
Using the [`extends`](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/asconfig.json#extends) field, you can use one asconfig.json file as a template and change only the options that you need. Here's an example:

https://gist.github.com/joshtynjala/2ef852272dc25c73502ce408a96ec3de

In your case, you might have asconfig.json and asconfig.logging.json or something like that. VSCode will detect asconfig.logging.json and provide a separate set of tasks.

**Comment by atmofunk** [comment]
Ok this is amazing - ty Josh!  It's exactly what I needed _and_ opens doors I didnt realize needed opening.  cheers!
