### ISSUE TITLE
Loading configuration file C:\air_29\frameworks\air-config.xml Error: null

### ISSUE THREAD

**Issue by cgascons** [BowlerHatLLC/vscode-as3mxml#504]
I'm having issues when compiling my project using a java version higher than 1.8.0.112. Note that this only seems to happen with my project, I have created test projects with just a hello world trace and _vscode_ compiles just fine. I have been attempting to disable library by library all components being used to find the guilty one and I can't seem to find it.

The project itself uses quite a lot of libraries (99% of them referenced by their `/src` folder instead of pointing to a `.swc` file), these libraries are: 

Starling
Feathers
Gamesparks
Greensock's AS3

And a few ANE's as well.

When attempting to compile this error prompts:

```
Executing task in folder Test: C:\Program Files\Java\jre1.8.0_261\bin\java.exe -jar c:\Users\fs\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.3.0\bin\asconfigc.jar --sdk c:\air_29 --debug=true --project c:\Users\fs\workspaceAIR\Test\asconfig.json --unpackage-anes=true <

Loading configuration file C:\air_29\frameworks\air-config.xml
Error: null

The terminal process "C:\Program Files\Java\jre1.8.0_261\bin\java.exe '-jar', 'c:\Users\fs\.vscode\extensions\bowlerhatllc.vscode-nextgenas-1.3.0\bin\asconfigc.jar', '--sdk', 'c:\air_29', '--debug=true', '--project', 'c:\Users\fs\workspaceAIR\Test\asconfig.json', '--unpackage-anes=true'" terminated with exit code: 1.
```

When compiling with the version we normally use (1.8.0.122) the error is gone and compiles fine (but then another old issue arises which is why we are attempting to change the java version in the first place, the error by the way is one we used to have a long time ago and apparently got it fixed by shortening the paths, which isn't working for us now https://github.com/BowlerHatLLC/vscode-as3mxml/issues/388). 

Will keep trying, but I'd appreciate if you could shed some light here, cheers

**Comment by cgascons** [comment]
Hi again, I managed to isolate the issue, it looks like it's related to the Feather's themes which comes in handy since you happen to be the creator of the plugin as well :)

I'm attaching [here](https://github.com/BowlerHatLLC/vscode-as3mxml/files/5372130/Test.zip) the test project that fails when compiling, these are the repro steps:

1. Get on a windows PC
2. Install java 1.8.0.122
3. Uncompress the test project anywhere
4. Open it on vscode
5. Select SDK (we tried with 29 and 30, both fail)
6. Attempt to compile

Hope this info helps

**Comment by joshtynjala** [comment]
I see the following error with Java 1.8.0.265 (tried with both AIR 30 and 32):

```
Internal error: java.lang.NullPointerException
        at com.adobe.flash.swf.SWF.addFrame(SWF.java:91)
        at com.adobe.flash.compiler.internal.targets.SWFTarget$FramesInformation.createFrames(SWFTarget.java:876)
        at com.adobe.flash.compiler.internal.targets.AppSWFTarget$AppFramesInformation.createFrames(AppSWFTarget.java:386)
        at com.adobe.flash.compiler.internal.targets.SWFTarget.build(SWFTarget.java:243)
        at com.adobe.flash.compiler.clients.MXMLC.buildSWFModel(MXMLC.java:686)
        at com.adobe.flash.compiler.clients.MXMLC.buildArtifact(MXMLC.java:672)
        at com.adobe.flash.compiler.clients.MXMLC.compile(MXMLC.java:553)
        at com.adobe.flash.compiler.clients.MXMLC.mainNoExit(MXMLC.java:242)
        at com.adobe.flash.compiler.clients.MXMLC.mainNoExit(MXMLC.java:196)
        at com.adobe.flash.compiler.clients.MXMLC.staticMainNoExit(MXMLC.java:167)
        at com.adobe.flash.compiler.clients.MXMLC.main(MXMLC.java:144)
```

However, I can successfully compile with Java 11.0.7. I recommend upgrading your Java beyond version 8, if possible.

**Comment by cgascons** [comment]
Thank you Josh, using the latest Java SDK (15) it compiles just fine. Closing this now.
