### ISSUE TITLE
Built SWC causes strange debugger suspension

### ISSUE THREAD

**Issue by jbgben** [BowlerHatLLC/vscode-as3mxml#505]
This is kind of complicated, but bear with me.
We generate a SWC using vscode-as3mxmlc with a bunch of embedded images.
We build two SWFs, a game SWF and a pause menu SWF. Both include the SWC.
The game SWF loads the Pause SWF with a Loader. After calling load, the debugger (Both Flash Builder and VS Code) will suspend randomly during (or before) static initialization. Do you have ANY idea what could be causing that?

**Comment by joshtynjala** [comment]
No idea. Since it happens with both Flash Builder and VSCode, it's definitely an issue in either the debugger or Flash/AIR.
