### ISSUE TITLE
Building royale-asjs\examples\crux\todomvc-jewel-crux with ActionScript & MXML plugin

### ISSUE THREAD

**Issue by Jasenvm** [BowlerHatLLC/vscode-as3mxml#506]
Hi

I am trying to compile and run the lastest `todomvc-jewel-crux example` using Visual Studio Code (v1.50.1) and ActionScript & MXML VSC plugin (v1.3.0).

My issue is when compiling the royale-asjs\examples\crux\todomvc-jewel-crux with
` mvn clean install `
the project builds exports to target successfully and runs fine inside the browser.

However, when compiling in VisualStudio Code / ActionScript & MXML plugin, I get an error (see below)

Steps to reproduce:
1) Building royal-asjs from source OK
2) Added royal-asjs SDK to VisualStudio Code OK
3) Open Folder: D:\dev\experiment\todomvc-jewel-crux OK
4) Code Completion OK
5) D:\dev\royale-asjs\frameworks\js\libs\CruxJS.swc exists OK
5) Cntrl+P -> Actionscript: Quick Compile & Run (Experimental) NOT OK:

`D:\dev\royale-asjs\frameworks\js\libs\CruxJS.swc Warning: The definition mx.rpc.events.FaultEvent depended on by org.apache.royale.crux.utils.services.MockDelegateHelper in the SWC D:\dev\royale-asjs\frameworks\js\libs\CruxJS.swc could not be found
`
I am sure I have just missed a step, any advice much appreciated.

Should I consider attempting to install the very latest plugin from git?

Jase

**Comment by joshtynjala** [comment]
Please ask for Royale support on the Royale users mailing list. I am not experienced with the Royale framework and cannot help with that.

**Comment by joshtynjala** [comment]
> Should I consider attempting to install the very latest plugin from git?
I can answer this for you, at least: It will not help to rebuild the vscode-as3mxml extension from Git.

**Comment by Jasenvm** [comment]
Thanks, Josh
