### ISSUE TITLE
 Definition org.apache.royale.core.WrappedSprite could not be found.

### ISSUE THREAD

**Issue by PhaneendraKiran** [BowlerHatLLC/vscode-as3mxml#510]
This is similar to issue #185 which is closed. But the work around mentioned there does not work for me.  We use ant script to do compilation. It is able to identify import org.apache.royale.geom.Point; But fails with error to locate package org.apache.royale.core.WrappedSprite; 
We have settings in the ant build file as 

```
<property name="COMPILER_TARGETS" value="-compiler.targets=JSRoyale" />
	<property name="MXMLC_PATH" value="${ROYALE_HOME}/js/bin/mxmlc.bat" />
```

here ROYALE_HOME refers to path where we locate for" apache-royale-0.9.8-bin-js/royale-asjs/frameworks". 
Essentially everything seems to be correct, but not able to figure out what is being wrong here.
Any pointers will be great help.

**Comment by joshtynjala** [comment]
Please ask for Apache Royale support on the Royale users mailing list.
