### ISSUE TITLE
Snippet: add package snippet

### ISSUE THREAD

**Issue by neuronix** [BowlerHatLLC/vscode-as3mxml#514]
Adding a package snippet could probably be handy since AS3 is so strict about using them and having them match folder names.

I tried using multiple transforms to automatically generated the appropriate package name for the current folder but I haven't found any documentation on nested transforms... so this uses the workspace name as a placeholder which is actually pretty decent since intellisense will suggest the correct package name accordingly if project name and root package names are identical.

```
"Package": {
		"prefix": "package",
		"body": [
			"package ${1:${WORKSPACE_NAME/(.*)/${1:/downcase}/}}",
			"{",
			"\t$0",
			"}"
		]
	}
```

**Comment by joshtynjala** [comment]
The regular code intelligence can complete the package block already, including the correct package name for the folder structure, so no need for a snippet. Just start typing "package" or press Ctrl+Space in an empty .as file, and you should see it included in the completion list.

**Comment by neuronix** [comment]
Hi Josh,

Indeed, sorry for the hassle, I only started getting the package suggestion after a day of working with VSCode but it works fine now. 

Thanks for your work on the plugin, it is really pleasant to work with!

**Comment by joshtynjala** [comment]
> Thanks for your work on the plugin, it is really pleasant to work with!

Thanks!
