### ISSUE TITLE
Using native extensions

### ISSUE THREAD

**Issue by AureliusSlawinski** [BowlerHatLLC/vscode-as3mxml#515]
Hi,
In order to get my native extension working, it had to add the ID to the "Main-app.xml" aswell:
```
<extensions>
    <extensionID>com.cleanextension.CleanExtension</extensionID>
</extensions>
```
This was not documented on your "how to desktop-plattform" help page.
Maybe you add this little hint.

I am comming from FlashBuilder, and the ID is added automatically to the xml, so I forgot about this.

**Comment by joshtynjala** [comment]
Thanks! I've added a note to the documentation for setting up Adobe AIR projects.
