### ISSUE TITLE
Help wanted with the setup of an old FlashBuilder project

### ISSUE THREAD

**Issue by dreammonkey** [BowlerHatLLC/vscode-as3mxml#516]
Hello,
I'm looking for pointers to revive an old Air FlashBuilder iOS/android project in vscode using this extension.

The project is setup in 3 separate projects
- A library which holds the main code
- A iOS wrapper for compiling to iOS 
- An Android wrapper for compiling to android

The projects uses several ANE's and was configured with the FlashBuilder UI.

Do you know about tutorials or instructions on how to successfully get such a setup running again using vscode, anyone with experience or a similar setup? I'd love to learn more

I know this is a broad question, just looking for pointers.

Cheers

**Comment by joshtynjala** [comment]
The vscode-as3mxml extension may be able to import your projects automatically. Have you given that a try? Just open each individual project folder in VSCode, and it should prompt you to import.

**Comment by dreammonkey** [comment]
I will surely give that a try !

Just to be clear though, each project will have to be imported one at a time, resulting in 3 vscode projects/windows ? I guess that'd make sense.

How would I initiatie the import? Is there a command for that ?

Does the import rely on the project-settings / .actionscriptproperties ?  

Thanks for your comment !

**Comment by joshtynjala** [comment]
> Just to be clear though, each project will have to be imported one at a time, resulting in 3 vscode projects/windows ? I guess that'd make sense.

Yes, but if you prefer, you can add multiple root workspace folders to a single window and save it as a combined workspace.

> How would I initiatie the import? Is there a command for that ?

When you first open the folder in VSCode, it should automatically detect the Flash Builder project files, and prompt you to import the project. However, there is a command you can choose from the command palette too. The command is named "ActionScript: Import Adobe Flash Builder project"

> Does the import rely on the project-settings / .actionscriptproperties ?

Yes, it reads the Flash Builder project files, like .actionScriptProperties, .flexProperties, and .flexLibProperties.

**Comment by dreammonkey** [comment]
I know it's been a while but I'm trying to give another go at this ...

Getting the entire project to run is difficult because of so many broken dependencies... :/ 

So I tried setting up a demo project following [this guide](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Create-a-new-ActionScript-project-in-Visual-Studio-Code-that-targets-Adobe-AIR-for-mobile-platforms) and [this one](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Debug-an-Adobe-AIR-mobile-application-with-Visual-Studio-Code). Now everything seems to be working, I can even see logs in the debugger console, but the adl is not showing **anything**, not even a default window layout, it's certainly running, ... there is an app icon in the dock but no content is rendering anywhere on screen :/ 

I'm using AIR  SDK 33.1.1.173
I'm trying to run this on a Mac M1, could that be an issue ?

`Main.as`
```as
package
{
	import flash.display.Sprite;
	import flash.text.TextField;
	import flash.events.Event;

	public class Main extends Sprite
	{
		public function Main()
		{
			trace('hello world')

			addEventListener(flash.events.Event.ADDED_TO_STAGE, init);
		}
		protected function init(event:flash.events.Event):void
		{
			removeEventListener(flash.events.Event.ADDED_TO_STAGE, init);
			trace('added to stage')

			const screenWidth:int  = stage.fullScreenWidth;
			const screenHeight:int = stage.fullScreenHeight;
			trace(screenWidth, screenHeight);

			var tf:TextField = new TextField();
			tf.text = "Hello World";
			stage.addChild(tf);
		}
	}
}
```

`Main-app.xml`
```as
<?xml version="1.0" encoding="utf-8" ?>
<application xmlns="http://ns.adobe.com/air/application/33.1">
	<id>com.example.Main</id>
	<versionNumber>0.0.1</versionNumber>
	<filename>Main</filename>
	<name>Main</name>
	<initialWindow>
		<content>[Path to content will be replaced by Visual Studio Code]</content>
		<visible>true</visible>
	</initialWindow>
</application>
```
`asconfig.json`
```as
{
  "config": "airmobile",
  "compilerOptions": {
    "source-path": ["src"],
    "output": "bin/Main.swf"
  },
  "mainClass": "Main",
  "application": "src/Main-app.xml"
  // "additionalOptions": "-locale en_US"
}
```

`launch.json`
```as
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "program": "bin/Main-app.xml", // I also tried with absolute path...
      "type": "swf",
      "request": "launch",
      "name": "Launch SWF",
      "preLaunchTask": "${defaultBuildTask}",
      "profile": "mobileDevice",
      "screensize": "iPhoneRetina",
      "screenDPI": 326,
      "versionPlatform": "IOS"
    }
  ]
}
```

`Debug Console`
```
hello world
added to stage
640 960
```

Fresh ideas are certainly welcome !
Many thanks

**Comment by joshtynjala** [comment]
> I'm using AIR SDK 33.1.1.173

It might be worth trying a newer release. The current version at the time that I write this comment is AIR 31.1.1.743.

> I'm trying to run this on a Mac M1, could that be an issue ?

I am able to run AIR 33.1 on an M1 Mac, so probably not. However, upgrading might help with this. It's possible that older builds had issues that have since been resolved.

> I can even see logs in the debugger console, but the adl is not showing anything

What's the value of `stage.nativeWindow.visible`?

**Comment by dreammonkey** [comment]
I was using SDK version 33.1.1.713 (I made typo in my last comment). 
I now upgraded to 33.1.1.743 and still no window appears. I do see the samsung branded AIR logo show up (same as before) for a bit and then nothing... .

I traced `stage.nativeWindow.visible` => `false`
And I invited Starling to the show as well, still no window is being rendered...


`Main.as`
```as
package
{
	import flash.display.Sprite;
	// import flash.text.TextField;
	import flash.events.Event;
	import starling.core.Starling;

	public class Main extends Sprite
	{
		private var _starling:Starling;

		[SWF(frameRate="60", backgroundColor="#ffffff")]
		public function Main()
		{
			trace('hello world')

			addEventListener(flash.events.Event.ADDED_TO_STAGE, init);
			
			_starling = new Starling(Game, stage);
      _starling.start();
		}

		
		protected function init(event:flash.events.Event):void
		{
			removeEventListener(flash.events.Event.ADDED_TO_STAGE, init);
			trace('added to stage')

			const screenWidth:int  = stage.fullScreenWidth;
			const screenHeight:int = stage.fullScreenHeight;
			trace(screenWidth, screenHeight);

			trace('stage.nativeWindow.visible', stage.nativeWindow.visible)
			stage.nativeWindow.visible = true;
			stage.nativeWindow.activate();
			trace('stage.nativeWindow.visible', stage.nativeWindow.visible)

			// var tf:TextField = new TextField();
			// tf.text = "Hello World";
			// stage.addChild(tf);
		}
	}
}
```

`Main-app.xml`
```as
<?xml version="1.0" encoding="utf-8" ?>
<application xmlns="http://ns.adobe.com/air/application/33.1">
	<id>com.example.Main</id>
	<versionNumber>0.0.1</versionNumber>
	<filename>Main</filename>
	<name>Main</name>
	
	<initialWindow>
		<!-- The main SWF or HTML file of the application. Required. -->
		<content>[Path to content will be replaced by Visual Studio Code]</content>
		
		<!-- The aspect ratio ("portrait", "landscape", or "any"). Optional. -->
		<aspectRatio>portrait</aspectRatio>

		<!-- Whether the app will begin auto-orienting on launch. Optional. Default false -->
		<autoOrients>false</autoOrients>

		<!-- Whether the app launches in full screen. Optional. Mobile only. Default false -->
		<!-- (On iOS, this decides if the StatusBar is visible or not.) -->
		<fullScreen>true</fullScreen>

		<!-- Either auto, cpu, gpu, or direct. Default auto -->
		<renderMode>direct</renderMode>

		<!-- Whether direct mode allocates storage for depth and stencil buffers. Default false -->
		<depthAndStencil>true</depthAndStencil>

		<!-- Whether or not to pan when a soft keyboard is raised or lowered (either "pan" or "none").  Optional.  Defaults "pan." -->
		<!-- <softKeyboardBehavior></softKeyboardBehavior> -->
		<visible>true</visible>
	</initialWindow>
</application>
```
`asconfig.json`
```as
{
  "config": "airmobile",
  "compilerOptions": {
    "source-path": ["src"],
    "output": "bin/Main.swf",
    "library-path": ["starling/bin"]
  },
  "mainClass": "Main",
  "application": "src/Main-app.xml",
  "additionalOptions": "-locale en_US"
}

```

`launch.json`
```as
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "program": "bin/Main-app.xml", // I also tried with absolute path...
      "type": "swf",
      "request": "launch",
      "name": "Launch SWF",
      // "preLaunchTask": "${defaultBuildTask}",
      "preLaunchTask": "ActionScript: compile debug - asconfig.json",
      "profile": "mobileDevice",
      "screensize": "iPhoneRetina",
      "screenDPI": 326,
      "versionPlatform": "IOS"
    }
  ]
}

```

`Debug Console`
```
hello world
added to stage
640 960
(2) stage.nativeWindow.visible false
[Starling] Context ready. Display Driver: OpenGL (Enhanced)
Hello Game

```

**Comment by joshtynjala** [comment]
Setting stage.nativeWindow.visible to true does not help?

**Comment by dreammonkey** [comment]
No :/ 

I tried this, but the output remains false

```as
stage.nativeWindow.visible = true;
trace('stage.nativeWindow.visible', stage.nativeWindow.visible)
stage.nativeWindow.visible = true;
stage.nativeWindow.activate();
trace('stage.nativeWindow.visible', stage.nativeWindow.visible)
```

**Comment by joshtynjala** [comment]
Did you run this command mentioned in the release notes?

> For macOS users on 10.15+, the SDK may not work properly unless the quarantine setting is removed from the SDK:
> `xattr -d -r com.apple.quarantine /path/to/SDK`

**Comment by dreammonkey** [comment]
yes, I tried that as well 🙈 

Strange thing is when I select `Adobe AIR: package iOS debug - asconfig.json` as prelanuch I get this in my terminal.
But maybe that's because I haven't set up any dev certificates yet ?

```bash
> Executing task: /usr/bin/java -jar /Users/username/.vscode/extensions/bowlerhatllc.vscode-as3mxml-1.11.0/bin/asconfigc.jar --sdk /Users/username/Develop/AIR/AIRSDK_MacOS_33.1.1.743 --debug=true --project /Users/username/Develop/projects/AIR-test/asconfig.json --air ios <

Loading configuration: /Users/username/Develop/AIR/AIRSDK_MacOS_33.1.1.743/frameworks/airmobile-config.xml

command line
Warning: 'compiler.locale' is not fully supported.

276793 bytes written to /Users/username/Develop/projects/AIR-test/bin/Main.swf in 2.562 seconds
Adobe (R) AIR (R) Developer Tool (ADT)
Version 33.1.1.743
Copyright (c) 2008-2019 Adobe. All rights reserved.

**No arguments were found**
usage:
  adt -checkstore SIGNING_OPTIONS
  adt -certificate -cn <name> ( -ou <org-unit> )? ( -o <org-name> )? ( -c <country> )? ( -validityPeriod <years> )? 2048-RSA <pfx-file> <password>
  adt -license
  adt -help

**Comment by joshtynjala** [comment]
> But maybe that's because I haven't set up any dev certificates yet ?

Yes. Your _asconfig.json_ file doesn't have an `airOptions` section, so it doesn't know what arguments to use.

**Comment by dreammonkey** [comment]
When using my dev certificate and provisioning profile I'm able to build an .ipa, but still nothing is showing ...

**Comment by joshtynjala** [comment]
> but still nothing is showing ...

Nothing is showing when the .ipa is installed on an iOS device?

**Comment by dreammonkey** [comment]
Have not yet tried that, how do I install it on a (ios) device ?

**Comment by joshtynjala** [comment]
That's the only reason to build an .ipa file. You never need to build an .ipa file or .apk file to test in AIR's mobile simulator.

Here's h ow to do it in VSCode.

https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Debug-an-Adobe-AIR-application-running-on-a-mobile-device-with-Visual-Studio-Code

You can also install it using Xcode's Simulators and Devices window, if you prefer.

**Comment by dreammonkey** [comment]
The app installs, but does not connect to the debugger (might be an networking issue)
But I get a white screen on my iphone ...

(need to run now will check back tomorrow)

`Forwarding port for debugging failed for platform "ios" and port 7936 because no connected devices could be found.
`

PS: thanks for your dedication ! 👍

**Comment by dreammonkey** [comment]
Hi Josh, I copied the project over to my intel mbp and the debug window launches as expected.
My guess is that this must almost definitely be a M1 arm64 vs. i386 issue. 😞 

Did you say you are able to run the AIR runtime (provided by the sdk) on a M1 mac ?
Are you using a different terminal, or specific arguments ? 
I tried making a copy of Terminal.app and forcing that to always open using Rosetta as suggested [here](https://www.courier.com/blog/tips-and-tricks-to-setup-your-apple-m1-for-development/). 
Trouble is I can't seem to get VScode to use that as the default terminal ...

**Comment by joshtynjala** [comment]
Besides running the `xattr -d -r com.apple.quarantine` command in a Terminal after extracting the AIR SDK, I don't think that I did anything special on my M1 Mac Mini. I have been launching from VSCode with normal options. No terminal involved at the point where I'm starting a debug session.

**Comment by dreammonkey** [comment]
Well it seems we both have the same computer then !
Things just started to get interesting...

I can confirm I can successfully launch the test app from my Terminal when calling adl directly.

`../../AIR/AIRSDK_MacOS_33.1.1.743/bin/adl bin/Main-app.xml`

Could it be a vscode issue? Conflicting extensions perhaps  ?

**Comment by joshtynjala** [comment]
Very strange that you can launch successfully from Terminal! I have no clue why it would be different.

**Comment by dreammonkey** [comment]
Hi Josh, I'm happy to let you know that today for the first time I'm seeing an actual window appear ! 🎉 

It seems was a problem with vscode, becasue it updated to the version below this morning and suddenly the debugger started working...

VS Code version:
January 2022 (version 1.64)

**Comment by joshtynjala** [comment]
Great news!

**Comment by dreammonkey** [comment]
One last question if I may, the main reason I need to update my app is because the in app purchases are no longer working... There used to be a lot of ANE providers, both paid and open source, but it seems a lot of them are deprecated/out of business... Do you have an idea where I can find maintained ANE's - preferably open source or reasonably priced ?

**Comment by joshtynjala** [comment]
@dreammonkey Distriqt continues to maintain their ANEs at https://airnativeextensions.com
