### ISSUE TITLE
Formatting: bracket position options

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/vscode-as3mxml#521]
In JS there's a setting to control the position of brackets for code completion of blocks and functions i.e. `typescript.format.placeOpenBraceOnNewLineForFunctions`

I'd love to have a preference setting for that in AS as well.

**Comment by joshtynjala** [comment]
The AS3 & MXML extension does not support formatting at all, so I would need to implement that before I could add any kind of options that control it. I doubt that I'll be adding formatting as a feature any time soon, though.

I remember someone sharing this other extension, but I've never tried it myself: https://github.com/leitwolf/vscode-ASTools

**Comment by Harbs** [comment]
Code completion of functions, getters/setters, implementing interface methods all place opening brackets on the next line. I'm looking for an option to change that.

The built-in matching and https://marketplace.visualstudio.com/items?itemName=formulahendry.auto-close-tag for mxml pretty much does everything else I need. (I added `mxml` to the fil;e types for  `auto-close-tag.activationOnLanguage`.)

**Comment by joshtynjala** [comment]
It may be that VSCode runs certain things through the formatter automatically with completion/snippets, and that's what you're seeing with JS/TS, but I'll need to investigate further to know for sure. One thing that I want to avoid is adding settings that suggest that full formatting capabilities are available when they actually are not.

**Comment by Harbs** [comment]
I just came across an extension for php which allows configuring bracket position. I couldn't find the code that handled it though... https://github.com/bmewburn/vscode-intelephense/commit/c983cacfa9065111ce975a4c02a2a8acfc15dc39

**Comment by joshtynjala** [comment]
Once the new Royale version is released, I'll be able to integrate the new formatter in VSCode, and you'll be able to specify bracket positions.

**Comment by Harbs** [comment]
Oh. That's great!
