### ISSUE TITLE
Using a saved workspace, code completion does not work

### ISSUE THREAD

**Issue by jbgben** [BowlerHatLLC/vscode-as3mxml#522]
If I am using an ad hoc workspace, code completion works fine with my asconfig.json. However, if I create a saved code-workspace, I get an error in my asconfig.json: 
```
JSON schema for the ActionScript configuration file

a target file must be specified.
D:\dev\tjpp8\TeamBuilding\asconfig.json (line: -1)(1319)
```

Any ideas?

**Comment by joshtynjala** [comment]
Can you share the contents of your _asconfig.json_ file?

**Comment by jbgben** [comment]
`{
    "config": "air",
    "type": "app",
    "mainClass": "Game",
    "application": "flash/src/Game-app.xml",
    "htmlTemplate": "./html-template",
    "compilerOptions": {
        "output": "flash/bin/air/Game.swf",
        "default-background-color": "#000000",
        "default-frame-rate": 30,
        "default-size": {
            "width": 1280,
            "height": 720
        },
        "target-player": "30",
        "swf-version": 26,
        "static-link-runtime-shared-libraries": true,
        "benchmark": false,
        "locale": [
            "en_US"
        ],
        "source-path": [
            "flash/src"
        ],
        "library-path": [
            "../jbg-common/flash/libs-jbgcommon/airglobal.swc",
            "../jbg-common/flash/libs-jbgcommon/as3corelib.swc",
            "../jbg-common/flash/libs-jbgcommon/asuuid.swc",
            "../jbg-common/flash/libs-jbgcommon/console-fonts.swc",
            "../jbg-common/flash/libs-jbgcommon/emoji.swc",
            "../jbg-common/flash/libs-jbgcommon/flash.swc",
            "../jbg-common/flash/libs-jbgcommon/gamepad.swc"
        ],
        "define": [
            {
                "name": "CONFIG::debug",
                "value": true
            },
            {
                "name": "CONFIG::release",
                "value": false
            },
            {
                "name": "CONFIG::DEMO",
                "value": false
            },
            {
                "name": "CONFIG::LOGGING",
                "value": true
            },
            {
                "name": "VERSION::STEAM",
                "value": false
            },
            {
                "name": "VERSION::TWITCH",
                "value": false
            },
            {
                "name": "VERSION::AIR",
                "value": true
            },
            {
                "name": "VERSION::WEB",
                "value": false
            },
            {
                "name": "VERSION::DESKTOP",
                "value": true
            },
            {
                "name": "VERSION::STARLING",
                "value": false
            },
            {
                "name": "VERSION::FLASH",
                "value": true
            },
            {
                "name": "VERSION::MOBILE",
                "value": false
            },
            {
                "name": "VERSION::CONSOLE",
                "value": false
            },
            {
                "name": "VERSION::NATIVE",
                "value": "!VERSION::FLASH"
            },
            {
                "name": "VERSION::VIDEOPLAYER",
                "value": "!VERSION::MOBILE"
            },
            {
                "name": "CONFIG::HAS_PUBLISHER",
                "value": false
            },
            {
                "name": "CONFIG::DEVELOPER_CONSOLE",
                "value": true
            }
        ]
    }
}`

**Comment by joshtynjala** [comment]
Is _asconfig.json_ at the root of one of your _.code-workspace_ folders? Or is it inside a sub-folder somewhere?

**Comment by jbgben** [comment]
It is not, my setup looks like...

d:\dev\myworkspace.code-workspace <--- References the folders below as "collection\game1", "collection\game2", etc

d:\dev\collection\game1\.vscode
d:\dev\collection\game1\asconfig.json
d:\dev\collection\game2\.vscode
d:\dev\collection\game2\asconfig.json
d:\dev\collection\game3\.vscode
d:\dev\collection\game3\asconfig.json

**Comment by joshtynjala** [comment]
Assuming that the asconfig.json file that you posted above is _d:\dev\collection\game1\asconfig.json_, your main class should be located at _d:\dev\collection\game1\flash\src\Game.as_. Does that file exist?

**Comment by joshtynjala** [comment]
Closing because there has been no response for a month. I can reopen if you still want to try to work through this.
