### ISSUE TITLE
Error: Cannot read field "classTable" because "compilationUnit" is null

### ISSUE THREAD

**Issue by varadig** [BowlerHatLLC/vscode-as3mxml#525]
macbookpro:app varadig$ /usr/bin/java -jar /Users/varadig/.vscode/extensions/bowlerhatllc.vscode-nextgenas-1.6.0/bin/asconfigc.jar --sdk /Volumes/Work/develop/as3/_SDK_/osx/air31-feathers4.0.0 --debug=true --project ./asconfig.editor.json --verbose=true
Configuration file: /Volumes/Work/develop/_project/dynamicdungeons.main/app/./asconfig.editor.json
Reading configuration file...
Validating configuration file...
Parsing configuration file...
SDK: /Volumes/Work/develop/as3/_SDK_/osx/air31-feathers4.0.0
Compiling application...
/Library/Java/JavaVirtualMachines/jdk-15.0.2.jdk/Contents/Home/bin/java -Dapple.awt.UIElement=true -Dflexcompiler=/Volumes/Work/develop/as3/_SDK_/osx/air31-feathers4.0.0 -Dflexlib=/Volumes/Work/develop/as3/_SDK_/osx/air31-feathers4.0.0/frameworks -jar /Volumes/Work/develop/as3/_SDK_/osx/air31-feathers4.0.0/lib/mxmlc.jar +flexlib=/Volumes/Work/develop/as3/_SDK_/osx/air31-feathers4.0.0/frameworks --debug=true +configname=air --warnings=false --define+=CONFIG::assetStoreUrl,"http://127.0.0.1:8080/" --define+=CONFIG::development,true --output=bin/editor/editor.swf --source-path+=common/src --source-path+=common/resources/ --source-path+=common/extsrc/ --source-path+=common/languages/en_US --source-path+=editor/src --source-path+=editor/resources --library-path+=common/libs/ --library-path+=/Volumes/Work/develop/as3/GotoCoreAS3/bin/ --library-path+=/Volumes/Work/develop/as3/_SDK_/osx/air31-feathers4.0.0/frameworks/themes/TopcoatLightMobileTheme/TopcoatLightMobileTheme.swc -optimize=false -- editor/src/Editor.mxml
Loading configuration file /Volumes/Work/develop/as3/_SDK_/osx/air31-feathers4.0.0/frameworks/air-config.xml
**Error: Cannot read field "classTable" because "compilationUnit" is null**

macbookpro:app varadig$ /usr/bin/java --version
java 15.0.2 2021-01-19
Java(TM) SE Runtime Environment (build 15.0.2+7-27)
Java HotSpot(TM) 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)
macbookpro:app varadig$

**Comment by varadig** [comment]
asconfig.editor.json

```
{
  "config": "air",
  "copySourcePathAssets": true,
  "airOptions": {
    "windows": {
      "output": "../bin/editor/Editor",
      "files": [
        {
          "file": "common/resources/bin/ffmpeg.exe",
          "path": "bin/ffmpeg.exe"
        },
        {
          "file": "resources/icons/icon16x16.png",
          "path": "editor/icons/icon16x16.png"
        },
        {
          "file": "editor/resources/icons/icon32x32.png",
          "path": "icons/icon32x32.png"
        },
        {
          "file": "editor/resources/icons/icon48x48.png",
          "path": "icons/icon48x48.png"
        },
        {
          "file": "editor/resources/icons/icon128x128.png",
          "path": "icons/icon128x128.png"
        },
        {
          "file": "common/resources/theme/common.xml",
          "path": "theme/common.xml"
        },
        {
          "file": "common/resources/theme/common.png",
          "path": "theme/common.png"
        },
        {
          "file": "editor/resources/theme/editor.xml",
          "path": "theme/editor.xml"
        },
        {
          "file": "editor/resources/theme/editor.png",
          "path": "theme/editor.png"
        }
      ]
    },
    "mac": {
      "output": "bin/editor/Editor.app",
      "files": [
        {
          "file": "common/resources/theme/common.xml",
          "path": "theme/common.xml"
        },
        {
          "file": "common/resources/theme/common.png",
          "path": "theme/common.png"
        },
        {
          "file": "editor/resources/icons/icon16x16.png",
          "path": "icons/icon16x16.png"
        },
        {
          "file": "editor/resources/icons/icon32x32.png",
          "path": "icons/icon32x32.png"
        },
        {
          "file": "editor/resources/icons/icon48x48.png",
          "path": "icons/icon48x48.png"
        },
        {
          "file": "editor/resources/icons/icon128x128.png",
          "path": "icons/icon128x128.png"
        },
        
        {
          "file": "editor/resources/theme/editor.xml",
          "path": "theme/editor.xml"
        },
        {
          "file": "editor/resources/theme/editor.png",
          "path": "theme/editor.png"
        }
      ]
    }
    ,
    "signingOptions": {
      "keystore": "certificate.p12",
      "storetype": "pkcs12"
    }
  },
  "compilerOptions": {
    "warnings": false,
    "define": [
      {
        "name": "CONFIG::assetStoreUrl",
        "value": "http://127.0.0.1:8080/"
      },
      {
        "name": "CONFIG::development",
        "value": true
      }
    ],
    "output": "bin/editor/editor.swf",
    "source-path": [
      "common/src",
      "common/resources/",
      "common/extsrc/",
      "common/languages/en_US",
      "editor/src",
      "editor/resources"
    ],
    "library-path": [
      "common/libs/",
      "/Volumes/Work/develop/as3/GotoCoreAS3/bin/",
      "/Volumes/Work/develop/as3/_SDK_/osx/air31-feathers4.0.0/frameworks/themes/TopcoatLightMobileTheme/TopcoatLightMobileTheme.swc"
    ]
  },
  "additionalOptions": "-optimize=false",
  "application": "editor/editor-app.xml",
  "files": [
    "editor/src/Editor.mxml"
  ]
}
```

**Comment by joshtynjala** [comment]
Because this is happening while you are running a build task, this is an error reported by the Flex SDK compiler (which the Feathers SDK is forked from). There's not really anything that I can do. You'll need to figure out what part of your code the compiler is having trouble with, and remove or change it until it works.

However, you might also try compiling without this: `-optimize=false`

I could see that potentially causing issues. Almost no one turns off ActionScript optimization, for obvious reasons, so that could very well have some bugs in the compiler because it isn't used often enough to find them.

**Comment by varadig** [comment]
Sry for the late reply, but I don't have/had time to find what is the real problem is.
but i need the optimize compiler flag, because I use worker in the project

**Comment by joshtynjala** [comment]
Closing because this is not an AS3 & MXML extension issue.
