### ISSUE TITLE
Code Action: Fully typed classes are not automatically importable

### ISSUE THREAD

**Issue by Adolio** [BowlerHatLLC/vscode-as3mxml#526]
Hi Josh,

I'm now using `v1.6` and have pretty much the same issue as #508 but for classes in core packages (flash.*).

Fully typed class:
![Screen Shot 03-04-21 at 10 33 AM](https://user-images.githubusercontent.com/1126990/109943980-0691dc00-7cd6-11eb-8ded-f7dfb7f3af0e.PNG)

Partially typed class:
![Screen Shot 03-04-21 at 10 36 AM](https://user-images.githubusercontent.com/1126990/109943972-042f8200-7cd6-11eb-8b37-c95be3d74d79.PNG)

Best,
Aurélien

**Comment by joshtynjala** [comment]
Interesting! It seems to work for the classes defined in .as files in my project, but not for the flash.* classes from playerglobal.swc/airglobal.swc. Or maybe it happens with all classes from any .swc file (I'll need to investigate further when I have time).

**Comment by joshtynjala** [comment]
Thanks! The fix will be in the next update.
