### ISSUE TITLE
compilerOptions.debug value in asconfig.json ignored when packaging AIR captive runtime release

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/vscode-as3mxml#527]
With a project set up to build as a captive runtime (Windows), the build task 'Adobe AIR: package Windows release' is automatically populated from asconfig.json.

However, even with `compilerOptions.debug = false` in asconfig.json, `--debug=true` is passed in the mxmlc command.

Attempting to override this behaviour by setting up the default build task as follows
```
{
	"type": "actionscript",
	"debug": false,
	"air": "windows"
}
```
results in the following error:
```
Error: The actionscript task detection didn't contribute a task for the following configuration:
{
    "type": "actionscript",
    "debug": false,
    "air": "windows"
}
The task will be ignored.
```

**Comment by joshtynjala** [comment]
Thanks! The fix will be in the next update.
