### ISSUE TITLE
MXML {} binding should support ActionScript completion

### ISSUE THREAD

**Issue by joshtynjala** [BowlerHatLLC/vscode-as3mxml#53]
Similar to how the &lt;fx:Script&gt; block and MXML events are a special case.

**Comment by joshtynjala** [comment]
I have partially implemented this, but I did not enable it. It seems that there's a bug in the compiler where the line/column of certain nodes is wrong. Will finish this enhancement after I fix this issue in the compiler.

**Comment by joshtynjala** [comment]
After updating to the next version after Royale 0.9.3, this feature can be enabled.

**Comment by carlosrovira** [comment]
Thanks Josh, we're about to create a new release. So if you could take a look this days it will be awesome. Thanks! :)

**Comment by esidegallery** [comment]
Is it possible to also add code hinting for functions and contructor arguments here too? Basically as if I were calling them in a script block or .as file.

e.g. `<f:LayoutGroup backgroundSkin="{new Quad(1, 1, Color.RED)}">` 
In the above, code completion stops once you get inside the constructor parentheses.

**Comment by joshtynjala** [comment]
@esidegallery Odd! I'll take a look.
