### ISSUE TITLE
How to debug issues in starting language server?

### ISSUE THREAD

**Issue by yishayw** [BowlerHatLLC/vscode-as3mxml#530]
Is there a log? I'm trying to debug what looks like this from the client log:

#######
14:48:03 INFO writer-Some("actionscript") src/language_server_protocol.rs:3580 settings synced

14:48:03 INFO writer-Some("actionscript") src/language_server_protocol.rs:3607 Project root: C:\dev\flexjs\royale-asjs\frameworks\projects\MXRoyale

14:48:03 DEBUG writer-None src/rpcclient.rs:254 => None {"jsonrpc":"2.0","method":"s:EchomsgEllipsis","params":["Project root: C:\\dev\\flexjs\\royale-asjs\\frameworks\\projects\\MXRoyale"]}

14:48:03 INFO writer-Some("actionscript") src/language_server_protocol.rs:840 initialize; params=Object({"languageId": String("actionscript")})

14:48:03 DEBUG writer-None src/rpcclient.rs:254 => None {"jsonrpc":"2.0","method":"s:command","params":["sign define LanguageClientError text=âœ– texthl=LanguageClientErrorSign","sign define LanguageClientInformation text=â„¹ texthl=LanguageClientInfoSign","sign define LanguageClientHint text=âž¤ texthl=LanguageClientInfoSign","sign define LanguageClientWarning text=âš  texthl=LanguageClientWarningSign"]}

14:48:03 DEBUG writer-None src/rpcclient.rs:254 => None {"jsonrpc":"2.0","method":"eval","params":["LSP#filename()"],"id":31}

14:48:03 DEBUG reader-None src/rpcclient.rs:207 <= None {"id":31,"jsonrpc":"2.0","result":"C:\\dev\\flexjs\\royale-asjs\\frameworks\\projects\\MXRoyale\\src\\main\\royale\\mx\\binding\\BindabilityInfo.as"}

14:48:03 DEBUG writer-None src/rpcclient.rs:254 => None {"jsonrpc":"2.0","method":"eval","params":["s:hasSnippetSupport()"],"id":32}

14:48:03 ERROR reader-Some("actionscript") src/rpcclient.rs:64 Thread reader-Some("actionscript") exited with error: Unable to read from language server

**Comment by joshtynjala** [comment]
It looks like you're trying to use the language server in another editor? I don't really have a good workflow to suggest. You could try adding `System.err.println()` calls in the language server code to see how far things get. Presumbly, these messages get printed in the client log somewhere.

Your log looks like JSON-RPC messages, which is what the language server protocol uses, but I don't recognize most of those method names as being part of the language server protocol, though (except for "initialize"). For instance, there's no "eval" method in the LSP, and I have no clue what "s:EchomsgEllipsis" is. That seems like something in your AS3/MXML code, maybe?

**Comment by yishayw** [comment]
Yes, I'm trying to use it with Vim. It was working for me on my old pc which is dead.

My test was to simply initialize the language server and go to a definition. That explains 'initialize' I'll see if I can figure out where the rest of the calls are coming from. Thanks.
________________________________
