### ISSUE TITLE
Server Automation

### ISSUE THREAD

**Issue by atmofunk** [BowlerHatLLC/vscode-as3mxml#532]
I don't think this qualifies as an issue specific to the extension itself, but it is an issue i'm having that i could use some help on so i'll ask anyway:

I use this extension for a pretty hefty project but i'm looking to offload production builds to a server.   I'm pretty heavily invested in the vscode-as3mxml system on my machine locally, but i'm unsure how to translate that to a machine that will ultimately be cli-only on a remote server.

Is there a way to use/translate the asconfig.json files I depend on to something that can be intepreted on a server in order to create the necessary adt commands?  Should I use something tradiitonal like Ant and rebuild the commands manually?

Just trying to piece together a plan that can harmoniously work with this tool!

Thanks for any insight

**Comment by joshtynjala** [comment]
You're looking for asconfigc:

https://www.npmjs.com/package/asconfigc

**Comment by atmofunk** [comment]
Holy crap ty Josh - perfect!  I'll check this out :)
