### ISSUE TITLE
Error #1069: Property drawWithQuality not found on flash.display.BitmapData and there is no default value.

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#540]
My Adobe Air Application has shown the error even if the target version was correct:
`<application xmlns="http://ns.adobe.com/air/application/32.0">`

![image](https://user-images.githubusercontent.com/6010183/127765426-2971ca6b-5531-4eb2-8258-9c254f221b84.png)

I have fixed this issue by adding this code to asconfig.json:
```
"additionalOptions":
	[
		"-swf-version=43"
	]
```
I create this issue for others who may have this error.
The issue should be fixed automatically by the extension.

Thanks!

**Comment by joshtynjala** [comment]
Using the `swf-version` compiler option is the correct solution. Th standalone AIR SDK & Compiler automatically uses its updated `swf-version`, but obviously, if you are using the legacy Adobe Flex 4.6 SDK merged with the AIR SDK integration kit, the older compiler won't know anything about new AIR versions, so it will use its old default `swf-version`.
