### ISSUE TITLE
Quick navigate: classes and symbols

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#541]
Hi!
My library contains thousands of ActionScript classes. Is there any way to quickly navigate to a class/function/property (the same as the QuickNavigate plugin of FlashDevelop)?
Thank you!

**Comment by joshtynjala** [comment]
In the **Go** menu, choose **Go to Symbol in Workspace**. Alternatively, the keyboard shortcut is Ctrl+T (or Command+T on macOS).

**Comment by ylazy** [comment]
Thank you!
