### ISSUE TITLE
Code hint support for Singleton Classes

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#542]
Hi!
Please add code hinting support for singleton classes properties. (see the attached image below)
![image](https://user-images.githubusercontent.com/6010183/127771320-9b04b1d9-c6a4-486e-8f00-0000122489b5.png)

**Comment by joshtynjala** [comment]
It looks like your `MainWindow` class does not have a public variable or property named `content`. Perhaps it is private or protected, or you gave it a different name.

**Comment by ylazy** [comment]
My `MainWindow` class does have the public variable named `content`.  It compiles successfully.
If I write it directly: `MainWindow.instance.content`, the code hint shows up.
I don't understand why, but today when I reopen it, everything works fine. The issue didn't happen again.
