### ISSUE TITLE
Extension failed to start

### ISSUE THREAD

**Issue by atmofunk** [BowlerHatLLC/vscode-as3mxml#549]
So this just popped up on me this morning and I'm at a loss for what to do about it:

![image](https://user-images.githubusercontent.com/931671/131725673-205f9264-4a70-437f-92f7-9fbfe96e9d69.png)
![image](https://user-images.githubusercontent.com/931671/131726312-23f0a8e2-3d30-4de6-a764-afb239b5111d.png)

Literally nothing changed (afaik) from when i was working yesterday until this morning.  No windows update, no vscode update, no extension update.  

I've restarted multiple times, rebooted my pc, and updated java (after i discovered the problem, not before).  

Any ideas?  Need more info?

**Comment by joshtynjala** [comment]
Open VSCode's command palette and run the "Developer: Toggle Developer Tools" command. This should open Electron's browser developer tools. In the console, it might have more detailed error messages.

**Comment by atmofunk** [comment]
ok, got a stack trace:

![image](https://user-images.githubusercontent.com/931671/131730350-44eb2ed7-f40e-40af-bcd6-29902533f541.png)

**Comment by atmofunk** [comment]
Ok its working again -- I found a rogue entry in my code-workspace settings file that was attempting to load an older version of launch.json from the .vscode folder.   May have been related to gitlens, but not 100% sure.

Thanks for your time!
