### ISSUE TITLE
launch.json args should be array

### ISSUE THREAD

**Issue by neminovno** [BowlerHatLLC/vscode-as3mxml#550]
If one follows https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/launch.json-fields-for-SWF-debugging#args
![image](https://user-images.githubusercontent.com/1468887/132223184-0243c3cc-6829-48d9-a076-6ceb14b1a281.png)

VSCode will say:
> Incorrect type. Expected "array".

This works:
`"args": ["myFirsArgument", "222", "third"]`

**Comment by joshtynjala** [comment]
Fixed! Thanks.
