### ISSUE TITLE
language server error [Error: command 'as3mxml.addImport' already exists]

### ISSUE THREAD

**Issue by varadig** [BowlerHatLLC/vscode-as3mxml#551]
I have a workspace, with 6 pure as3 subproject. So it's a quet big project.
Time by time I got this error, and just the vscode restart solve the problem.
Maybe this happening, because multiple server is running.

![Screenshot 2021-09-09 at 08 17 36](https://user-images.githubusercontent.com/6317148/132633821-52b508d9-91f9-4594-bb7e-2688a7231368.png)

**Comment by joshtynjala** [comment]
Yes, it seems like multiple language servers are being started, for some reason. I don't know how that could happen! It should always be one language server, even with multiple projects in the same window.

Do you see any output displayed if you select those "ActionScript & MXML Language Server" choices from the drop down?

Can you also tell me the versions of the "ActionScript & MXML", "Debugger for SWF", and "AS3, MXML, and SWF Extension Pack" extensions that you have installed? Can you try uninstalling them all and re-installing the AS3, MXML, and SWF Extension Pack?

**Comment by varadig** [comment]
![image](https://user-images.githubusercontent.com/6317148/132802276-f715826e-8dfb-4d4e-a2b3-64b01f98b8c8.png)
![image](https://user-images.githubusercontent.com/6317148/132802310-30063036-2b73-4e75-8dd9-2939e4e817d6.png)
![image](https://user-images.githubusercontent.com/6317148/132802333-b67ed2ac-5247-4087-9fae-b9220b351c03.png)
![image](https://user-images.githubusercontent.com/6317148/132802536-39b6137a-fe2a-4050-a68c-6dc93cc6df0a.png)



versions
ActionScript & MXML
![image](https://user-images.githubusercontent.com/6317148/132802644-11335c93-087e-467e-8d41-e384cc8f8e8e.png)

Debugger for SWF
![image](https://user-images.githubusercontent.com/6317148/132802767-1eeded4d-915c-4a54-b0eb-7e743aac3ecf.png)

AS3, MXML and SWF Extension Pack
![image](https://user-images.githubusercontent.com/6317148/132802890-1f1436f5-8b5c-4c4a-8ce1-21aa2b2d1a76.png)

Now i''m going to reinstall all of it, and after I will come back with the results

**Comment by varadig** [comment]
the issue is occurred after reinstall too

**Comment by joshtynjala** [comment]
@varadig Is this issue still happening?

**Comment by varadig** [comment]
Yes, sometimes is occur

**Comment by varadig** [comment]
<img width="1712" alt="Screenshot 2021-12-08 at 11 27 15" src="https://user-images.githubusercontent.com/6317148/145192585-576d881d-9673-49ef-8e8c-00577a1434f7.png">

**Comment by joshtynjala** [comment]
@varadig That looks like a different error to me...
