### ISSUE TITLE
Can't compile module.

### ISSUE THREAD

**Issue by varadig** [BowlerHatLLC/vscode-as3mxml#554]
What is the problem with this configuration?
modules is just working with mxml files?

![ModuleCompileError](https://user-images.githubusercontent.com/6317148/132749650-141b6b68-2a76-4bb0-a007-002bd5a18123.png)

**Comment by joshtynjala** [comment]
> "type": "lib"

Modules can only be created for application projects.

**Comment by varadig** [comment]
why this restriction needed? I have to compile uicomponent library swc, and want to export each component live preview to swf.

**Comment by joshtynjala** [comment]
Modules aren't a generic way to compile multiple SWFs in the same project. Modules are something that a main application loads on demand at runtime to avoid loading everything all at once. In other words, modules aren't meant to be standalone apps on their own.

This feature was mainly to provide a way to compile Flex modules, which is a feature that Flash Builder offers. My VSCode extension is providing that feature mostly as-is. The one thing it could theoretically support that Flash Builder doesn't is compiling non-Flex modules.

If you want to compile multiple SWFs in the same project, you can create multiple asconfig.json files, and add a secondary name between asconfig and .json, like asconfig.livepreview1.json, asconfig.livepreview2.json, etc.

**Comment by varadig** [comment]
Thank You Josh!
