### ISSUE TITLE
Organize Imports: Imports issue with class declared outside the package block (in same file)

### ISSUE THREAD

**Issue by Adolio** [BowlerHatLLC/vscode-as3mxml#566]
Hi Josh,

I just discovered a small issue related to classes declared outside the package block (in the same file). The code action proposes to fix the missing import but the `organize imports` feature then cleans it.

This gif demonstrates the issue:

![OutOfPackeClassImportIssue](https://user-images.githubusercontent.com/1126990/141773219-e006d2d3-b3df-4c41-a552-d67fb346ea3e.gif)

Best,
Aurélien

**Comment by joshtynjala** [comment]
Wow, I never knew that if you need to reference the class in the package block from outside of the block in the same file, that you are required to import it (unless it's in the top-level package, of course). I confirm that all AS3 compilers require this. Crazy how this hasn't come up before now!

**Comment by Adolio** [comment]
Thanks Josh for the fix. 

Yes, this was a discovery for me as well. I think this was the first time I had to do a such thing 😅
