### ISSUE TITLE
Getting error while used mx:HTML 

### ISSUE THREAD

**Issue by mmchavda** [BowlerHatLLC/vscode-as3mxml#568]
I am working on move my adobe air project from flash builder to visual studio code.

My project sdk is 4.6.0
Project used mx+spark component

I have imported other modules and compile successfully.
But in my one module library getting error on compile time.

Error:
D:\project\TLSRD\VSStudio\kokko-suite\KokkoSuite Core Flex Modules Library\FlexModules\src\org\kokkosuite\presentation\RichTextEditor.mxml(93):  Error: Type was not found or was not a compile-time constant: HTML.

        <mx:HTML id="editorWrapper" width="100%" height="100%" location="/ckeditor.html" />    

Is there any solution to solve this error? 

class is exist under sdk path:
D:\project\TLSRD\SourceFile\4.6.0\frameworks\projects\airframework\src\mx\controls\HTML.as

----------------------------------------
Also getting reference error in embed tag

[Embed(source='org/kokkosuite/presentation/male-default-small.png')]
			public static const maleDefaultSmall:Class;
To solve it i need to give syntax like below:

[Embed(source='../../../org/kokkosuite/presentation/male-default-small.png')]
			public static const maleDefaultSmall:Class;

is there any solution so system is taking root path for embed?

Thanks,
Mohit

**Comment by joshtynjala** [comment]
> Error: Type was not found or was not a compile-time constant: HTML.

Do you have `"config": "air"` in your _asconfig.json_ file?

> is there any solution so system is taking root path for embed?

To reference a file starting from the project root, you need to start your path with `/`. This might work:

_/org/kokkosuite/presentation/male-default-small.png_

**Comment by mmchavda** [comment]
Hi,

1)
Error:
D:\project\TLSRD\VSStudio\kokko-suite\KokkoSuite Core Flex Modules Library\FlexModules\src\org\kokkosuite\presentation\RichTextEditor.mxml(93): Error: Type was not found or was not a compile-time constant: HTML.

Project is library project and need swc file which used in main project.
In asconfig.json, there is not any property "config": "air".

2) 
For reference issue, now i can build swc with /  instead of long path / will take as source. - thanks for this solution.

Thanks,
Mohit

**Comment by joshtynjala** [comment]
> In asconfig.json, there is not any property "config": "air".

Okay, that's the issue! To access Adobe AIR classes in your code, you need to add `"config": "air"` to your asconfig.json file.

**Comment by mmchavda** [comment]
Hi, 

After adding property, now able to generate .swc file 

Thanks,
Mohit
