### ISSUE TITLE
Add new compiler options

### ISSUE THREAD

**Issue by Harbs** [BowlerHatLLC/vscode-as3mxml#569]
It would be nice if asconfig.json would allow direct input of all the compiler options here: https://apache.github.io/royale-docs/compiler/compiler-options

My `additionalOptions` section is getting a little unwieldy... ;)

```
"additionalOptions": "-js-output-optimization=skipAsCoercions -allow-abstract-classes=true -js-vector-emulation-class=Array -js-vector-index-checks=false -js-complex-implicit-coercions=false -export-public-symbols=false -prevent-rename-protected-symbols=false -prevent-rename-public-static-methods=false -prevent-rename-public-instance-methods=false -prevent-rename-public-static-variables=false -prevent-rename-public-instance-variables=false -prevent-rename-public-instance-accessors=false",
```

**Comment by joshtynjala** [comment]
I'll try to get this added soon. In the meantime, `additionalOptions` now supports both a string format and an array of strings format, so switching to something more like this might be a bit easier to manage:

```
"additionalOptions": [
	"-js-output-optimization=skipAsCoercions",
	"-allow-abstract-classes=true",
	// ...
]
```

**Comment by Harbs** [comment]
🎉 ❤️
