### ISSUE TITLE
Import flashbuilder project can't generate asconfig.json

### ISSUE THREAD

**Issue by mmchavda** [BowlerHatLLC/vscode-as3mxml#570]
Hi,

I am working on move my adobe air project from flash builder to visual studio code.

My project sdk is 4.6.0
Project used mx+spark component

I have imported 5 library project into vs code, now for 6th library project when import it to vscode, system can't generate asconfig.json file.
Output message:

🚀 Importing Adobe Flash Builder project...
✅ Import complete.

is there any way to generate asconfig.json file while import flash builder project to vscode?

Thanks,
Mohit

**Comment by mmchavda** [comment]
I have added property in .actionScriptProperties  file and now asconfig.json is generated.
 <applications>
    <application path="TLSModule.mxml"/>
  </applications>

In my main project having variable reference in .actionScriptProperties file and same is converted in asconfig.json file like:


	"compilerOptions": {
		"output": "bin-debug/myproject.swf",
		"accessible": true,
		"source-path": [
			"src",
			"${PROJECTS_LOC}/kokolib/kokolibFlex Modules Library/FlexModules/modules",
			"${PROJECTS_LOC}/kokolib/kokolibFlex Modules Library/FlexModules/ckeditor",
			"${PROJECTS_LOC}/kokolib/kokolibFlex Modules Library/FlexModules/locale/en_US",
			"${PROJECTS_LOC}/myproject/PrjModule/prjModules"
		],
		"library-path": [
			"libs",
			"D:/mohit/TLSRD/VSStudio/kokolib/kokolibFlexLibrary/FlexLibrary/bin/kokolib.swc",
			"D:/mohit/TLSRD/VSStudio/kokolib/kokolibFlexExtensions/FlexExtensions/bin/kokolibFlex Extensions.swc",
			"D:/mohit/TLSRD/VSStudio/myproject/TLSFlexCore/bin/TLSFlexCore.swc",
			"D:/mohit/TLSRD/VSStudio/prjvara/framework/bin/prjvara.swc",
			"D:/mohit/TLSRD/VSStudio/kokolib/Tan/Tan/bin/Tan.swc",
			**"D:/mohit/TLSRD/VSStudio/kokolib/kokolibSkinLibrary/SkinLibrary/bin/kokolibSkinLibrary.swc",
			"D:/mohit/TLSRD/VSStudio/myproject/prjModule/bin/prjModuleLibrary.swc",
			"D:/mohit/TLSRD/VSStudio/kokolib/kokolibFlexModulesLibrary/FlexModules/bin/kokolibFlex Modules Library.swc",
			"${FLEXUNIT_LIB_LOCATION}/version4libs/Common",
			"${FLEXUNIT_LIB_LOCATION}/version4libs/FlexProject",
			"${FLEXUNIT_LIB_LOCATION}/version4libs/FlexProject_Extended",
			"${FLEXUNIT_LOCALE_LOCATION}/version4locale/"
		]
	},

How can provide value of reference variable? like FLEXUNIT_LOCALE_LOCATION & PROJECTS_LOC 

For now getting error due to not set reference variable.

Thanks,
Mohit

**Comment by joshtynjala** [comment]
You'll need to manually edit your asconfig.json file to replace the tokens with the real paths, wherever they are on your local computer.

Based on context, I would guess that `PROJECTS_LOC` is _D:/mohit/TLSRD/VSStudio_. You'll need to figure out `FLEXUNIT_LIB_LOCATION` and `FLEXUNIT_LOCALE_LOCATION` on your own. You could probably comment these out if you don't strictly need to run FlexUnit tests.

**Comment by mmchavda** [comment]
Thanks, After apply full path, it's work

Still i want to search if we can provide variable value instead of hard code path.

Thanks,
Mohit

**Comment by joshtynjala** [comment]
> Still i want to search if we can provide variable value instead of hard code path.

Try adding `+PROJECTS_LOC =D:/mohit/TLSRD/VSStudio` to the `additionalOptions` field of _asconfig.json_. A compiler option starting with `+` defines a "token", which should allow you to use `${PROJECTS_LOC}` in other compiler options that accept file paths.

You'll still need to hardcode the path in _asconfig.json_, but if this works, it will be only once instead of everywhere that this is used.

It's also worth mentioning that you are allowed to use relative paths in _asconfig.json_ instead of absolute paths. For instance, you have `"output": "bin-debug/myproject.swf"`. You may not need a token at all, if the paths are easily resolved from the root directory of your project.

**Comment by mmchavda** [comment]
Hi,

PROJECTS_LOC in additionalOptions is working as source variable for "library-path" and "modules" in asconfig.json.
But for "source-path" it's not working. 

"source-path" is taking root path of the project.
I got below error where "LibraryProjects" in other folder than "MyProject"
Invalid source path: d:\mohit\TLSRD\VSStudio\MyProject\ProjectApp\${PROJECTS_LOC}\LibraryProject\Flex Modules Library\FlexModules\modules

I need to provide full path in "source-path" but it's fine.

Thank you very much for your support.
