### ISSUE TITLE
[ERROR] Debbuging Via USB Android AIR App

### ISSUE THREAD

**Issue by angelhdzmultimedia** [BowlerHatLLC/vscode-as3mxml#579]
You saved me time with the `command:as3mxml.saveSessionPassword`. Everything works in the AIR Emulator, the build task calls the sign in password task and finally debug. Don't have to keep typing the .p12 password anymore.

My new issue is debugging via USB in my Android phone. I carefully followed the steps in https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Debug-an-Adobe-AIR-application-running-on-a-mobile-device-with-Visual-Studio-Code.

This is my configuration:

![image](https://user-images.githubusercontent.com/10191085/149427552-88631dab-d381-4c31-9c56-ce0dcca8cd83.png)
![image](https://user-images.githubusercontent.com/10191085/149427581-efa5f2da-ff1d-4d40-926f-04b67965a379.png)

I run the `Install & Attach Adobe AIR (Android)` task, and this is the error:

![image](https://user-images.githubusercontent.com/10191085/149427616-c0a31ada-8137-4843-82bc-941c275dc744.png)

As the error complains about the `applicationID`, i changed my app's name in asconfig.json to follow Android's required name with com.username.AppName, and then changed `applicationID `in launch.json. The app's name was previously just `MyApp`.

**Comment by joshtynjala** [comment]
A few of things that you should probably address:

1) I don't understand why you the `dependsOn` field in one of your build tasks, you seem to be building your application twice. Unless I misunderstood something, you should probably change the `preLaunchTask` for the "Install & Attach" configuration in your _launch.json_ to "package Adobe AIR app (Android)".

1) You are specifying `--debug=false` that task. You _won't_ be able to connect the debugger to the app on your device with this argument.

1) You should not need to specify `applicationID` in your _launch.json_ file. The debugger should automatically populate the `applicationID` with the value from your _*.-app.xml_.

**Comment by angelhdzmultimedia** [comment]
> A few of things that you should probably address:
> 
> 1. I don't understand why you the `dependsOn` field in one of your build tasks, you seem to be building your application twice. Unless I misunderstood something, you should probably change the `preLaunchTask` for the "Install & Attach" configuration in your _launch.json_ to "package Adobe AIR app (Android)".
> 2. You are specifying `--debug=false` that task. You _won't_ be able to connect the debugger to the app on your device with this argument.
> 3. You should not need to specify `applicationID` in your _launch.json_ file. The debugger should automatically populate the `applicationID` with the value from your _*.-app.xml_.

Thank you for your time and infromation provided.

You're right. Apparenty the second task after the sign in password process, it also builds/debugs like the first task.
I renamed the second task to `Sign In Password" and removed it as dependency of the first task. The first task will be to build/debug with the AIR Android Emulator and "Sign In Password" task will be the one to debug in my android Phone via USB.
**But still the same error:**

https://user-images.githubusercontent.com/10191085/149605804-1a7df29d-3296-40e1-85ad-3487c58bdd43.mp4

AIR  Manifest:
![image](https://user-images.githubusercontent.com/10191085/149605845-c3626cda-830c-41c4-b4d6-0acfe9739ab9.png)

**Comment by angelhdzmultimedia** [comment]
Just installed Flash Develop, used the same AIR SDK, changed to JDK 11 in adt.cfg (FD didn't got it from JAVA_HOME for some strange reason), and managed to install the APK in my phone via USB in Flash Develop.

So after getting sure everything works, I tried again in VSCode with this extension, and same error as earlier...

I don't know what's wrong with AS & MXML or VSCode TBH... 😣

**Comment by angelhdzmultimedia** [comment]
### UPDATE
Finally solved the first error. It was the version in the AIR manifest was all zeros 0.0.0.  Changed to 0.0.1 and fixed.
The debug continued as it did in Flash Develop, the .APK was created in `bin/MyApp.apk `and now I get this error:
![image](https://user-images.githubusercontent.com/10191085/149624370-009d560f-33c0-47bb-bab6-ab1a21644d4e.png)

**Comment by joshtynjala** [comment]
> Warning: failure in signing Android apk-debug

Well, this is clearly why installing the app fails. If the app isn't signed, Android will reject it. However, I don't really know what would cause this error, and Google isn't giving any results for the error.

Are you using the same certificate and password in VSCode that you used in FlashDevelop?

**Comment by angelhdzmultimedia** [comment]
> > Warning: failure in signing Android apk-debug
> 
> Well, this is clearly why installing the app fails. If the app isn't signed, Android will reject it. However, I don't really know what would cause this error, and Google isn't giving any results for the error.
> 
> Are you using the same certificate and password in VSCode that you used in FlashDevelop?

When I run it in the AIR Emulator, it asks me for password, i put 123456 and it compiles.
So I assumed that when running in device via USB, it would work as well. Do I need to call `adt `to create the certificate file?

**Comment by joshtynjala** [comment]
When you debug your app on your desktop computer using the AIR Debug Launcher (which I assume you are referring to when you say "AIR Emulator"), you should not need a password at all. You can simply run the appropriate "compile debug" task, rather than "package debug". You only need to package if you need an .apk/.ipa/.exe file, such as when you are installing on a device.

If you installed an app on your Android device successfully from FlashDevelop, I assume that you already have a perfectly good certificate. You shouldn't need to use adt to create a certificate file if you already have one.

**Comment by angelhdzmultimedia** [comment]
> When you debug your app on your desktop computer using the AIR Debug Launcher (which I assume you are referring to when you say "AIR Emulator"), you should not need a password at all. You can simply run the appropriate "compile debug" task, rather than "package debug". You only need to package if you need an .apk/.ipa/.exe file, such as when you are installing on a device.
> 
> If you installed an app on your Android device successfully from FlashDevelop, I assume that you already have a perfectly good certificate. You shouldn't need to use adt to create a certificate file if you already have one.

In Flash Develop, I execute the CreateCertificate.bat and it creates it.
Oh, snaps. That's the issue! 
I haven't created it in VScode!

Is there a script to do that, or should I navigate to AIR SDK's directory and call some adt command there?

Thank you.

**Comment by joshtynjala** [comment]
Just use the same certificate that you created in FlashDevelop with CreateCertificate.bat. You don't need to create a new one.
