### ISSUE TITLE
Build AIR macOS apps  - Apple silicon (Universal Binary) and Intel-based Mac computers

### ISSUE THREAD

**Issue by zabdoul60460** [BowlerHatLLC/vscode-as3mxml#580]
Hello, 
With vsCode-as3Mxml, is it possible to build AIR macOS apps  that run natively on both Apple silicon (Universal Binary) and Intel-based Mac computers or is rosetta 2 mandatory ?
Best regards

**Comment by joshtynjala** [comment]
I believe that Rosetta 2 is still mandatory, but please refer to the AIR SDK release notes on HARMAN's website for details.

https://airsdk.harman.com/release_notes
