### ISSUE TITLE
Always show:Initializing ActionScript & MXML language server...

### ISSUE THREAD

**Issue by fireflyhy** [BowlerHatLLC/vscode-as3mxml#583]
Always show:Initializing ActionScript & MXML language server...
and High CPU usage

**Comment by joshtynjala** [comment]
When it never completes initialization, it means that something about your project is causing code intelligence to crash or hang. Would it be possible for you to share your project with me?

Additionally, can you give me some more information? Which operating system? Which version of Java? Thanks!

**Comment by fireflyhy** [comment]
Thank you for reminding me.

I found the problem. Because there are too many files in the imported external class folder

**Comment by joshtynjala** [comment]
@fireflyhy You may be able to fix that by increasing the memory available to the JVM when running the extension.

Take a look at the [as3mxml.languageServer.jvmargs](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Extension-settings#as3mxmlasconfigcjvmargs) setting. Something like `-Xmx1024m` might be just what you need.
