### ISSUE TITLE
stage.allowsFullScreenInteractive is false (except with AIR 33)

### ISSUE THREAD

**Issue by Stortof** [BowlerHatLLC/vscode-as3mxml#592]
Hi Josh, 

I don't know if it's related to vscode-as3mxml but I wanted to try your great extension by compiling an old FlashDevelop project on VSCode and I have a strange issue :

stage.allowsFullScreenInteractive is false and the app exit if I try to set stage to StageDisplayState.FULL_SCREEN_INTERACTIVE...

I tried with several AIR SDK but no way to change this... any idea?

The same project is OK on Flashdevelop...
Is there something specific to handle on VSCode?

```
<?xml version="1.0" encoding="utf-8" ?>
<application xmlns="http://ns.adobe.com/air/application/28.0">
	<id>AbyssBoxMap</id>
	<versionNumber>1.0</versionNumber>
	<filename>AbyssBoxMap</filename> 
	<name>AbyssBoxMap</name>

	<initialWindow> 
		<title>AbyssBoxMap</title> 
		<content>[Path to content will be replaced by Visual Studio Code]</content>
		<systemChrome>none</systemChrome> 
		<transparent>false</transparent> 
		<visible>true</visible> 
		<minimizable>false</minimizable> 
		<maximizable>false</maximizable> 
		<resizable>true</resizable> 
		
	</initialWindow> 

	<supportedProfiles>desktop extendedDesktop</supportedProfiles>

</application>
```
```
{
     // Utilisez IntelliSense pour en savoir plus sur les attributs possibles.
     // Pointez pour afficher la description des attributs existants.
     // Pour plus d'informations, visitez : https://go.microsoft.com/fwlink/?linkid=830387
     "version": "0.2.0",
     "configurations": [
          {
               "type": "swf",
               "request": "launch",
               "name": "Launch SWF",
               "profile": "extendedDesktop",
               "preLaunchTask": "ActionScript: compile debug - asconfig.json",
          }
     ]
}
```
```
{
	"config": "air",
	"compilerOptions": {
		"source-path": [
			"src", 
			"lib/as"
			
		],
		"library-path": [
			"lib/swc"
		],
		
		"output": "bin/AbyssBoxMap.swf"
	},
	"mainClass": "Main",
	"application": "src/Main-app.xml",
	"airOptions": 
	{
		"windows": {
			"target": "bundle",
			"output": "bin",
			"signingOptions": {
				"storetype": "pkcs12",
				"keystore": "AS.p12"
			}
		},
		"files": [
			{
				"file": "static/data",
				"path": "data"
			},
			{
				"file": "static/cmd",
				"path": "cmd"
			}
		]
	}
}
```

Thanks for your help !

**Comment by Stortof** [comment]
I don't know what I've done but the issue is gone... :)

**Comment by Stortof** [comment]
OK I repoen this one and I understood what made the difference.

I need to publish with the latest AIR SDK (33.1.1.743) to have access to StageDisplayState.FULL_SCREEN_INTERACTIVE...

Do you know why?

**Comment by Stortof** [comment]
But the odd is that with FlashDevelop I can publish with any Air SDK and it works....and all my apps use full screen and I never had this issue...

**Comment by joshtynjala** [comment]
Does FlashDevelop show the full terminal commands (mxmlc, adt, etc.) that are run when building your app? In vscode-as3mxml, you can enable `as3mxml.asconfigc.verboseOutput` in settings to see the full terminal commands.

Ultimately, every editor/IDE ends up running the command line tools in your SDK, so the easiest way to find the difference is probably to see which commands are actually being run, and how the options differ.

**Comment by Stortof** [comment]
OK I think I found the problem. It works with older SDK if I set a "swf-version" value...so I guess that it compiles by default with a swf-version correspond to something lower than FLash Player 9.0.28.0 as StageDisplayState.FULL_SCREEN_INTERACTIVE is available since this version...

**Comment by Stortof** [comment]
I am using the AIR SDK & Compiler.

**Comment by joshtynjala** [comment]
That's really odd. In my experience, with the AIR SDK & Compiler, it has a default swf-version that is correct for the version of AIR that it targets, and you almost never need to set it manually. Only with the Flex SDK should you need to specify swf-version because the default swf-version will be whichever version of AIR was available when the Flex SDK was originally released, and the default swf-version doesn't get updated when you merge in a new AIR SDK.

**Comment by joshtynjala** [comment]
Interestingly, it appears that `allowsFullScreenInteractive` is always `false` for me when I run in ADL, no matter which version of the AIR SDK that I try to use. However, I can successfully use `StageDisplayState.FULL_SCREEN_INTERACTIVE` without crashing. I did not need to set swf-version at all.

Well, at least you figured out a way to make it work. I'm going to close this issue.
