### ISSUE TITLE
No actionscript compilation option displayed

### ISSUE THREAD

**Issue by mjesteve** [BowlerHatLLC/vscode-as3mxml#593]
On my main development machine I cannot see the option to "compile with actionscript" (the following image is from another machine).

![image](https://user-images.githubusercontent.com/55754195/159256936-a0f4fdc8-bd7d-49a6-b99c-a3d51eaf4620.png)

I have uninstalled the two extensions, reinstalled them and it has not solved the problem.
I have not seen any comments about it, any ideas?

Thx.

**Comment by joshtynjala** [comment]
Do you have an asconfig.json file in the root of your workspace?

**Comment by mjesteve** [comment]
Hi Josh, yes
This behavior occurs in all my projects, I think it is because of the machine, maybe because of the java or because of the vsCode installation... 
This is an example of asconfig.json:

`{
    "config": "royale",
    "compilerOptions": {
        "debug": true,
        "targets": ["JSRoyale"],
        "html-template": "src/main/resources/jewel-app-index-template.html",
        "theme": "${royalelib}/themes/JewelTheme/src/main/resources/defaults.css",
        "source-path": [
            "src/main/resources",
            "../../royalelibs/royalecomponents/src/main/royale/",
			"../../royalelibs/royalemobiscroll/src/main/royale/",
			"../../royalelibs/royale-js-year-calendar/src/main/royale/",
			"../../royalelibs/royalefullcalendar/src/main/royale/",
			"../../royalelibs/royale-jscalendar/src/main/royale/",
			"../../royalelibs/royale-virtual-select/src/main/royale/",
			"../../royalelibs/royale-inspire-tree/src/main/royale/"
        ],
        "namespace": [
            {
                "uri": "library://ns.apache.org/royale/community",
                "manifest": "../../royalelibs/royalecomponents/src/main/resources/components-manifest.xml"
            },
			{
                "uri": "library://ns.apache.org/royale/community",
                "manifest": "../../royalelibs/royalemobiscroll/src/main/resources/mobiscroll-manifest.xml"
            },
            {
               "uri": "library://ns.apache.org/royale/community",
               "manifest": "../../royalelibs/royale-js-year-calendar/src/main/resources/year-calendar-manifest.xml"
            },
            {
                "uri": "library://ns.apache.org/royale/community",
                "manifest": "../../royalelibs/royalefullcalendar/src/main/resources/fullcalendar-manifest.xml"
            },
            {
                "uri": "library://ns.apache.org/royale/community",
                "manifest": "../../royalelibs/royale-jscalendar/src/main/resources/jscalendar-manifest.xml"
            },
            {
                "uri": "library://ns.apache.org/royale/community",
                "manifest": "../../royalelibs/royale-virtual-select/src/main/resources/virtual-select-manifest.xml"
            },
            {
                "uri": "library://ns.apache.org/royale/community",
                "manifest": "../../royalelibs/royale-inspire-tree/src/main/resources/inspire-tree-manifest.xml"
            }
        ],
        "library-path": [
            "${royalelib}/libs/MXRoyaleBase.swc"
        ],
        "js-library-path": [
            "${royalelib}/js/libs/MXRoyaleBaseJS.swc"
        ],
        "keep-as3-metadata": [
            "Inject", "Dispatcher", "EventHandler", "PostConstruct", "PreDestroy", "ViewAdded", "ViewRemoved", "Bindable", "Transient"
        ],
        "js-default-initializers": true,
        "define": [
            {
                "name": "BUILD::buildNumber",
                "value": "'buildNumber'"
            },
            {
                "name": "BUILD::buildVersion",
                "value": "'project.version'"
            }
        ],
        "source-map": true
    },
    "copySourcePathAssets": true,
    "additionalOptions": [
        "-js-dynamic-access-unknown-members=true",
        "-show-binding-warnings=false"
    ],
    "files":
    [
        "src/main/royale/App.mxml"
    ]
}
`

**Comment by joshtynjala** [comment]
Did you set the `as3mxml.sdk.framework` setting to the path of the Royale SDK that you are using?

**Comment by joshtynjala** [comment]
Do you get any notifications on the bottom right of your VSCode window when you open your workspace folder? If they've been hidden, you can click the bell icon. You should get errors about Royale or Java if you are using versions that are not supported.

**Comment by mjesteve** [comment]
Warnings:

`
mar 19, 2022 12:38:34 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
ADVERTENCIA: Unmatched cancel notification for request id 98
mar 19, 2022 2:34:37 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
ADVERTENCIA: Unmatched cancel notification for request id 403
mar 19, 2022 4:07:00 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
ADVERTENCIA: Unmatched cancel notification for request id 1676
mar 19, 2022 4:07:00 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
ADVERTENCIA: Unmatched cancel notification for request id 1677
mar 19, 2022 4:37:11 AM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFORMACIÓN: Unsupported notification method: $/setTrace
mar 19, 2022 4:37:11 AM org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint notify
INFORMACIÓN: Unsupported notification method: $/setTrace
mar 20, 2022 1:48:52 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
ADVERTENCIA: Unmatched cancel notification for request id 2560
mar 21, 2022 1:18:40 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
ADVERTENCIA: Unmatched cancel notification for request id 2665
mar 21, 2022 1:18:40 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
ADVERTENCIA: Unmatched cancel notification for request id 2666
mar 21, 2022 2:06:22 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation
ADVERTENCIA: Unmatched cancel notification for request id 2835
`

**Comment by joshtynjala** [comment]
That looks like content from the Output view. I don't see any issues there. Those messages are normal.

If you open up VSCode's command palette (Ctrl+Shift+P), you can run the "Notifications: Show Notifications" command to display the current notifications (they will appear on the bottom right).

**Comment by mjesteve** [comment]
No, no tengo ninguna notificación de error.
La única advertencia que tengo en las dos máquinas cuando adjunto la carpeta "/projects del SDK" es:

![image](https://user-images.githubusercontent.com/55754195/159311443-2d8fb758-3758-4af3-a566-3fe76c5cbbdc.png)

"The following folders in the work area will be skipped because they use task version 0.1.0: projects"

(Someday I'll change it in the SDK)

**Comment by joshtynjala** [comment]
> The following folders in the work area will be skipped because they use task version 0.1.0

I think that this is the issue. I can reproduce this issue if I add royale-asjs/frameworks/projects as a root folder to a multi-root workspace. I get that message, and there are no actionscript tasks available. However, if I open the same folder as a single-root workspace, I see the tasks.

I think that you need to upgrade these tasks.json files to version 2.0.0. It looks like Microsoft is trying to stop supporting version 0.1.0, and this is one place where they're already requiring version 2.0.0.

**Comment by joshtynjala** [comment]
Perhaps there is something missing from your Royale SDK that vscode-as3mxml is looking for. The following files are required in the root of a Royale SDK to display tasks:

- A file named _royale-sdk-description.xml_
- A _frameworks_ directory
- A _bin_directory

Do the following paths exist?

- _d:\Develop_Royale\Projects\Royale-SDK\royale-asjs\royale-sdk-description.xml_
- _d:\Develop_Royale\Projects\Royale-SDK\royale-asjs\frameworks_
- _d:\Develop_Royale\Projects\Royale-SDK\royale-asjs\bin_

**Comment by joshtynjala** [comment]
Does code intelligence work in the text editor when you open .as and .mxml files? For instance, you see a pop-up when you hover your mouse over a symbol? Do you get completion when you type . or press Ctrl+Space?

In other words, does everything else work properly, and it's only tasks that are missing? Or is everything not working?

**Comment by mjesteve** [comment]
yes, Yes, everything works

**Comment by joshtynjala** [comment]
Unfortunately, I don't have any more suggestions at this time.

**Comment by mjesteve** [comment]
Don't worry, I'm sure "at some point" some new clue will give us the answer.

I greatly appreciate it Josh.
