### ISSUE TITLE
Create a new ActionScript project

### ISSUE THREAD

**Issue by zabdoul60460** [BowlerHatLLC/vscode-as3mxml#594]
Hi,
I try to use AS3Mxml for the first time.
For training, I try to do a basic sample like an Adobe AIR desktop project (https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Create-a-new-ActionScript-project-in-Visual-Studio-Code-that-targets-Adobe-AIR-for-desktop-platforms).

I've done all step, for 1 to 7.

But, I'm not able to execute compilation task. Indeed, I can't see this option. See below all option available.
<img width="1009" alt="Capture d’écran 2022-03-23 à 14 10 31" src="https://user-images.githubusercontent.com/66958185/159711501-22aa6062-fe9f-45ba-9bfd-96073237f105.png">

<img width="270" alt="Capture d’écran 2022-03-23 à 14 32 49" src="https://user-images.githubusercontent.com/66958185/159711543-01f2c14c-46cf-438f-ac73-f9a3c0d248d4.png">

So could you help me to solve that.

Best regards

**Comment by joshtynjala** [comment]
Based on your screenshot, I can see that you have opened the command palette. The compile tasks are not commands. You need to go to the **Terminal** menu and choose **Run Task** or **Run Build Task**.

See the documentation here:

https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Build-an-ActionScript-project-in-Visual-Studio-Code

**Comment by zabdoul60460** [comment]
Thanks for this reply and sorry for my mistake
Now, I have some errors after compiling even if files are on directory.
<img width="868" alt="Capture d’écran 2022-03-23 à 15 37 07" src="https://user-images.githubusercontent.com/66958185/159762173-c5445e40-0d3d-4f28-ac7e-86b9ea35e19c.png">

Is it mandatory to merge Flex SDK 4.16 and Harman SDK ?
Best regards

**Comment by joshtynjala** [comment]
Yes, if you want to use AIR, you should merge the Flex SDK with the AIR SDK. Be sure to use the smaller version of the AIR SDK meant for Flex developers. Don't merge with the version of the AIR SDK that includes its own compiler, or you could run into conflicts.

**Comment by joshtynjala** [comment]
You may also need playerglobal.swc, if you don't already have it. I assume that you can get that from HARMAN too, but if not, I think it's still possible to download it from Adobe.

**Comment by joshtynjala** [comment]
I don't think that it would be safe to add the mx folder from Flex SDK 4.6. The SDK should generally be backwards compatible, but there may still be some conflicts.

I just checked, and Flex SDK 4.16.1 on my computer has mx/mx.swc. I also downloaded the binary distribution of Flex SDK 4.16.1 and it also has mx/mx.swc. Perhaps you accidentally deleted the mx folder. Maybe you should start with a fresh copy of Flex SDK 4.16.1.

**Comment by zabdoul60460** [comment]
Could you confirm that I must download SDK binaries  from this website (https://www.apache.org/dyn/closer.lua/flex/4.16.1/binaries/apache-flex-sdk-4.16.1-bin.tar.gz) and not sdk source code.
Best regards

**Comment by joshtynjala** [comment]
Yes, it is easier to download the binary distribution instead of building it yourself from source code. That is the correct URL to download it from.

**Comment by zabdoul60460** [comment]
Now all my SDK is right.
But when I try to package macOS release, this error appear 
/Documents/DevAIR/SDK/SDK Flex Hamran ILO/frameworks/air-config.xml(64): Erreur: impossible d'ouvrir '{airHome}/frameworks/libs/air/airglobal.swc' even if this file exist as you can see below
<img width="428" alt="Capture d’écran 2022-03-24 à 17 26 32" src="https://user-images.githubusercontent.com/66958185/159964000-b36b61b9-7e27-4432-8a47-d63cecfae55d.png">

Please could you help me.
Best regards

**Comment by joshtynjala** [comment]
Try removing `{airHome}/` from the path. I don't see that in my SDK's air-config.xml file.

I think that the Flex SDK Installer app (or running the Ant installer.xml script) would normally make a number of adjustments to the binary distribution to make it properly usable. I suspect that you downloaded the binary distribution and simply unzipped it, so there may be some extra steps that you need to do to adjust things manually.

**Comment by zabdoul60460** [comment]
Each time, I try to use Installer Apache Flex SDK, those errors
      appear :
    Installer path:
/private/var/folders/ms/df3v_qh940d6c9hbxbl5g8sr0000gn/T/AppTranslocation/7A2B66D3-2E81-4B10-AA99-55596DBB1DA6/d/Apache
        Flex SDK Installer.app/Contents/Resources
      Installer version 3.3.2 (mac)
      Using Locale: fr_FR
      L'URL de téléchargement du SDK à été récupérée à partir du
        CGI.
      Error #2031
      Installation interrompue:
http://flex.apache.org/track-installer.html?failure=true&label=Apache
        Flex SDK
4.16.1&version=4.16.1&os=mac&installerversion=3.3.2&info=Error
        #2031
      Do you know why ?
    Best regards
    
    
      
        
          
            
            
          
          
            
            
          
          
            
            
          
        
      
    
    Le 24/03/2022 à 17:46, Josh Tynjala a
      écrit :
    
    
      
      Try removing {airHome}/ from the path.
        I don't see that in my SDK's air-config.xml file.
      I think that the Flex SDK Installer app (or running
        the Ant installer.xml script) would normally make a number of
        adjustments to the binary distribution to make it properly
        usable. I suspect that you downloaded the binary distribution
        and simply unzipped it, so there may be some extra steps that
        you need to do to adjust things manually.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you authored the thread.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/BowlerHatLLC/vscode-as3mxml/issues/594#issuecomment-1077827804",
"url": "https://github.com/BowlerHatLLC/vscode-as3mxml/issues/594#issuecomment-1077827804",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by joshtynjala** [comment]
> Do you know why ?

Unfortunately, I have no idea.

**Comment by zabdoul60460** [comment]
Hi,
I found a solution SDK 4.16 (and not 4.16.1) may be downloaded  with Apache Flex SDK installer ...
Now a new problem appears when I try to package my demo application.
Indeed, compiler stop to work before the end with this message ;
`Arrêt du processus de terminal "/usr/bin/java '-jar', '/Users/isaloyer/.vscode/extensions/bowlerhatllc.vscode-as3mxml-1.11.1/bin/asconfigc.jar', '--sdk', '/Users/myusermac/Documents/DevAIR/SDK/4.16.0_Air 32', '--debug=false', '--project', '/Users/myusermac/Documents/DevAIR/Demo/asconfig.json', '--air', 'mac'". Code de sortie : 12.
`
Do you know how to solve that ?
Thanks for helping.
Best regards

**Comment by piotrzarzycki21** [comment]
@zabdoul60460 could you try our tool Moonshine SDK Installer to download Flex. Stable or nightly and let us know -> https://moonshine-ide.com/download-sdk-installer/

**Comment by joshtynjala** [comment]
@zabdoul60460 Please enable the `as3mxml.asconfigc.verboseOutput` setting in VSCode and share the full output of the build. Thanks!

**Comment by zabdoul60460** [comment]
> @zabdoul60460 could you try our tool Moonshine SDK Installer to download Flex. Stable or nightly and let us know -> https://moonshine-ide.com/download-sdk-installer/

Dear @piotrzarzycki21, thanks for your help. If I download Flex SDK (Harman AIR), may I overlaid onto a Flex SDK 4.16.1, or is it ready to use ?
Best regards

**Comment by piotrzarzycki21** [comment]
> > @zabdoul60460 could you try our tool Moonshine SDK Installer to download Flex. Stable or nightly and let us know -> https://moonshine-ide.com/download-sdk-installer/
> 
> Dear @piotrzarzycki21, thanks for your help. If I download Flex SDK (Harman AIR), may I overlaid onto a Flex SDK 4.16.1, or is it ready to use ? Best regards

What you have downloaded is already Flex SDK + Air, so it's ready to use.

**Comment by zabdoul60460** [comment]
> > > @zabdoul60460 could you try our tool Moonshine SDK Installer to download Flex. Stable or nightly and let us know -> https://moonshine-ide.com/download-sdk-installer/
> > 
> > 
> > Dear @piotrzarzycki21, thanks for your help. If I download Flex SDK (Harman AIR), may I overlaid onto a Flex SDK 4.16.1, or is it ready to use ? Best regards
> 
> What you have downloaded is already Flex SDK + Air, so it's ready to use.

I've downloaded the second item of Moonshine SDK installer.
![image](https://user-images.githubusercontent.com/66958185/160878645-226e3e91-479c-4d2f-b7cd-4d9f058eeb1c.png)
Best regards

**Comment by zabdoul60460** [comment]
Thanks for your help. Now demo sample works. I need to do the same with my air production project !
Best regards
