### ISSUE TITLE
关于SDK

### ISSUE THREAD

**Issue by Pamper321** [BowlerHatLLC/vscode-as3mxml#595]
你好，
我是一名在校大学生，我的老师让我们用layaair使用as编程做游戏，
但是我的代码水平非常低，必须借助代码提示。
但是我遇到一个问题，没有代码提示，我按照您的方法下载并配置SDK,但是我的vscode里并没有出现可用的SDK,于是我在HARMAN上下载了一个最新的SDK，解压缩后在vscode中添加SDK,但是配置完后出现了新问题
请问这是怎么回事
无法打开“h:\下载\AIRSDK_Flex_Windows\frameworks\js-config.xml”。
defaults (line: -1)

我是下载的最新的SDK33.1.1.795,好像并不是中文路径问题，因为我曾改过英文路径，还是行不通。
![Dingtalk_20220330112642](https://user-images.githubusercontent.com/102639807/160745771-844ca954-4aa2-4ba3-87e0-88f553e3737c.jpg)
![image](https://user-images.githubusercontent.com/102639807/160745820-f374da4a-dc06-4709-bcbc-161275f64fff.png)

**Comment by joshtynjala** [comment]
> Hello,
I am a college student, my teacher asked us to use layaair to use as programming to make games,
But my code level is very low and I have to resort to code hints.
But I encountered a problem, there is no code prompt, I downloaded and configured the SDK according to your method, but the available SDK did not appear in my vscode, so I downloaded a latest SDK on HARMAN, decompressed it in vscode Add the SDK to the , but a new problem occurred after the configuration
May I ask how is this going
Could not open 'h:\Downloads\AIRSDK_Flex_Windows\frameworks\js-config.xml'.
defaults (line: -1)
>
> I downloaded the latest SDK33.1.1.795, it doesn't seem to be a problem with the Chinese path, because I have changed the English path, but it still doesn't work.

I am have no experience with LayaAir. You should contact the creators of LayaAir for support with this tool.
