### ISSUE TITLE
Error : a target file should be indicate

### ISSUE THREAD

**Issue by zabdoul60460** [BowlerHatLLC/vscode-as3mxml#598]
When I try to package an Adobe AIR application an error appears.
<img width="312" alt="Capture d’écran 2022-03-30 à 23 07 12" src="https://user-images.githubusercontent.com/66958185/160933119-4b1af1fc-2397-427e-800a-74203440c712.png">

See below my asconfig.json

```json5
{
	"config": "air",
	"type": "app",
	"compilerOptions": {
		"source-path": [
			"src"
		],
		"output": "bin/Expert.swf"
	},
	"mainClass": "Expert",
	"application": "src/Expert-app.xml",
	"additionalOptions": "-locale=fr_FR,en_US",
	"copySourcePathAssets": true,
	
"airOptions": {
	
	"target": "native",
	"output": "bin/Expert6.3.dmg",
	"signingOptions": {
		"storetype": "pkcs12",
		"keystore": "SE_jfcjfc2048.p12"
	}

}
}
```

More details on terminal
_Erreur: Problème lors de la recherche de la feuille de style externe : /skin/1styles.css
  <fx:Style source="/skin/1styles.css"/>_

Thanks for helping.
best regards

**Comment by joshtynjala** [comment]
It is looking for either _src/Expert.as_ or _src/Expert.mxml_. Does one of these files exist? If not, are they in a package instead? For instance, if the `Expert` class is in `com.example` package, `mainClass` should be set to "com.example.Expert".

**Comment by zabdoul60460** [comment]
Yes Expert.mxml exist on the root of src directory.

**Comment by joshtynjala** [comment]
I'm afraid that I don't have any suggestions. Something in your project is misconfigured, but I don't know what it could be.

**Comment by joshtynjala** [comment]
Is asconfig.json located in the root of your project? You didn't accidentally create it at src/asconfig.json or somewhere else, right?

If there are any other errors, they may give you clues about what the actual problem is. Sometimes, this error is a side effect of a different issue.

**Comment by zabdoul60460** [comment]
See below terminal content 

```
Configuration file: /Users/isa/Documents/DevAIR/Expert/asconfig.json
Reading configuration file...
Validating configuration file...
Parsing configuration file...
Main class not found in source paths: Expert.mxml
Arrêt du processus de terminal "/usr/bin/java '-jar', '/Users/isa/.vscode/extensions/bowlerhatllc.vscode-as3mxml-1.11.1/bin/asconfigc.jar', '--sdk', '/Users/isa/Documents/DevAIR/SDK/Flex_4.16.1_AIR_33.1', '--debug=true', '--project', '/Users/isaloyer/Documents/DevAIR/Expert/asconfig.json', '--unpackage-anes=true', '--verbose=true'". Code de sortie : 1.

```

**Comment by joshtynjala** [comment]
Do you have `"mainClass": "Expert"` or `"mainClass": "Expert.mxml"`?

It should be `"mainClass": "Expert"`.

**Comment by zabdoul60460** [comment]
I don't know why but after restarted VSCode, this error disappear !
Thanks for helping.
Best regards
