### ISSUE TITLE
External CSS error and unknown property

### ISSUE THREAD

**Issue by zabdoul60460** [BowlerHatLLC/vscode-as3mxml#600]
Hi everyone,
It try to migrate my AIR project from Flex 4.6.
To customize my desktop application I have a an external css file named '1styles.css.
This file is calling on main class (mainApp.mxml) like this 
`    <fx:Style source="/skin/1styles.css"/>
`
My project directory Is like this 

```
MainLevel
      ____ assets
                        ____ skin
                                      1styles.css
                                      ____ assets
      ____ src
                     mainApp.mxml

```

When I try to launch compilation several message appear 
Impossible d’intégrer l’actif depuis "Embed("/../assets/icon_pulldown.png")".
![Capture d’écran 2022-04-15 à 15 41 22](https://user-images.githubusercontent.com/66958185/163577881-fdd9bf75-2092-4abb-aa3c-04d99740a9ca.jpg)

But as you can see on the screenshot on the line 553, the path is not the same on file and on debug terminal !

I have more than 250 errors like this on this css file. I think the problem is the same for all (path description but I don't know how to solve !).

Another point with this CSS file is about unknown property errors, for example those errors appears with paddingTop, paddingBottom, paddingLeft, paddingRight, vertical-gap and theme-color.
`s|WindowedApplication {
	paddingTop:0;
	paddingBottom:0;
	paddingLeft:0;
	paddingRight:0;
	vertical-gap:0;
	theme-color: #919191;
	font-family: main;
	color: #333333;
	font-size: 12;
	
}`

I have a similar problem with personal skin
```
@namespace windowSkin "fr.mycompagny.ui.windowSkin.*";

windowSkin|NativeTitleWindow
{
	skinClass:ClassReference("fr.mycompagny.ui.windowSkin.NativeTitleWinSkin");
}

```
In this cas unknown property error about skinClass appear !

So I neeed your help.
Thanks a lot.
Best regards.

**Comment by joshtynjala** [comment]
What if you try this instead?

```
Embed("/../assets/skin/assets/icon_pulldown.png");
```

A path starting with _/_ will be relative to the _src_ directory, so you were missing the top-level _assets_ directory in your relative path.

**Comment by joshtynjala** [comment]
I'm afraid that I don't have any further suggestions at this time.

**Comment by zabdoul60460** [comment]
I change the location of assets directory and reconfigured all paths and now those errors disappear ...
Best regards
