### ISSUE TITLE
Compile a debug build - Refresh terminal and problems list

### ISSUE THREAD

**Issue by zabdoul60460** [BowlerHatLLC/vscode-as3mxml#601]
Dear users, 
Each time before launch compile a debug build, I need before launch clean task.
if not errors on terminal and on problems window are not updated.
Do you have the same behavior ?
Best regards.

**Comment by joshtynjala** [comment]
The Problems view should update automatically when you change code in the .as or .mxml files. Building or cleaning the project should not affect the Problems view unless you have added a `problemMatcher` in your _tasks.json_ file (which you don't need to).

**Comment by zabdoul60460** [comment]
I found a solution : at the end of compiling, I enter on the keyboard and everything works !
Best regards
