### ISSUE TITLE
Package an Adobe AIR application for Mac OS and Windows

### ISSUE THREAD

**Issue by zabdoul60460** [BowlerHatLLC/vscode-as3mxml#604]
Hi,
I work on Mac OS with Visual Studio and I try to package a desktop applications for Windows and macOS that have a native installer. 
For that I update the file asconfig.json like that :
`
"airOptions": {
	"windows": {
		"target": "native",
		"output": "bin/Main.exe",
		"signingOptions": {
			"storetype": "pkcs12",
			"keystore": "windows_certificate.p12"
		}
	},
	"mac": {
		"target": "native",
		"output": "bin/Main.dmg",
		"signingOptions": {
			"storetype": "pkcs12",
			"keystore": "mac_certificate.p12"
		}
	}
}
`
But with this updated file any application is packaging, why ?
The task "Adobe Air - Package Mac OS Relase (native installer) work only with those options 👍 
`
	
"airOptions": {
	"target": "native",
	"output": "bin/SysExpert63-Build2204c.dmg",
	"signingOptions": {
		"storetype": "pkcs12",
		"keystore": "SE_jfcjfc2048.p12"
		
	
	},

	"files": [
		{"file": "src/app_icons/Logo16.png","path": "app_icons/Logo16.png"},
		{"file": "src/app_icons/Logo32.png","path": "app_icons/Logo32.png"},
		{"file": "src/app_icons/Logo48.png","path": "app_icons/Logo48.png"}
	]
}
`

So is it possible to package on the same computer for Mac OS and Windows or do I need to package on Mac OS for Mac OS and On Windows for Windows ?

Thanks for helping.
Best regards.

**Comment by joshtynjala** [comment]
> So is it possible to package on the same computer for Mac OS and Windows or do I need to package on Mac OS for Mac OS and On Windows for Windows ?

You need to package on macOS for macOS and on Windows for Windows.

By the way, if you have questions, can you use [Discussions](https://github.com/BowlerHatLLC/vscode-as3mxml/discussions) instead of Issues? Thanks!
