### ISSUE TITLE
Issues renaming MXML attributes

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/vscode-as3mxml#612]
Confirmed in a fresh installation of the latest VSCode with the ActionScript & MXML extension on Windows 10 x64.

When renaming MXML element IDs from the ActionScript side, all references in the ActionScript block are renamed, but the MXML attribute is not. When renaming an ID on the MXML element itself, a notification says 'You cannot rename this element'.

When renaming an attribute referencing another value e.g. event listener or bound property, the replaced text is offset by a character, causing the MXML to break.

![MXML Rename](https://user-images.githubusercontent.com/354051/179489401-65d8c930-4f99-4127-b15d-5075d71c4afb.gif)

**Comment by joshtynjala** [comment]
> When renaming MXML element IDs from the ActionScript side, all references in the ActionScript block are renamed, but the MXML attribute is not.

Confirmed.

> When renaming an ID on the MXML element itself, a notification says 'You cannot rename this element'.

Confirmed. I guess I must have forgotten implement MXML id renaming.

> When renaming an attribute referencing another value e.g. event listener or bound property, the replaced text is offset by a character, causing the MXML to break.

Confirmed. This appears to be a bug in the Royale compiler that powers code intelligence. The line is correct, but the column is off by one for attribute values.

**Comment by joshtynjala** [comment]
> When renaming an attribute referencing another value e.g. event listener or bound property, the replaced text is offset by a character, causing the MXML to break.

apache/royale-compiler@749763d1757b7afe759967092150b59bb520fc8c
