### ISSUE TITLE
Ability to cancel a Quick Compile task

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/vscode-as3mxml#615]
I have a few very large projects, which can take up to 30 seconds to compile. Occasionally I hit the Quick Compile shortcut only to find I missed something, but have to wait until the process completes before recompiling. Using the Quick Compile shortcut again during a running task doesn't cancel the first task and usually results in an error. How easy would it be to implement a cancel command?

**Comment by joshtynjala** [comment]
There's no ability to cancel built into the compiler shell, as far as I know. However, the compiler shell is a separate process, so I guess it's hypothetically possible to simply kill the running process to stop the compile. It's already started on demand, so killing it shouldn't have serious side effects.

**Comment by esidegallery** [comment]
OK, good to know, thanks!
