### ISSUE TITLE
Display information from ASDoc tags when hovering mouse over a symbol

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/vscode-as3mxml#616]
`@inheritDoc` - Display the description from the implemented or overridden method in hover (might get complicated with the below point however)

`@param` - Display as list in hover, and (if possible) for the highlighted parameter in Parameter Info.

`@return` & `@see` - Display in hover

**Comment by joshtynjala** [comment]
I assume by "quick info", you mean in the pop-up overlay that gets displayed when hovering your mouse over a symbol. I edited things to make that clear, since quick info is kind of a vague name.

**Comment by esidegallery** [comment]
Apparently Quick Info is the official term, but yeah it's pretty vague
