### ISSUE TITLE
Compilation: "Error: Could not find or load main class format" when "as3mxml.asconfigc.jvmargs" is not specified

### ISSUE THREAD

**Issue by Adolio** [BowlerHatLLC/vscode-as3mxml#619]
Hi Josh,

I recently noticed that several of my small projects weren't compiling anymore with the following error: 
`Error: Could not find or load main class format`

After few investigations I noticed that this is occurring only when the property `"as3mxml.asconfigc.jvmargs"` is missing in the `settings.json`. I'm using it that way in larger projects: `"as3mxml.asconfigc.jvmargs": "-Xms512M -Xmx1G"`

The verbose mode doesn't tell me more in the console. I'm using `ActionScript & MXML` `v1.13.0` and as I remember this wasn't the case few weeks ago.

Best,
Aurélien

---

Used `java` version:
```
java version "1.8.0_333"
Java(TM) SE Runtime Environment (build 1.8.0_333-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.333-b02, mixed mode)
```

**Comment by joshtynjala** [comment]
> After few investigations I noticed that this is occurring only when the property "as3mxml.asconfigc.jvmargs" is missing in the settings.json. I'm using it that way in larger projects: "as3mxml.asconfigc.jvmargs": "-Xms512M -Xmx1G"

This is the correct solution. For some reason, the JVM doesn't provide enough memory for larger projects, and manual intervention is required. It was the same with Flash Builder. I don't consider it a bug. It's just something that is needed sometimes.

**Comment by Adolio** [comment]
I totally agree for large projects (even if the error message is not clear and doesn't help do understand the root cause easily). 

👉 My main concern is the fact that it also occurs on a basic "Hello World" project. This might be very confusing for newcomers.

**Comment by joshtynjala** [comment]
> 👉 My main concern is the fact that it also occurs on a basic "Hello World" project. This might be very confusing for newcomers.

Unfortunately, I'm not able to reproduce this issue.

Does either your project's or SDK's absolute path contain the string "format"? I have no idea know what it's referring to with this message, but it feels more like an argument being parsed incorrectly than a low memory issue.

Can you copy the full verbose output so that I can take a look?

**Comment by Adolio** [comment]
Nice catch, apparently the term "format" is passed as a `jvmargs`.

Here is the full compilation out I get for a small template project:

```
 *  Executing task: C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe -jar c:\Users\Adolio\.vscode\extensions\bowlerhatllc.vscode-as3mxml-1.13.0\bin\asconfigc.jar --sdk c:/AIR/AIR_SDK_33_1 --debug=false --project d:\Adolio\Development\AIR\Starling-Template\asconfig.json --verbose=true --jvmargs="format" 

Configuration file: d:\Adolio\Development\AIR\Starling-Template\asconfig.json
Reading configuration file...
Validating configuration file...
Parsing configuration file...
SDK: c:\AIR\AIR_SDK_33_1
Processing Adobe AIR application descriptor(s)...
Initial window content: Starling-Template.swf
Descriptor: d:\Adolio\Development\AIR\Starling-Template\application.xml
Compiling application...
C:\Program Files\Java\jre1.8.0_333\bin\java format -Dflexcompiler=c:\AIR\AIR_SDK_33_1 -Dflexlib=c:\AIR\AIR_SDK_33_1\frameworks -jar c:\AIR\AIR_SDK_33_1\lib\mxmlc-cli.jar +flexlib=c:\AIR\AIR_SDK_33_1\frameworks --debug=false +configname=air --output=bin/Starling-Template.swf --default-background-color=#000000 --default-frame-rate=60 --swf-version=44 --source-path+=src --library-path+=lib -- src\Main.as
Error: Could not find or load main class format

 *  The terminal process "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe '-jar', 'c:\Users\Adolio\.vscode\extensions\bowlerhatllc.vscode-as3mxml-1.13.0\bin\asconfigc.jar', '--sdk', 'c:/AIR/AIR_SDK_33_1', '--debug=false', '--project', 'd:\Adolio\Development\AIR\Starling-Template\asconfig.json', '--verbose=true', '--jvmargs="format"'" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

The project's source if you need them: [Starling-Template.zip](https://github.com/BowlerHatLLC/vscode-as3mxml/files/9152245/Starling-Template.zip)

**Comment by Adolio** [comment]
So in a nutshell, when `as3mxml.asconfigc.jvmargs` is not set I get: `--jvmargs="format"`.

**Comment by joshtynjala** [comment]
Your Starling-Template project compiles for me without error. I do not see `--jvmargs="format"` in my output.

This suggests to me that you may have accidentally set `as3mxml.asconfigc.jvmargs` in your global VSCode settings. Alternatively, if this project is part of a workspace, `as3mxml.asconfigc.jvmargs` could be set in the _.code-workspace_ file.

**Comment by Adolio** [comment]
Oh Josh, you're right! I'm so sorry for the time you spent on this 😲

I honestly don't know how I ended up with this weird user config...

Thanks a lot & sorry again!
