### ISSUE TITLE
code intelligence for external script

### ISSUE THREAD

**Issue by zabdoul60460** [BowlerHatLLC/vscode-as3mxml#621]
Hi,
Why code intelligence (go to function) doesn't work when a function is declaring inside an external AS file.
For exemple : 

`	<fx:Script source="wMyScript.as"/>
`
Best regards

**Comment by joshtynjala** [comment]
I have no plans to add better support for external ‘ <fx:Script source="file.as"/>’. I recommend avoiding this construct and adding the source directly inside your .mxml files.
