### ISSUE TITLE
File.createTempDirectory permission

### ISSUE THREAD

**Issue by zabdoul60460** [BowlerHatLLC/vscode-as3mxml#623]
Hi,
I try to use File.createTempDirectory to create a temporary directory and a file inside it.
But both on Mac OS et PC the problem is the same. The new directory is on read only.

```
var temp:File = File.createTempDirectory();
 var file:File = new File(temp.nativePath + "/" + "lib.txt");
```
So in my exemple, lib.txt is not created.

Could you help me to change permission before create new file.

Best regards

**Comment by joshtynjala** [comment]
Please post in a forum for Adobe AIR. This is not a vscode-as3mxml issue.
