### ISSUE TITLE
Error: ....\src\Main.mxml is of an unsupported type: mxml | prelaunchTask 'Compile debug' terminated with exit code 2

### ISSUE THREAD

**Issue by blackjyn** [BowlerHatLLC/vscode-as3mxml#624]
I am migrating to VScode for AS3 development and creating mobile app project.
Just a simple hello world taste , tried to run via `Ctrl+Shift+B` + `F5` and Quick Compile ...
But I got this error:

```
Error: ....\src\Main.mxml is of an unsupported type: mxml 
```
also this error
```
prelaunchTask 'Compile debug' terminated with exit code 2
```

Env: 
- Windows x64 
- AIR SDK v33.1.1929
- Java 8 (1.8_311)

When I tried to build/run manually with `mxmlc +configname...`  it just runs fine. 
AND I did not change anything of `launch.json` nor `asconfig.json`

Please help

**Comment by blackjyn** [comment]
I use the Flex SDK with correct AIR for Flex SDK , but the problem still the same `Error: ....\src\Main.mxml is of an unsupported type: mxml 
`

again, when I tried to run the code from Flash Builder using the same SDK via `F11` it debugs perfectly without problem

**Comment by blackjyn** [comment]
also tried on Intellij IDEA, and it runs with no problems

**Comment by blackjyn** [comment]
Still no update on this? Please.. 
This migration isn't as smooth as I thought before, really frustrating so for workaround I just Ant build task.

**Comment by joshtynjala** [comment]
> Still no update on this?

@blackjyn Please be patient. I don't work on weekends, and if you respond on a Friday, you're probably not getting a response until Monday.

>  use the Flex SDK with correct AIR for Flex SDK , but the problem still the same Error: ....\src\Main.mxml is of an unsupported type: mxml

Please share the contents of your asconfig.json file.

**Comment by blackjyn** [comment]
Godnesss, I have to say sorry Josh.
After trying this and that, it turns out there's something wrong with my SDK setup that "just works" with FB , Intellij and FDT but NOT 

I was switching to the old Flex 4.6 inside VScode just to test and the project compiled successfully. 

Given that situation I suspect "was it the SDK?" 
and so I did fresh installation using Moonshine SDK Installer and then it works fine on VSCode.

Well I don't know why  the "broken SDK" setup  works in FB,INtellij and FDT but  not in the VSCode.

Sorry and thank you!
