### ISSUE TITLE
MXML docs on hover not showing 

### ISSUE THREAD

**Issue by blackjyn** [BowlerHatLLC/vscode-as3mxml#630]
it seems the MXML docs is not showing when we hover over on the tag/component unlike on the .as source file.

Does MXML docs still not supported or how do I enable it?

**Comment by blackjyn** [comment]
That's exactly the behavior I got

**Comment by joshtynjala** [comment]
Understood. I guess that I need to do something special to parse the asdoc from MXML that's a bit different from AS3. I'll keep it in mind for a future update.

**Comment by blackjyn** [comment]
Thanks Josh!

**Comment by blackjyn** [comment]
I confirm this has been fixed with v1.14.1!
Thank you Josh! 
![fixed](https://user-images.githubusercontent.com/6046191/197369421-11f56771-913f-462a-a88a-5f34a36b41b2.png)
