### ISSUE TITLE
It is recommended to add exclude files setting

### ISSUE THREAD

**Issue by ganyanchuan1989** [BowlerHatLLC/vscode-as3mxml#632]
I need to add exclusion files, such as `*.svn`,`*.copyarea.db`, how can I configure it .

**Comment by joshtynjala** [comment]
Exclude from what, exactly?

**Comment by ganyanchuan1989** [comment]
thank you for your reply.
I want is to provide a configuration file, like  git `.gitignore` file.  I can set the need to exclude files by myself.

**Comment by ganyanchuan1989** [comment]
thank you for your reply. I'm sorry for my poor English.

`ctrl + shift + b` The build will copy many files to `bin-debug`. My project has many `*.copyarea.db` files , I want to build project don't copying.

**Comment by joshtynjala** [comment]
Since I received no answer to my previous question, I'm going to close this issue. You should still be able to respond, though.
