### ISSUE TITLE
air-config.xml - unable to open .... frameworks\locale\en_GB

### ISSUE THREAD

**Issue by PippoApps** [BowlerHatLLC/vscode-as3mxml#635]
I get an error regarding some locale not found in framework...
I do not use as3mxml to compile so I can't say whether errors are triggered on compilation.
Though it is is annoying, I do like to have 0 errors and warnings :)

[{
	"resource": "/d:/AIR_SDK_WINDOWS/AIR_WINDOWS_33.1.1.544/frameworks/air-config.xml",
	"owner": "_generated_diagnostic_collection_name_#2",
	"code": "1319",
	"severity": 8,
	"message": "unable to open 'd:\\AIR_SDK_WINDOWS\\AIR_WINDOWS_33.1.1.544\\frameworks\\locale\\en_GB'.\nd:\\AIR_SDK_WINDOWS\\AIR_WINDOWS_33.1.1.544\\frameworks\\air-config.xml (line: 61)",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 1
}]

cheers

**Comment by joshtynjala** [comment]
Set the `locale` compiler option to "en_US". Your SDK probably doesn't have the "en_GB" locale.
