### ISSUE TITLE
the "override" keyword doesn't suggest super methods if the class constructor has multiline comment

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#640]
When the constructor (Command) has a multiline comment:

![image](https://user-images.githubusercontent.com/6010183/199962524-14d05234-92b6-4e94-b6ce-e126c9bb5d76.png)

When I remove the constructor comment:

![image](https://user-images.githubusercontent.com/6010183/199962800-d5d26059-d196-4bee-8e36-c84f33e6d8c3.png)

**Comment by ylazy** [comment]
[TestCodeHint.zip](https://github.com/BowlerHatLLC/vscode-as3mxml/files/9937847/TestCodeHint.zip)
I've attached an example .as file to reproduce the problem.

**Comment by joshtynjala** [comment]
Adding example code below so that I don't need to redownload the .zip file, if I ever need to revisit this issue in the future.

```as3
package
{
	import flash.events.EventDispatcher;

	public class TestCodeHint extends EventDispatcher
	{
		/**
		 * any comment
		 */
		public function TestCodeHint():void
		{
			super();
			
			
		}
		
		override 
	}
}
```
