### ISSUE TITLE
asformat: Adding 'finally' to try/catch block breaks formatting.

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/vscode-as3mxml#645]
The following code will break formatting:
![Try Catch Finally](https://user-images.githubusercontent.com/354051/203292249-4e9abdf8-5663-482e-b494-a1d0ef06067c.gif)

```
package
{
	public class Test
	{
		public function Test()
		{
			try
			{
				trace("start");
			}
			catch (error:Error)
			{
				trace("oops");
			}
			finally
			{
				trace("finish");
			}
		}
	}
}
```

**Comment by joshtynjala** [comment]
apache/royale-compiler@285681a5b9e56614a65e300909014c2eeaf3d7c5
