### ISSUE TITLE
[BUG] asconfig property in tasks is actually named jsonURI

### ISSUE THREAD

**Issue by piepie62** [BowlerHatLLC/vscode-as3mxml#647]
A task with a custom ASConfig needs to have its asconfig defined as "jsonURI" instead of "asconfig", which auto-completion shows.

Example of non-working task:
```
{
	"type": "actionscript",
	"asconfig": "asconfig.json",
	"label": "Compile Project"
}
```

Example of working task:
```
{
	"type": "actionscript",
	"jsonURI": "asconfig.json",
	"label": "Compile Project"
}
```

**Comment by joshtynjala** [comment]
`jsonURI` is not a field used by the "actionscript" task in vscode-as3mxml. That may be a field available in tasks for another language, but that doesn't mean that it's relevant to all languages.

The `asconfig` field is for when you want to use a custom file (like _asconfig.prod.json_ or _asconfig.custom.json_) where you can add any value in the middle of the `.` characters. If you want to use the default _asconfig.json_ file, then you simply need to omit the `asconfig` field. It will know to use _asconfig.json_ automatically.

```jsonc
{
	"type": "actionscript",
	"debug": true,
	"label": "Compile Project"
}
```

**Comment by piepie62** [comment]
No, I know that, I'm saying that the `asconfig` field isn't used properly. The example I gave was a bad one, given that I was using the default; I am actually trying to use `asconfig.BezelLibrary.json` but the key `jsonURI` is what allows me to use that field instead.

**Comment by joshtynjala** [comment]
> I am actually trying to use asconfig.BezelLibrary.json but the key jsonURI is what allows me to use that field instead.

jsonURI isn't a real field, though. There is no reference to `jsonURI` anywhere in the asconfigc codebase. This field is simply being ignored, and asconfigc is using _asconfig.json_ instead of _asconfig.BezelLibrary.json_.

> "asconfig": "${workspaceFolder}/asconfig.BezelLibrary.json",

The value of `asconfig` must exactly match a task generated by vscode-as3mxml. It is never a full path, so it would need to be `"asconfig": "asconfig.BezelLibrary.json"` without the `${workspaceFolder}/`.

-----

If you go to the **Terminal** menu and choose **Configure Tasks...**, you'll get a list of all of the generated tasks from vscode-as3mxml. You should see one named _ActionScript: compile debug - asconfig.BezelLibrary.json_. Choose that one, and it will insert the correct task configuration into your _tasks.json_ file.

**Comment by piepie62** [comment]
It doesn't, though; that doesn't insert the `asconfig` field, which means it'll just use the default `asconfig.json` for that task

**Comment by joshtynjala** [comment]
I have a project with an _asconfig.custom.json_ file. When I used **Configure Tasks...** to configure the _ActionScript: compile debug - asconfig.custom.json_ task, it added the following task to my _tasks.json_ file.

```json
{
	"version": "2.0.0",
	"tasks": [
		{
			"type": "actionscript",
			"debug": true,
			"asconfig": "asconfig.custom.json",
			"group": "build",
			"problemMatcher": [],
			"label": "ActionScript: compile debug - asconfig.custom.json"
		}
	]
}
```

As you can see, it populates the `asconfig` field correctly.

**Comment by piepie62** [comment]
Very interesting, it does not on my end. Very strange. Let me try doing this in a completely clean directory.

**Comment by joshtynjala** [comment]
> it does not on my end

And you are choosing the task that includes the _asconfig.BezelLibrary.json_ file name, right?

**Comment by piepie62** [comment]
I was, yes. I have no idea what changed, but rebuilding the package and reinstalling it several times with different combinations of my two PRs (one of which is used for this project) fixed it. I'm baffled, but at least it's not actually a problem that needs to be fixed.
