### ISSUE TITLE
Completion: Higher priority for classes that are already imported

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#648]
Hi!

My lib contains a class named StringUtil. When I type:

```as
import com.ylazy.utils.StringUtil;

Stringu
```

VSCode show `mx.utils.StringUtil` in a higher priority than `com.ylazy.utils.StringUtil`:

![image](https://user-images.githubusercontent.com/6010183/203886943-d62a5a57-2d07-479a-8f96-b80534e4bcb4.png)

I think it's better to make imported classes a higher priority than others.

Thanks!

**Comment by ylazy** [comment]
I want to add a similar case:

![image](https://user-images.githubusercontent.com/6010183/208816516-5d5758b2-7136-450d-b4a0-db2eb6615750.png)

The `validateSize` function should have the highest priority.

Thanks!

**Comment by ylazy** [comment]
Another case:

https://user-images.githubusercontent.com/6010183/209263023-47e5ad68-2d33-446a-8ac9-b0bb2f1d6ac0.mp4

The variable `_exist` should be there on the list but it isn't.
Workaround: insert `;` then try again.

**Comment by joshtynjala** [comment]
> The variable _exist should be there on the list but it isn't.
> Workaround: insert ; then try again.

Please open a separate issue for this one. Thanks!
