### ISSUE TITLE
Error Checking & Code Hint stop working with new .as file

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#655]
When I:
- Create a new text file then save as an ActionScript file.
- Save an existing ActionScript file as another .as file.

The following error occurred:

![image](https://user-images.githubusercontent.com/6010183/205480553-83f9b0f9-7c44-4ff3-8f60-51fa054dd11f.png)

Re-opening the file won't fix the problem. I have to restart VSCode.

**Comment by ylazy** [comment]
Hi!

It seems to be the issue happened after a symbol renaming failed.
I've attached a video for more detail.

https://user-images.githubusercontent.com/6010183/206363001-c9096c6a-6653-403c-a23f-be13b67b0e87.mp4

**Comment by joshtynjala** [comment]
So it looks like things have gotten into a bad state after symbol renaming fails, and that bad state is affecting the rest of the project. Your best bet when this happens is to restart VSCode or the AS3 & MXML language server.
