### ISSUE TITLE
Need a fast way to set the Main Class

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#656]
Hi!

It would be nice if we have something like this:

![image](https://user-images.githubusercontent.com/6010183/205481156-cd421bdd-02d1-4362-ba82-b433da3d26d2.png)

Much faster than editing asconfig.json. It's time-saving especially for testing purposes.

Thanks!

**Comment by joshtynjala** [comment]
Closing because I don't intend to add this feature.
