### ISSUE TITLE
Code completion doesn't work correctly with function name start with $ (dollar sign)

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#658]
Hi!

When I select a function named `$S` from the code completion:

![dollar](https://user-images.githubusercontent.com/6010183/206355941-ad088280-b65b-4fd9-9bbe-1594e411aef0.gif)

Similiar issue with `$M`, `$L`, `$XL`.
No issue with `$`.

**Comment by joshtynjala** [comment]
Note: To reproduce, the function must have at least one parameter, which causes the CompletionItem to be treated as a snippet (where $ is a special character that needs to be escaped).

```as3
public static function $S(a:Object):void {}
```
