### ISSUE TITLE
"Ctrl + Enter" "Ctrl + Shift + Enter" not working in non-as3 files

### ISSUE THREAD

**Issue by JiaChen-Zeng** [BowlerHatLLC/vscode-as3mxml#663]
I can't properly insert line above/below. Disabling the shortcut fixes it. The plugin shouldn't overwrite the behavior when it's not as3 files. And probably this default shortcut isn't good.

**Comment by joshtynjala** [comment]
There is a setting to disable these commands.

`"as3mxml.quickCompile.enabled": false`

Ctrl+Enter and Ctrl+Shift+Enter are standard keyboard shortcuts in Adobe Flash/Animate authoring tool, so they're being used for a good reason. I won't be changing it.

**Comment by JiaChen-Zeng** [comment]
That's not what this issue is about. I mean in non-as3 files, the plugin shouldn't overwrite those shortcuts.

**Comment by joshtynjala** [comment]
Oh, I see that the key bindings were still in effect if `as3mxml.quickCompile.enabled` is false. That will be fixed in the next version.
