### ISSUE TITLE
Error reading Adobe AIR application <id> for platform "android".

### ISSUE THREAD

**Issue by Shaunmax** [BowlerHatLLC/vscode-as3mxml#666]
When trying to debug the project on an android device I am getting : 

`Error reading Adobe AIR application <id> for platform "android". `

what could be the issue ? the same for iOS. 

But I am able to debug in AIR Simulator.

**Comment by joshtynjala** [comment]
Does your _asconfig.json_ file include the top-level [`application`](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/asconfig.json#application) field? That's where it tries to find the ID.

**Comment by Shaunmax** [comment]
> Does your _asconfig.json_ file include the top-level [`application`](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/asconfig.json#application) field? That's where it tries to find the ID.

No, this is the file : 
https://github.com/Gamua/Flappy-Starling/blob/master/asconfig.json

**Comment by joshtynjala** [comment]
The `application` field can be found here:

https://github.com/Gamua/Flappy-Starling/blob/master/asconfig.json#L14

I can see that it's looking for _src/FlappyStarling-app.xml_.

This line, in particular is where the id should be found:

https://github.com/Gamua/Flappy-Starling/blob/master/src/FlappyStarling-app.xml#L4

I think it is failing because the id contains a `-` character. I need to fix that.

If you want a temporary workaround for this issue, change the id to something that doesn't contain `-`.

**Comment by Shaunmax** [comment]
> 

No, I am still getting the same error. 

```
 <id>com.gamua.flappystarling</id> <!-- Bundle Identifier. Required. -->
    <filename>flappystarling</filename> <!-- Used as the filename for the application. Required. -->
    <name>Flappy Starling</name> <!-- The name that is displayed below the app icon. -->
    <versionNumber>0.0.1</versionNumber> <!-- Required. -->
```

**Comment by Shaunmax** [comment]
> > 
> 
> No, I am still getting the same error.
> 
> ```
>  <id>com.gamua.flappystarling</id> 
>     <filename>flappystarling</filename> 
>     <name>Flappy Starling</name> 
>     <versionNumber>0.0.1</versionNumber> 
> ```

Ok! after restarting the code editor its not showing the error.

**Comment by Shaunmax** [comment]
now, I getting the error : 
![image](https://user-images.githubusercontent.com/16576562/212988038-f06c1aba-94c1-4fc1-9943-c2c518b639d9.png)

'--air', 'android'" terminated with exit code: 12.

**Comment by joshtynjala** [comment]
According to [ADT error messages](https://help.adobe.com/en_US/air/build/WSBE9908A0-8E3A-4329-8ABD-12F2A19AB5E9.html), error code 12 means:

> Invalid input | Verify file paths and other arguments passed to ADT on the command line.

Most likely, some kind of path that you specified in asconfig.json is wrong.

If you want to see the full command generated from asconfig.json for ADT, set `as3mxml.asconfigc.verboseOutput` to `true` in VSCode's settings. It might give you some clues.

**Comment by Shaunmax** [comment]
I just added a new keystore file in the src folder. 

```
"mainClass": "FlappyStarlingMobile",
	"application": "src/FlappyStarling-app.xml",
	"airOptions": {
		"android": {
			"output": "out/flappy.apk",
			"listen": true,
			"signingOptions": {
				"storetype": "pkcs12",
				"keystore": "src/flappy_starling.p12"
			},
			"resdir": "system/res"
		}
```

additional information, I only see this : 
`WARNING: could not find appropriate Java Home location for v11+ JDK`

`c:\Users\mypc\Documents\GitHub\Flappy-Starling\out\FlappyStarling-app.xml: error 305: Intial window content SWF version 50 exceeds namespace version http://ns.adobe.com/air/application/33.1`

**Comment by joshtynjala** [comment]
> c:\Users\mypc\Documents\GitHub\Flappy-Starling\out\FlappyStarling-app.xml: error 305: Intial window content SWF version 50 exceeds namespace version http://ns.adobe.com/air/application/33.1

Looks like this is your issue. Change the namespace in FlappyStarling-app.xml to match your AIR SDK version.

**Comment by Shaunmax** [comment]
> > c:\Users\mypc\Documents\GitHub\Flappy-Starling\out\FlappyStarling-app.xml: error 305: Intial window content SWF version 50 exceeds namespace version http://ns.adobe.com/air/application/33.1
> 
> Looks like this is your issue. Change the namespace in FlappyStarling-app.xml to match your AIR SDK version.

Yes, I changed it to 50.1 but 

```
WARNING: could not find appropriate Java Home location for v11+ JDK
WARNING: could not find appropriate Java Home location for v8+ JDK
NOTE: The application has been packaged with a captive runtime.
```

![image](https://user-images.githubusercontent.com/16576562/213002704-6b38c22f-89f5-40b4-8ce4-84f550e26f88.png)

**Comment by joshtynjala** [comment]
Okay, since you see the captive runtime message, it means that compiling and packaging are completing successfully. Now you're having trouble with installation/launch on the device.

According to the docs page I linked above, ADT exit code 15 means:

> No devices | Verify that a device is attached and turned on or that an emulator is running.

There are several things to try:

1. Did you remember to connect the device to your computer with a USB cable?
2. Did you enable developer mode in the Android settings?
3. Is the device asking for any kind of permission to connect to your computer?
4. Disconnect and reconnect the USB cable.

**Comment by Shaunmax** [comment]
> 4\. Disconnect and reconnect the USB cable

this worked
