### ISSUE TITLE
mxml rename issue

### ISSUE THREAD

**Issue by varadig** [BowlerHatLLC/vscode-as3mxml#674]
I think something is wrong with the text selection on the renaming logic :) 

https://user-images.githubusercontent.com/6317148/222751642-9ba66070-436c-45ea-b43d-4f8b062f885e.mov

**Comment by joshtynjala** [comment]
Duplicate #612

This has been fixed in the Apache Royale compiler, which powers the code intelligence in vscode-as3mxml, and now I'm just waiting for them to release an update so that I can include the fix.
