### ISSUE TITLE
New language features cause syntax error

### ISSUE THREAD

**Issue by hydroper** [BowlerHatLLC/vscode-as3mxml#675]
For example, `x ?? y` is causing error at the right `?`. I'm using only one SDK

**AS&MXML version:** 1.15.0
**AIR SDK version:** 50.0.1.2
**Environment `AIR_HOME`:** C:\Dev\AIRSDK_Windows\AIRSDK_50.0.1.2
**Environment `FLEX_HOME`:** C:\Dev\AIRSDK_Windows\AIRSDK_50.0.1.2

I've only one SDK version installed locally. Plus running `asconfigc` reports no syntax error.

**Comment by joshtynjala** [comment]
Duplicate #633
