### ISSUE TITLE
Rename Symbol Action: Overridden methods are not renamed when renaming base method

### ISSUE THREAD

**Issue by Adolio** [BowlerHatLLC/vscode-as3mxml#684]
Hi Josh,

I just noticed that renaming a base method doesn't rename the overridden methods when renamed using the `Rename Symbol` action. This could be very useful when refactoring large code base.

![Screenshot_2023-05-03_10-02-57](https://user-images.githubusercontent.com/1126990/235862179-bef2e033-e6cb-43f2-8d93-0dae303c7b6f.png)

However, the `super` calls inside the overridden methods are renamed properly.

Best,
Aurélien

**Comment by joshtynjala** [comment]
Confirmed. I'll try to get it fixed.
