### ISSUE TITLE
Error renaming event class

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#697]
When I rename symbol `TickerEvent` to `FrameTickerEvent`, the Event tags in other classes were renamed incorrectly:

```as
	[Event(name = "onTick",			type = FrameTickerEventt")]
	[Event(name = "onTickStart",	type = FrameTickerEventt")]
	[Event(name = "onTickEnd",		type = FrameTickerEventt")]
```

expected result:

```as
	[Event(name = "onTick",			type = "FrameTickerEvent")]
	[Event(name = "onTickStart",	type = "FrameTickerEvent")]
	[Event(name = "onTickEnd",		type = "FrameTickerEvent")]
```

**Comment by joshtynjala** [comment]
It looks like the Royale compiler is providing the incorrect position. I'll need to fix it there first.

**Comment by joshtynjala** [comment]
apache/royale-compiler@e5a22fb81954f1d44a534a9080c5d62f22da8ea4
