### ISSUE TITLE
Don't force saving temporary tabs when start debugging

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#700]
When I start debuging my app, my temporary tabs (that are not saved as files) are prompted to save.
Please add an option to disable this behavior.

https://github.com/BowlerHatLLC/vscode-as3mxml/assets/6010183/0780f8dc-f986-43f6-af24-511114e897d2

Thank you!

**Comment by joshtynjala** [comment]
This behavior is controlled by VSCode. There's nothing I can do.

**Comment by ylazy** [comment]
Thank you!
For others: This can be controlled by the setting: `"testing.saveBeforeTest": false`
