### ISSUE TITLE
asformat: Error formatting MXML files

### ISSUE THREAD

**Issue by esidegallery** [BowlerHatLLC/vscode-as3mxml#701]
If the Script tag contents of an MXML file becomes too long (which isn't very long at all), formatting will break. Deleting code will allow it to work again. This occurs with both CRLF and LF line endings, though CRLF seems to be a little more sensitive than LF. Behaviour is quite inconsistent, as I can re-add code after it breaks and it will still work - up to a point at least.

![Animation](https://github.com/BowlerHatLLC/vscode-as3mxml/assets/354051/dd2b376d-8baf-454a-b0e7-323a61023946)

Here is the output from the error: [Error.txt](https://github.com/BowlerHatLLC/vscode-as3mxml/files/12273991/Error.txt)

And this is the file used in the animation above: [TileList.mxml.txt](https://github.com/BowlerHatLLC/vscode-as3mxml/files/12273996/TileList.mxml.txt)

I am using a Windows PC, and I have a feeling this error doesn't occur in macOS.

**Comment by joshtynjala** [comment]
I was able to reproduce a couple of times on macOS, but it's happening very inconsistently. It seems to happen every time on Windows.

**Comment by joshtynjala** [comment]
apache/royale-compiler@255bb4d040755184be0dfb176ac5608061bd1305

**Comment by esidegallery** [comment]
Is this now just a matter of waiting for the next Royale Compiler release?

**Comment by joshtynjala** [comment]
> Is this now just a matter of waiting for the next Royale Compiler release?

Yes.

**Comment by esidegallery** [comment]
Oh my, Christmas has come early! Thank you Josh
