### ISSUE TITLE
Using LSP with Sublime Text: MXML not recognized as source

### ISSUE THREAD

**Issue by blackjyn** [BowlerHatLLC/vscode-as3mxml#704]
I try to use the LSP with Sublime Text and follow the step here: 
https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/How-to-use-the-ActionScript-and-MXML-language-server-with-Sublime-Text

with slight modification I create an LSP entry : 
```js
"as3mxml": {
	"enabled": true,
	"command": [
		"java",
		"-Droyalelib=D:/DEVSDK/ApacheFlexSDK4161AIR55.1.2/frameworks",
		"-Dfile.encoding=UTF8",
		"-cp",
		"D:/VSCodeEPortable/data/extensions/bowlerhatllc.vscode-as3mxml-1.18.0/bundled-compiler/*;D:/VSCodeEPortable/data/extensions/bowlerhatllc.vscode-as3mxml-1.18.0/bin/*",
		"com.as3mxml.vscode.Main"
	],
	"selector": "source.actionscript.2"
}
```

The LSP triggered ONLY on ActionScript files and NOT MXML file.
What is the selector for MXML files?

ENV:
- Windows x64
- Sublime Text 4
- AIRSDK 55
- AS3MXML 1.18

**Comment by joshtynjala** [comment]
I have updated the Sublime Text page with the necessary configuration changes to enable MXML code intelligence too.

https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/How-to-use-the-ActionScript-and-MXML-language-server-with-Sublime-Text

**Comment by blackjyn** [comment]
Thanks Josh. Works nicely!
