### ISSUE TITLE
Syntax Checker does not respect CONFIG:: statements

### ISSUE THREAD

**Issue by alexpolmans** [BowlerHatLLC/vscode-as3mxml#710]
If the same function is defined within conditional code, the whole program gets marked with red underlines because the syntax checker thinks that two functions have been declared with the same name.

```
package
{
    public class TestClass
    {
CONFIG::desktop {
        public function Test() : void
        {
            trace( "I am desktop" );
        }
    } // end CONFIG::desktop

CONFIG::mobile {
        public function Test() : void
        {
            trace( "I am mobile" );
        }
    } // end CONFIG::desktop
} 
```

The asconfig.as file has only one of the conditions marked as true.

```
"define": [
			{
				"name": "CONFIG::mobile",
				"value": "false"
			},
			{
				"name": "CONFIG::desktop",
				"value": "true"
			},
```

The compiler itself respects the condition and compiles the code.

**Comment by joshtynjala** [comment]
Try true and false values without the quotes around them.

**Comment by alexpolmans** [comment]
Thank you Josh.   Rookie mistake.
