### ISSUE TITLE
Wiki Installation instructions for SDK location

### ISSUE THREAD

**Issue by velara3** [BowlerHatLLC/vscode-as3mxml#715]
On following install instructions for the first time, on the following page please add a link to download the sdk, 

https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Choose-an-ActionScript-SDK-for-the-current-workspace-in-Visual-Studio-Code

_"[Download Apache Royale here](https://royale.apache.org/download/), if you don't have it yet. Then restart VS Code"_

If you install only the extension, the sdk will not be listed in the command palette. 

<img width="546" alt="image" src="https://github.com/BowlerHatLLC/vscode-as3mxml/assets/1084127/fb6c1ccc-a24d-4b20-90d1-af78daa962d5">

Note: I don't know where the JS only option is coming from. I had Royale installed at one point. 

Also, on this page, https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Create-a-new-ActionScript-project-in-Visual-Studio-Code-that-targets-JavaScript-and-HTML, there were two errors from the extension in the problems view:  

 - "src path could not be found" 
 - "Main.as could not be found" 
 
 Restarting vscode solved the issues

**Comment by velara3** [comment]
Additionally, an instruction video may help new users.

**Comment by velara3** [comment]
Additionally, on this [page](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Debug-a-transpiled-ActionScript-project-in-Visual-Studio-Code-with-Google-Chrome), the Debugger for Chrome has been deprecated. It appears that it is replaced with an already installed VS code extension [JavaScript Debugger]( https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug). The instructions may be different.

**Comment by joshtynjala** [comment]
> On following install instructions for the first time, on the following page please add a link to download the sdk,

All of the supported ActionScript SDKs are linked at the top of that page. vscode-as3mxml supports more than just Royale, and there are links to the AIR SDK, Flex SDK, and the Feathers SDK too.

> Note: I don't know where the JS only option is coming from. I had Royale installed at one point.

The extension automatically searches a few common places where the SDK might be found, including Flash Builder's installation location, the PATH environment variable, FLEX_HOME, ROYALE_HOME, and possibly a couple more. It looks like you installed Royale from npm, which is automatically added to the PATH.

> there were two errors from the extension in the problems view

Interesting! I can reproduce this issue. I'll try to get it fixed.

**Comment by joshtynjala** [comment]
> Additionally, on this [page](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/Debug-a-transpiled-ActionScript-project-in-Visual-Studio-Code-with-Google-Chrome), the Debugger for Chrome has been deprecated. It appears that it is replaced with an already installed VS code extension [JavaScript Debugger](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug). The instructions may be different.

You are correct. The Debugger for Chrome extension is deprecated for the built-in JavaScript debugger. I removed the step that said that Debugger for Chrome should be installed. After that, I was able to follow all of the steps successfully with no changes required (though, just to be more clear, I mentioned that if you want to debug from a web server, you need to start it yourself). Chrome launched without specifying `runtimeExecutable` and breakpoints in the Main.as file were recognized correctly.

**Comment by joshtynjala** [comment]
At this point, I consider everything resolved. If you want to try the fix to creating a new project, you can download the latest nightly build from GitHub Actions, or you can build it yourself, if you prefer.

**Comment by velara3** [comment]
I did get the debugger to work. But I had to add the path in "webRoot": "/bin/js-debug" to the end of the url (full url - "localhost/bin/js-debug/") in the browser for it to work. It immediately hit the breakpoint. It works great btw.

**Comment by velara3** [comment]
Side Note: Upon clicking on the Global variables text OSX displayed a message about microphone access: 

 
<img width="843" alt="image" src="https://github.com/BowlerHatLLC/vscode-as3mxml/assets/1084127/6206f38d-de0b-43eb-8ea4-6d510d819057">
