### ISSUE TITLE
Live source update: added .as source files not considered for libraries

### ISSUE THREAD

**Issue by hydroper** [BowlerHatLLC/vscode-as3mxml#716]
# Problem

When I add an .as source file while editing a SWC project, I get this at the package word:

> A fatal error occurred. Error checking has been disabled, except for simple syntax problems.

I have this `asconfig.json`, but I experience the issue when editing any SWC library:

```json
{
    "config": "air",
    "type": "lib",
    "compilerOptions": {
        "include-sources": ["src"],
        "library-path": ["libs"],
        "output": "swc/org.agera.crypto.swc"
    }
}
```

## Workaround

Re-open the editor to detect added `.as` source files.

**Comment by joshtynjala** [comment]
Does it make any difference if you add `"source-path": ["src"]` to your compiler options?
