### ISSUE TITLE
Display code hinting inside type checking block

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#717]
Hi!

Just an idea. Is it possible for type inference in these cases?

```as
var object:*;

if (object is ActionButton)
{
  object. // display code hint for ActionButton without (object as ActionButton) needed.
}
else if (object is Button)
{
  object. // display code hint for Button without (object as Button) needed.
}
```

Thanks!

**Comment by joshtynjala** [comment]
This would need to be modified in the Royale compiler. While vscode-as3mxml could probably hack something together without compiler changes when `object` is of type `*` or `Object`, when it's a non-dynamic class, it requires a cast.
