### ISSUE TITLE
Defining a flat output and to a flat output path

### ISSUE THREAD

**Issue by velara3** [BowlerHatLLC/vscode-as3mxml#719]
In my application I have setup as following (before compilation): 

```
/project 
   asconfig.json
   /src
      - MyApp.as
      - myapp.html
   /public
       /js
```

I want to output to a single .js file to the /public/js directory but I'm getting the following error:  

```
Internal error: java.lang.RuntimeException: Unable to create release directory at /public/js/bin/js-release org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyalePublisher.setupOutputFolder(MXMLRoyalePublisher.java:1103)org.apache.royale.compiler.internal.codegen.mxml.royale.MXMLRoyalePublisher.getOutputFolder(MXMLRoyalePublisher.java:182)org.apache.royale.compiler.clients.MXMLJSCNative.compile(MXMLJSCNative.java:403)org.apache.royale.compiler.clients.MXMLJSCNative._mainNoExit(MXMLJSCNative.java:248)org.apache.royale.compiler.clients.MXMLJSCNative.mainNoExit(MXMLJSCNative.java:205)org.apache.royale.compiler.clients.MXMLJSC._mainNoExit(MXMLJSC.java:382)org.apache.royale.compiler.clients.MXMLJSC.mainNoExit(MXMLJSC.java:281)org.apache.royale.compiler.clients.MXMLJSC.staticMainNoExit(MXMLJSC.java:241)org.apache.royale.compiler.clients.MXMLJSC.main(MXMLJSC.java:220)
```

I'm using the [js-output](https://github.com/BowlerHatLLC/vscode-as3mxml/wiki/asconfig.json#js-output) compiler option:  

```
{
	"config": "js",
	"compilerOptions": {
		"debug": true,
		"source-path": [
			"src"
		],
		"js-output": "/public/js",
		"html-template": "template.html",
		"source-map": true
	},
	"mainClass": "LoginApp"
}
```

What I want:  

```
/project 
   asconfig.json
   /src
      MyApp.as
      myapp.html
   /public
      /js
            MyApp.js
      myapp.html
```

**Comment by velara3** [comment]
The way typescript does it is if you have a file, myapp.ts, it will compile that to myapp.js. It's very basic but very simple. You don't even need a tsconfig (I believe). 

Project before compilation:  
```
/project 
   myapp.ts
```

After compilation:  
```
/project 
   myapp.ts
   myapp.js
```

**Comment by joshtynjala** [comment]
A starting slash is probably considered an absolute path by the compiler:

```json5
"js-output": "/public/js",
```

Did you try this?


```json5
"js-output": "public/js",
```

**Comment by velara3** [comment]
That's what I have now: 

```
{
	"config": "js",
	"compilerOptions": {
		"debug": false,
		"source-path": [
			"src"
		],
		"js-output": "public/js",
		"html-template": "astemplate.html",
		"source-map": true
	},
	"mainClass": "MyApp"
}
```

This is the output: 

<img width="150" alt="image" src="https://github.com/BowlerHatLLC/vscode-as3mxml/assets/1084127/ed48a27e-6cde-42a0-9191-7434ab3592ce">

It publishes to the /public/js folder the sub folders /bin/js-debug/

```
/project
    /src
      - myapp.as
    /public
       /js
          /bin
             /js-debug
                /library
                /org
             - index.html
             - myapp.as
             - myapp.as.map
```

What I'd like if possible is: 
```
/project
    /src
      - myapp.as
      - myapp.js
```

Or:  

```
/project
    /src
      - myapp.as
    /public
       /js
         - myapp.as
         - myapp.as.map
```

In this case, the html page is already built and in the public directory. So I just need to get the js app into the root or sub directory of the index page if possible. 

Side note:  What are, /library and /org used for? Can they not be exported in debug?

**Comment by joshtynjala** [comment]
> What I'd like if possible is export one single js in the same directory or to the /public directory:

Royale does not currently support outputting a single JS file in a specific directory. It will always create js-debug, js-release, or both. If you do a release build, it will generate a single JS file, but it will go in the js-release directory.

You'll need to open a feature request for https://github.com/apache/royale-compiler. vscode-as3mxml has no control over how Royale outputs its JS code. 

> In this case, the html page is already built and in the public directory.

If you have your own HTML page, you can omit the html-template compiler option (or possibly set it to an empty string), and the Royale compiler won't create its own index.html.

> Side note: What are, /library and /org used for? Can they not be exported in debug?

I believe that library contains the Google Closure Library, which Royale depends on. The org directory probably contains the classes from org.apache.royale.* package. The `Language` class, in particular, is needed even if you aren't using the Royale framework. It provides implementations of some of the features of AS3 that aren't native to JS.
