### ISSUE TITLE
Inline source maps

### ISSUE THREAD

**Issue by velara3** [BowlerHatLLC/vscode-as3mxml#721]
When I compile to a release or debug build the output contains a source map like so: 

```
/bin
/bin
  /js-release
     - Main.js
     - Main.js.map
```

Is there a way to specify the source to be inline? 

Typescript adds something like this to the end of the js file: 

```
//# sourceMappingURL=data:application/json;base64,abc...abc==
```

**Comment by joshtynjala** [comment]
The compiler generates source maps. Open a feature request here: apache/royale-compiler
