### ISSUE TITLE
The file belongs to an unsupported type: mxml

### ISSUE THREAD

**Issue by panjunqiao** [BowlerHatLLC/vscode-as3mxml#722]
![image](https://github.com/BowlerHatLLC/vscode-as3mxml/assets/8489040/a8b5039a-aa79-43d2-85ee-c1baad6a29e8)

**Comment by joshtynjala** [comment]
It looks like you are using the _AIR SDK and Compiler_. That is AS3 only. I think that you meant to use the _Flex SDK_ instead. It supports AS3 and MXML.

**Comment by panjunqiao** [comment]
the problem has been resolved,thank you very much.
