### ISSUE TITLE
AIR 50.2 - Drag and Drop - Windows 11

### ISSUE THREAD

**Issue by zabdoul60460** [BowlerHatLLC/vscode-as3mxml#723]
Hi, 
Do you know why since I upgrade Windows and AIR SDK and runtime, drag and drop doesn't works.
Indeed a red [Ø] appear on target.
The same code works very well with Mac OS and it worked before the update.
Many thanks in advance.
Best regards.

**Comment by joshtynjala** [comment]
This is a better place to ask your question:

https://github.com/airsdk/Adobe-Runtime-Support/discussions
