### ISSUE TITLE
Completion: Ordering improvement for fully present terms

### ISSUE THREAD

**Issue by Adolio** [BowlerHatLLC/vscode-as3mxml#729]
Hi Josh, happy new year to you 🎉

---

Here is small improvement request to prioritize terms that are fully present in the results list of the completion feature. 

In this example, the results of the term `TOP` don't seem to be prioritized properly:
![Top](https://github.com/BowlerHatLLC/vscode-as3mxml/assets/1126990/c5d81232-867c-4aec-a25a-cf4ee06eda50)

Same here with `LEVELOPTION` where `LEVEL` and `OPTION` terms seems to be "consumed" separately first:
![LevelOptions](https://github.com/BowlerHatLLC/vscode-as3mxml/assets/1126990/1d1dbd70-1d0b-43d1-8775-f1530351231c)

Thanks in advance,

Best,
Aurélien

**Comment by joshtynjala** [comment]
VSCode is prioritizing them like this. It is not my code in vscode-as3mxml that is doing it.

**Comment by Adolio** [comment]
Good to know, thanks!
