### ISSUE TITLE
<mx:DataGrid and gestureTwoFingerTap

### ISSUE THREAD

**Issue by zabdoul60460** [BowlerHatLLC/vscode-as3mxml#734]
Hi,
With flex 4.7, I uses gestureTwoFingerTap event.
But with As3Mxml this event is ignored ?
Do you know why ? 
Many thanks in advance.
Best regards.

**Comment by joshtynjala** [comment]
Can you explain in more detail what you mean by "this event is ignored"? Can you share some code and possibly any error messages that you see? Thanks!

**Comment by zabdoul60460** [comment]
Find below a screenshot who explain there error.

**Comment by zabdoul60460** [comment]
Dear Josh,

Find below a screenshot to explain error.

dg

Best regards


      IsabelleLOYER

I










Le 06/02/2024 à 17:47, Josh Tynjala a écrit :

**Comment by joshtynjala** [comment]
I did not receive a screenshot. I don't think that you can attach a screenshot by replying via email. You must attach it on the GitHub issue page.
