### ISSUE TITLE
Build task failing because Adobe Animate not found

### ISSUE THREAD

**Issue by Notexe** [BowlerHatLLC/vscode-as3mxml#735]
I've tried setting `"as3mxml.sdk.animate": "C:\\Program Files\\Adobe\\Adobe Animate 2024\\Animate.exe"` in VSCode's settings.json file but that hasn't helped at all. Is there something I am missing? My asconfig.json looks like this:
```json
{
	"animateOptions": {
		"file": "basic.fla"
	},
	"compilerOptions": {
		"source-path": [
			"src"
		]
	},
	"mainClass": "basic_Main"
}
```

Thanks! Also unrelated but is it somehow possible to define multiple fla files in the same asconfig?

**Comment by Notexe** [comment]
Nvm.... I thought the file field for the fla was relative based on the source-path field. I've moved the fla file out of the src folder and now it finds adobe animate.

**Comment by joshtynjala** [comment]
> Also unrelated but is it somehow possible to define multiple fla files in the same asconfig?

No, but you can create multiple asconfig files. Just add an extra . and string before the file extension, like asconfig.customstring.json.

**Comment by Notexe** [comment]
> > Also unrelated but is it somehow possible to define multiple fla files in the same asconfig?
> 
> 
> 
> No, but you can create multiple asconfig files. Just add an extra . and string before the file extension, like asconfig.customstring.json.

Oh awesome, thank you!
