### ISSUE TITLE
Support to Flash Builder old SDKs were dropped?

### ISSUE THREAD

**Issue by GonzalezAtWork** [BowlerHatLLC/vscode-as3mxml#740]
When I try to build an mxml project suing the 4.6 SDK for Flex / Flash Builder, I get this error:

Configuration options in asconfig.json require Apache Royale or FlexJS. Path to SDK is not valid: c:\Program Files (x86)\Adobe Flash Builder 4.6\sdks\4.6.0

can someone point me on the right direction?

Thanks!

**Comment by joshtynjala** [comment]
>  Support to Flash Builder old SDKs were dropped?

They will never be dropped, if I can help it!

> Configuration options in asconfig.json require Apache Royale or FlexJS. Path to SDK is not valid: c:\Program Files (x86)\Adobe Flash Builder 4.6\sdks\4.6.0

This message is saying that you have some field or value in your asconfig.json that is available to Royale projects only, and it can't be used with Flex or other non-Royale SDKs.

Can you share the contents your asconfig.json file?
