### ISSUE TITLE
Option to "ACTIONSCRIPT SOURCE PATH" always visible

### ISSUE THREAD

**Issue by SolidSoft-Lda** [BowlerHatLLC/vscode-as3mxml#742]
Hi,

Based on https://github.com/BowlerHatLLC/vscode-as3mxml/issues/351, the panel "ACTIONSCRIPT SOURCE PATH" is not always open, however on my case I'm using VS Code only for ActionScript and .NET (that is always open).

Would be nice to have an option to force the actionscript source path to be always open (I would active on my case).

Thank you.

**Comment by Adolio** [comment]
+1 for this as well.

On my side I don't always understand why sometimes the section disappears. Also, it would be super nice if, when configured, the currently focused source file gets automatically selected in the `ACTIONSCRIPT SOURCE PATH` hierarchy too.

**Comment by joshtynjala** [comment]
ActionScript Source Path is visible when an .as or .mxml file is the currently active text editor. I found it annoying when I was working on a project in another language, and it was always visible (even though it wasn't relevant to that workspace, and the extension hadn't even been activated).

**Comment by joshtynjala** [comment]
> Also, it would be super nice if, when configured, the currently focused source file gets automatically selected in the ACTIONSCRIPT SOURCE PATH hierarchy too.

I tried to implement this, but unfortunately, I couldn't figure it out.

**Comment by SolidSoft-Lda** [comment]
> ActionScript Source Path is visible when an .as or .mxml file is the currently active text editor. I found it annoying when I was working on a project in another language, and it was always visible (even though it wasn't relevant to that workspace, and the extension hadn't even been activated).

C# Dev Kit is always visible and I think is super intuitive this way.
There is no possibility to have a configuration that one could activate to be always visible ?
This way we would have the best for both worlds and perhaps you could add more parameters in the future if you need it.
