### ISSUE TITLE
Context menu for clean, compile debug and compile release

### ISSUE THREAD

**Issue by SolidSoft-Lda** [BowlerHatLLC/vscode-as3mxml#743]
Sugestion:
Context menu for clean, compile debug, compile release

Example in the printscreen (this example was taken from C# Dev Kit extension):
<img width="424" alt="Screenshot 2024-03-13 at 20 02 09" src="https://github.com/BowlerHatLLC/vscode-as3mxml/assets/32980209/7352d5c4-f08f-4531-930c-77cc3c7c0ab1">

**Comment by joshtynjala** [comment]
Marking as won't fix. VSCode exposes tasks in the GUI in a particular way, and I don't want to duplicate that functionality somewhere else.
