### ISSUE TITLE
Cannot rename a variable if it is declared in "for each in"

### ISSUE THREAD

**Issue by pngdrift** [BowlerHatLLC/vscode-as3mxml#754]
[Screencast_20240713_002117.webm](https://github.com/user-attachments/assets/0008f6b9-a8e8-4075-af6d-34067feb76a5)

Cannot rename a variable if it is declared in "for each in", but if you rename variable inside the brackets, then it works.

**Comment by joshtynjala** [comment]
Good find! Thanks. I'll investigate.

**Comment by joshtynjala** [comment]
Fixed in apache/royale-compiler@6679e22713dacaf9ddcb4fb1fdc8517a78b82006

This fix will be included in a version of vscode-as3mxml after the next Apache Royale version is released.
