### ISSUE TITLE
Need a setting to display multiline comments without <p></p>

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#762]
Hi!

In JavaScript I can use two newline chars to split paragraphs.

![image](https://github.com/user-attachments/assets/440a261b-7b64-4b13-9227-2118ee4ccf43)
![image](https://github.com/user-attachments/assets/8a28b65e-01fd-4fd1-8f7b-628c533f3b1d)

This's very useful. Because on most cases I don't want to write the standard ASDoc. I just want to describe my variables/properties/methods to get the hint when I hover my symbols.

![image](https://github.com/user-attachments/assets/8fb8d062-2300-4c43-ab42-24d247fe7d9c)

I know that I can use `<p></p>` but It's inconvenion and take too much time. Especially I'm building libs and copying so many description from Internet. And I have to edit them over and over again.

So... Please consider to add an option to support the behavior above. And, if possible, another option: "display comments as you type" and we can simply use "Enter" to add line breaks (one newline instead of two).

Thank you!!!

**Comment by joshtynjala** [comment]
> And, if possible, another option: "display comments as you type"

Can you explain this one in more detail? I'm not sure what you mean. Thanks!

**Comment by ylazy** [comment]
It means, if a comment does not contains any ASDoc Tags, or the symbol is not in `public` namespace (e.g. private, protected vars/consts/methods/properties), then

```as
/**
 * Optional. A sequence of any of the following characters:
 * 
 * `-` - Makes the output left-justified by adding any padding spaces to the right instead of to the left.
 * `+` - Causes positive numbers to always be prefixed with "+".
 * ` ` - (A space character) This prefixes a space to positive numbers, primarily so that the digits can be lined up with the digits of negative numbers.
 * `0` - Pads numbers with zeroes on the left.
 * `,` - Groups digits (for example by thousands) and puts separators between the groups.
 */
var flags:String = found.resultGroups[2];
```

should be displayed like this:

![image](https://github.com/user-attachments/assets/ba1d0e10-401b-453d-8209-a27740f98d51)

- It allows MarkDown formats (default by VSCode)
- It doesn't need to put paragraphs in `<p></p>` (important)
- It allows extra linebreaks. It's what I mean "as you type". You press `Enter` twice then it should be two linebreaks (one empty line). (if possible)

Currently, to get the above displayed result, I have to write:

```as
/**
 * <p>Optional. A sequence of **any** of the following characters:</p>
 * <p> <p>
 * <p>`-` - Makes the output left-justified by adding any padding spaces to the right instead of to the left.</p>
 * <p>`+` - Causes positive numbers to always be prefixed with "+".</p>
 * <p>` ` - (A space character) This prefixes a space to positive numbers, primarily so that the digits can be lined up with the digits of negative numbers.</p>
 * <p>`0` - Pads numbers with zeroes on the left.</p>
 * <p>`,` - Groups digits (for example by thousands) and puts separators between the groups.</p>
 */
```

Thanks!

**Comment by joshtynjala** [comment]
This sounds like a roundabout way to say that you would like ASDoc comment to be parsed as Markdown, which you already requested in #639. I'm going to close this as duplicate.

**Comment by ylazy** [comment]
I don't think it's duplicate because this case is about comments that does not need to export/generate to documentation. And https://github.com/BowlerHatLLC/vscode-as3mxml/issues/639 is about comments that does need to export/generate to documentation.

**Comment by joshtynjala** [comment]
> In this case MarkDown has been supported already by VSCode, as you can see in the image above.

That's not intentional, and I consider it a bug in vscode-as3mxml.
