### ISSUE TITLE
Error when renaming a function

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#764]
Hi!

When I renamed `input` to `Input`

![image](https://github.com/user-attachments/assets/8a6aceb8-93ee-450a-b198-6872ac94864e)

The result:

![image](https://github.com/user-attachments/assets/d32e069e-62e0-4212-a210-f5ff72c7e61e)

The actual result is: `XInputt`
The expected result is: `X.Input`

Please review this.

Thank you!

**Comment by joshtynjala** [comment]
Unfortunately, I am unable to reproduce this issue when I try to recreate the code from your screenshot in my editor. Can you share a simple example that can reproduce the issue? Thanks!

**Comment by ylazy** [comment]
Unfortunately if I create a simple example then the renaming is correct. The function Input is put inside a class called `Tools` that is referencing to hundreds of files. I'll try to create a more complex example to see if the problem happen again. If yes I'll create a new issue.

Thank you!

**Comment by joshtynjala** [comment]
> If yes I'll create a new issue.

Please continue to comment on this issue if you see the problem happen again and can reproduce. Thanks!
