### ISSUE TITLE
Connection to server got closed. Server will restart

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#768]
Today when I open my project on another pc, I got this Error:

```
[Info  - 4:26:48 PM] Connection to server got closed. Server will restart.
[Error - 4:26:48 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:26:48 PM] ActionScript & MXML Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:26:48 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Trace - 4:26:48 PM] Sending request 'initialize - (0)'.
```

It happens 5 times then:

```
[Error - 4:26:48 PM] The ActionScript & MXML Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 4:26:48 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:26:48 PM] ActionScript & MXML Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 4:26:48 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
```

![image](https://github.com/user-attachments/assets/eb73e18c-3703-4625-909d-f108562d066d)

The full log:

[crash.log](https://github.com/user-attachments/files/16976999/crash.log)

I tried to use another as3mxml versions
tried to use another vscode versions
tried to move my project to another location
tried to delete `C:\Users\%username%\.vscode` and restart VSCode
tried to restart the computer
but still the same.

The `java -version` is `1.8.0_421`.

I'm using the VSCode Portable latest. (My laptop using the same VSCode Portable + AS3MXML version but it's working fine)

The issue still remain with an empty project.

What I should do now?

Thank you!

**Comment by joshtynjala** [comment]
Are you using vscode-as3mxml from the Marketplace? Or are you using a version built from GitHub source? If it's from GitHub source, then JDK 11 is now required.

**Comment by ylazy** [comment]
I'm using vscode-as3mxml from the Marketplace.

Thanks!

**Comment by ylazy** [comment]
The hard part is I don't have admin right on that pc. The pc is using an antivirus so I think the issue may related to the antivirus software since it can prevent some processes from running. But other extensions is working fine. I'll check to see if it's blocking java or not.

Thanks!
