### ISSUE TITLE
Creating custom projects from Project Templates

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#771]
Hi!

FlashDevelop allows me to define project templates to create custom projects.

Please consider to add support for this.

Thank you!

**Comment by joshtynjala** [comment]
Have you considered using another extension, like this one?

https://marketplace.visualstudio.com/items?itemName=cantonios.project-templates

**Comment by ylazy** [comment]
Thank you for your suggestion!
