### ISSUE TITLE
Performance issue with an .swc that contains many (18,000+) Sprites

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#779]
Hi!

If I include the attached .swc below in my project, the performance will be decreased very much. I see a long delay with code hinting, error checking... On my machine, sometimes it delays >10 seconds.

The AS3MXML server takes a long time for unpacking and analyzing the .swc, and sometimes it takes up 1-2gb more space. I'm ok with that. But when it's finished, it still affect to the performance.

Is it possible for you to do more optimization for this? If it's not possible, is there anyway to disable code hinting for specific classes? For example, disable code hinting for these icon classes and only show code hint for them when ctrl+space pressed? Or any other way to improve the performance?

Thank you!

[FluentIcons.zip](https://github.com/user-attachments/files/17459487/FluentIcons.zip)

**Comment by joshtynjala** [comment]
Commit 3c37e127cb1d472b0fc15018ae8346c5e1677510 should improve the performance for completion with FluentIcons.swc in the library-path. On my machine, I measured a drop from about 300ms to about 30ms.

**Comment by ylazy** [comment]
It's ~15x faster on my machine.

Thank you!!!
