### ISSUE TITLE
Support [Exclude tags

### ISSUE THREAD

**Issue by ylazy** [BowlerHatLLC/vscode-as3mxml#781]
Hi!

The completion engine should hide APIs that specified by the `[Exclude` metadata tags.

A typical example is the `Stage` class:

```as
[Exclude(name="y",kind="property")]
[Exclude(name="x",kind="property")]
[Exclude(name="visible",kind="property")]
[Exclude(name="transform",kind="property")]
[Exclude(name="tabIndex",kind="property")]
[Exclude(name="tabEnabled",kind="property")]
[Exclude(name="scrollRect",kind="property")]
[Exclude(name="scaleY",kind="property")]
[Exclude(name="scaleX",kind="property")]
[Exclude(name="scale9Grid",kind="property")]
[Exclude(name="rotation",kind="property")]
[Exclude(name="opaqueBackground",kind="property")]
[Exclude(name="name",kind="property")]
[Exclude(name="mouseEnabled",kind="property")]
[Exclude(name="mask",kind="property")]
[Exclude(name="loaderInfo",kind="property")]
[Exclude(name="focusRect",kind="property")]
[Exclude(name="filters",kind="property")]
[Exclude(name="contextMenu",kind="property")]
[Exclude(name="cacheAsBitmap",kind="property")]
[Exclude(name="blendMode",kind="property")]
[Exclude(name="alpha",kind="property")]
[Exclude(name="accessibilityProperties",kind="property")]
[Exclude(name="accessibilityImplementation",kind="property")]
```

The `kind` can be `property|method|event|style|effect`.

A real example:

```as
[Exclude(name="hasEventListener",	kind="method")]

/**
 * deprecated: Use hasListener or hasEvent
 */
override public function hasEventListener(type:String):Boolean
{
	...
}

public function hasEvent(type:String):Boolean
{
	...
}

public function hasListener(listener:Function):Boolean
{
	...
}
```

Thanks!

**Comment by joshtynjala** [comment]
`[Exclude]` metadata is supported.

https://github.com/BowlerHatLLC/vscode-as3mxml/blob/199a9cbb406925140488c1d83b62bd2a50303d76/language-server/src/main/java/com/as3mxml/vscode/providers/CompletionProvider.java#L1845-L1857

You need to add `[Exclude]` metadata above the class definition.

```as3
[Exclude(name="hasEventListener",	kind="method")]

class MyClass {}
```

**Comment by ylazy** [comment]
> You need to add [Exclude] metadata above the class definition.

I see it worked with the class that has [Exclude] metadata, but it does not work with sub-classes.

Thanks!

**Comment by ylazy** [comment]
Hi!

I've tried the latest snapshot but I still see the excluded members in sub-classes.

![image](https://github.com/user-attachments/assets/6cbb6136-1fce-4e19-897b-f58e5274c938)
![image](https://github.com/user-attachments/assets/0bb3677b-33da-4a58-899c-6598c6d12cb1)
![image](https://github.com/user-attachments/assets/5d6f1c84-289e-44d9-be24-300526b02157)

Could you recheck this?

Thank you!

**Comment by joshtynjala** [comment]
> Could you recheck this?

In my test project, it appears to be working correctly. I can add `[Exclude]` to any class in the inheritance chain, and the member is correctly excluded from completion.

**Comment by ylazy** [comment]
There was a problem when I installed the latest extension snapshot. It show me a progress bar for a long time (over a minute) until it finished. Maybe that was the cause. I re-built and & re-installed the vsix 2 times until it did not show the progress bar anymore, restart vscode, then it's working fine now.

Thank you!
